Repository nasa/cumulus, pull requests merged in 2018-11, with the labels that each got.

#670 CUMULUS-965 Remove cwait package
  packages/api/lambdas/ems-distribution-report.js
  packages/api/package.json
  packages/api/tests/lambdas/create-reconciliation-report.js
  packages/common/aws.js
  packages/common/concurrency.js
  packages/common/package.json
Labels: in review

#685 CUMULUS-656 Disable lerna hoisting
  package.json
  travis-ci/build-cache.sh
Labels: in review, needs review

#681 CUMULUS-661 Tests for listing/retrieving executions and execution statuses
  example/spec/parallel/ingest/ingestFromPdrSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleFailureSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/standalone/redeployment/WorkflowRedeploySpec.js
  packages/api/endpoints/executions.js
  packages/api/lib/testUtils.js
  packages/api/tests/endpoints/executions.js
  packages/api/tests/serial/endpoints/executions.js
  packages/integration-tests/api/api.js
  packages/integration-tests/api/executions.js
  packages/integration-tests/index.js
Labels: PR feedback

#671 CUMULUS-906|790|783: duplicate handling changes for reingest
  CHANGELOG.md
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/syncGranule/SyncGranuleSuccessSpec.js
  example/workflows/sips.yml
  packages/api/endpoints/granules.js
  packages/api/lambdas/sf-scheduler.js
  packages/api/models/granules.js
  packages/api/models/rules.js
  packages/api/tests/serial/endpoints/granules.js
  packages/ingest/granule.js
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/hello-world/package.json
  tasks/move-granules/index.js
  tasks/move-granules/package.json
  tasks/move-granules/tests/index-test.js
  tasks/parse-pdr/package.json
  tasks/pdr-status-check/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-granules/package.json
  tasks/queue-pdrs/package.json
  tasks/sf-sns-report/package.json
  tasks/sync-granule/index.js
  tasks/sync-granule/package.json
  tasks/sync-granule/tests/sync_granule_test.js
  tasks/test-processing/package.json
Labels: in review

#688 Reject move granule via API if file exists at destination location
  CHANGELOG.md
  example/spec/parallel/discoverGranules/DiscoverGranulesHttpsSpec.js
  example/spec/parallel/ingest/ingestFromPdrSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleDuplicateHandlingSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleFailureSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleFtpSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/syncGranule/SyncGranuleDuplicateHandlingSpec.js
  example/spec/parallel/syncGranule/SyncGranuleSuccessSpec.js
  packages/api/endpoints/granules.js
  packages/api/models/granules.js
  packages/api/tests/models/test-granules-model.js
  packages/api/tests/serial/endpoints/granules.js
  packages/ingest/granule.js
  packages/ingest/test/granule.js
  packages/integration-tests/api/api.js
  packages/integration-tests/api/granules.js
  packages/integration-tests/granule.js
  packages/integration-tests/index.js
Labels: in review

#661 CUMULUS-658 Delete rules using the API (tests)
  example/spec/parallel/testAPI/ruleSpec.js
  packages/api/tests/serial/endpoints/rules.js
  packages/integration-tests/api/rules.js
  packages/integration-tests/index.js
Labels: PR feedback

#704 Cumulus 658 upgrade wait for test execution start
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/syncGranule/SyncGranuleSuccessSpec.js
  example/spec/parallel/testAPI/ruleSpec.js
  packages/integration-tests/index.js
Labels: needs review

#697 CUMULUS-977: Trigger workflow via SNS
  CHANGELOG.md
  docs/assets/schedule-workflows.png
  docs/data-cookbooks/cnm-workflow.md
  docs/data-cookbooks/setup.md
  docs/system-documentation/system-documentation.md
  docs/workflows/workflow-triggers.md
  example/spec/parallel/kinesisTests/KinesisTestErrorSpec.js
  example/spec/parallel/kinesisTests/KinesisTestTriggerSpec.js
  example/spec/parallel/testAPI/ruleSpec.js
  example/spec/parallel/testAPI/snsRuleDef.json
  example/spec/parallel/testAPI/snsRuleSpec.js
  packages/api/README.md
  packages/api/config/api_default.yml
  packages/api/config/api_v1.yml
  packages/api/config/lambdas.yml
  packages/api/index.js
  packages/api/lambdas/message-consumer.js
  packages/api/lib/rulesHelpers.js
  packages/api/models/rules.js
  packages/api/package.json
  packages/api/tests/lambdas/test-kinesis-consumer.js
  packages/api/tests/lambdas/test-sns-consumer.js
  packages/api/tests/models/test-rules-model.js
  packages/api/tests/serial/migrations/migration_4.js
  packages/deployment/app/cloudformation.template.yml
  packages/deployment/app/cumulus_api.template.yml
  packages/deployment/iam/cloudformation.template.yml
  packages/integration-tests/api/rules.js
  packages/integration-tests/index.js
Labels: PR feedback

#700 Cumulus 919
  CHANGELOG.md
  README.md
  docs/data-cookbooks/cnm-workflow.md
  docs/data-cookbooks/error-handling.md
  docs/data-cookbooks/setup.md
  docs/deployment/README.md
  example/README.md
  example/app/config.yml
  example/fake-server.yml
  example/iam/config.yml
  packages/deployment/iam/cloudformation.template.yml
  packages/deployment/iam/config.yml
Labels: in review

#719 Fix issue where events were not properly pulled from S3
  CHANGELOG.md
  packages/api/lambdas/sf-sns-broadcast.js
  packages/common/aws.js
  packages/common/tests/aws.js
  packages/ingest/aws.js
Labels: PR feedback

#721 CUMULUS-952 Add ability to specify ecs repository authentication type
  docs/workflows/developing-workflow-tasks.md
  example/app/config.yml
  packages/deployment/app/cloudformation.template.yml
  packages/deployment/app/config.yml
Labels: PR feedback

#717 CUMULUS-989
  CHANGELOG.md
  example/app/.env.sample
  package.json
  packages/api/config/api_default.yml
  packages/api/config/api_v1.yml
  packages/api/endpoints/executions.js
  packages/api/endpoints/token.js
  packages/api/index.js
  packages/api/lib/EarthdataLogin.js
  packages/api/lib/GoogleOAuth2.js
  packages/api/lib/assertions.js
  packages/api/lib/response.js
  packages/api/lib/responses.js
  packages/api/lib/testUtils.js
  packages/api/lib/token.js
  packages/api/models/access-tokens.js
  packages/api/models/schemas.js
  packages/api/package.json
  packages/api/tests/endpoints/collections/create-collection.js
  packages/api/tests/endpoints/collections/delete-collection.js
  packages/api/tests/endpoints/collections/get-collection.js
  packages/api/tests/endpoints/collections/list-collections.js
  packages/api/tests/endpoints/collections/update-collection.js
  packages/api/tests/endpoints/execution-status.js
  packages/api/tests/endpoints/logs.js
  packages/api/tests/endpoints/providers/create-provider.js
  packages/api/tests/endpoints/providers/delete-provider.js
  packages/api/tests/endpoints/providers/get-provider.js
  packages/api/tests/endpoints/providers/list-providers.js
  packages/api/tests/endpoints/providers/update-provider.js
  packages/api/tests/endpoints/schemas.js
  packages/api/tests/endpoints/stats.js
  packages/api/tests/endpoints/test-endpoints-async-operations.js
  packages/api/tests/endpoints/test-endpoints-bulk-delete.js
  packages/api/tests/endpoints/test-instance-meta.js
  packages/api/tests/endpoints/token.js
  packages/api/tests/endpoints/workflows.js
  packages/api/tests/lib/EarthdataLogin.js
  packages/api/tests/lib/GoogleOAuth2.js
  packages/api/tests/lib/response.js
  packages/api/tests/models/test-access-tokens-model.js
  packages/api/tests/serial/endpoints/executions.js
  packages/api/tests/serial/endpoints/granules.js
  packages/api/tests/serial/endpoints/pdrs.js
  packages/api/tests/serial/endpoints/reconciliation-reports.js
  packages/api/tests/serial/endpoints/rules.js
  packages/deployment/app/config.yml
  packages/integration-tests/api/api.js
Labels: PR feedback
