Repository nasa/cumulus, pull requests merged in 2019-04, with the labels that each got.

#904 CUMULUS-1217: Deployment doc updates
  docs/deployment/README.md
  docs/deployment/obtain_cumulus_packages.md
  docs/development/release.md
  example/package.json
  packages/deployment/app.example/config.yml
  packages/deployment/app/config.yml
Labels: PR feedback

#908 CUMULUS-1198: remove leading slash from provider path expectations
  CHANGELOG.md
  packages/api/lib/testUtils.js
  packages/api/models/schemas.js
  packages/api/tests/data/granule_failed.json
  packages/api/tests/data/granule_success.json
  packages/api/tests/data/pdr_failure.json
  packages/api/tests/data/pdr_success.json
  packages/api/tests/endpoints/collections/update-collection.js
  packages/ingest/ftp.js
  packages/ingest/granule.js
  packages/ingest/pdr.js
  packages/ingest/recursion.js
  packages/ingest/s3.js
  packages/ingest/sftp.js
  packages/ingest/test/test-ftp.js
  packages/ingest/test/test-http.js
  packages/ingest/test/test-sftp.js
  packages/ingest/test/test-util.js
  packages/ingest/util.js
  packages/test-data/cumulus_messages/discover-pdrs.json
  packages/test-data/cumulus_messages/discover-s3-granules.json
  packages/test-data/cumulus_messages/parse-pdr.json
  packages/test-data/cumulus_messages/pdr-status-check.json
  packages/test-data/cumulus_messages/post-to-cmr.json
  packages/test-data/cumulus_messages/sync-granule.json
  packages/test-data/payloads/amsr2/discover.json
  packages/test-data/payloads/modis/cmr.json
  packages/test-data/payloads/modis/discover.json
  packages/test-data/payloads/modis/ingest-checksumfile.json
  packages/test-data/payloads/modis/ingest.json
  packages/test-data/payloads/modis/parse.json
  packages/test-data/payloads/mur/discover.json
  packages/test-data/payloads/new-message-schema/cmr.json
  packages/test-data/payloads/new-message-schema/discover.json
  packages/test-data/payloads/new-message-schema/ingest-checksumfile.json
  packages/test-data/payloads/new-message-schema/ingest.json
  packages/test-data/payloads/new-message-schema/parse.json
  tasks/discover-granules/tests/fixtures/mur.json
  tasks/discover-granules/tests/index.js
  tasks/discover-pdrs/tests/fixtures/input.json
  tasks/move-granules/tests/data/payload.json
  tasks/queue-pdrs/tests/fixtures/input.json
Labels: PR feedback

#915 Cumulus 1183: Add lambda configuration check to kes
  .eslintrc.json
  CHANGELOG.md
  packages/deployment/lib/configValidators.js
  packages/deployment/lib/kes.js
  packages/deployment/test/test_configValidations.js
  packages/deployment/test/test_kes.js
Labels: PR feedback

#910 CUMULUS-777: Ancillary File in Granule & CMR Record Feature Validation
  CHANGELOG.md
  docs/data-cookbooks/browse-generation.md
  docs/data-cookbooks/tracking-files.md
  docs/features/ancillary_metadata.md
  docs/tasks.md
  packages/cmrjs/cmr-utils.js
  packages/cmrjs/tests/cmr-utils/test-cmr-utils.js
  packages/cmrjs/tests/fixtures/UMMGFilesObjectFixture.json
  tasks/files-to-granules/package.json
  website/i18n/en.json
  website/sidebars.json
Labels: PR feedback

#912 Fix issues with indexer
  CHANGELOG.md
  example/app/config.yml
  packages/api/models/base.js
  packages/api/models/files.js
  packages/api/tests/models/test-files-model.js
  packages/deployment/app/cumulus_api.template.yml
  packages/deployment/iam/cloudformation.template.yml
Labels: PR feedback

#919 CUMULUS-1216: SyncGranules should download files to expected staging location
  CHANGELOG.md
  packages/deployment/test/fixtures/config.json
  packages/ingest/granule.js
  packages/ingest/test/test-granule.js
  packages/test-data/granules/MOD09GQ.A2017224.h27v08.006.2017227165029.hdf.met
  packages/test-data/payloads/new-message-schema/ingest-multigran.json
  tasks/sync-granule/index.js
  tasks/sync-granule/tests/sync_granule_test.js
Labels: PR feedback

#932 Move public files behind distribution endpoint.
  CHANGELOG.md
  example/spec/helpers/testUtils.js
  example/spec/ingestGranule/IngestUMMGSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  packages/api/tests/lambdas/create-reconciliation-report.js
  packages/cmrjs/cmr-utils.js
  packages/cmrjs/tests/cmr-utils/test-cmr-utils.js
  packages/cmrjs/tests/cmr-utils/test-constructurls.js
  packages/ingest/test/test-ftp.js
  packages/ingest/test/test-sftp.js
  packages/integration-tests/api/distribution.js
Labels: PR feedback, needs review

#936 Cumulus 1203
  CHANGELOG.md
  example/iam/config.yml
  example/spec/helpers/configUtils.js
  example/spec/helpers/testUtils.js
  example/spec/standalone/redeployment/TemplateOverrideDeploySpec.js
  packages/common/local-helpers.js
  packages/deployment/iam/cloudformation.template.yml
Labels: PR feedback

#945 CUMULUS-1203 Add missing refactor changes redeploy->runKes
  example/spec/helpers/configUtils.js
  example/spec/helpers/testUtils.js
  example/spec/standalone/redeployment/LambdaRedeploySpec.js
  example/spec/standalone/redeployment/LambdaVersionOption.js
  example/spec/standalone/redeployment/WorkflowRedeploySpec.js
  packages/deployment/app/cloudformation.template.yml
Labels: needs review

#940 CUMULUS-1232: Deduplicate duplicate-handling code
  CHANGELOG.md
  example/spec/createReconciliationReport/IngestGranule.MYD13Q1_006.input.payload.json
  example/spec/parallel/ingest/ingestFromPdrSpec.js
  example/spec/parallel/ingest/resources/ParsePdr.output.json
  example/spec/parallel/ingestGranule/IngestGranule.UMM.output.payload.template.json
  example/spec/parallel/ingestGranule/IngestGranule.input.payload.json
  example/spec/parallel/ingestGranule/IngestGranule.output.payload.template.json
  example/spec/parallel/ingestGranule/IngestGranuleFtp.input.payload.json
  example/spec/parallel/ingestGranule/SyncGranule.output.payload.template.json
  example/spec/parallel/kinesisTests/data/records/L2_HR_PIXC_product_0001-of-4154.json
  packages/common/aws.js
  packages/common/errors.js
  packages/ingest/granule.js
  packages/ingest/http.js
  packages/ingest/protocol.js
  packages/ingest/s3.js
  packages/ingest/sftp.js
  packages/ingest/test/test-granule.js
  packages/ingest/test/test-queue.js
  packages/ingest/test/test-sftp.js
  packages/test-data/payloads/new-message-schema/ingest-checksumfile.json
  packages/test-data/pdrs/MOD09GQ_1granule_v3.PDR
  tasks/move-granules/index.js
  tasks/sync-granule/tests/sync_granule_test.js
Labels: PR feedback

#960 CUMULUS-1157 Add audit check conditionals
  bamboo/audit.sh
Labels: needs review

#953 Point changelog to CLI command
  CHANGELOG.md
Labels: needs review
