Repository nasa/cumulus, pull requests merged in 2019-10, with the labels that each got.

#1212 Add remaining TF resources defined in the spreadsheet
  example/cumulus-tf/ecs_hello_world_workflow.tf
  tf-modules/archive/bootstrap.tf
  tf-modules/archive/fetch_or_create_rsa_keys.sh
  tf-modules/cumulus/outputs.tf
  tf-modules/cumulus_ecs_service/main.tf
  tf-modules/cumulus_ecs_service/outputs.tf
  tf-modules/ingest/discover-pdrs-task.tf
  tf-modules/ingest/parse-pdr-task.tf
  tf-modules/ingest/queue-pdrs-task.tf
Labels: PR feedback

#1215 Add listEcsClusters tests
  packages/common/tests/test-ecs.js
Labels: needs review

#1209 Cumulus 639 mhs
  .eslintignore
  CHANGELOG.md
  docs/deployment/README.md
  docs/deployment/cumulus_api_launchpad_authentication.md
  example/app/config.yml
  packages/api/app/auth.js
  packages/api/app/index.js
  packages/api/app/launchpadAuth.js
  packages/api/app/launchpadSaml.js
  packages/api/app/routes.js
  packages/api/config/backend_api_lambdas.yml
  packages/api/package.json
  packages/api/tests/app/fixtures/_certificateFixture.js
  packages/api/tests/app/fixtures/bad-metadata.xml
  packages/api/tests/app/fixtures/launchpad-sbx-metadata.xml
  packages/api/tests/app/test-launchpadAuth.js
  packages/api/tests/app/test-launchpadSaml.js
  packages/api/webpack.config.js
  packages/deployment/app/config.yml
Labels: needs review

#1222 CUMULUS-1485: Update cmr-client to return error message from CMR for validation failures
  CHANGELOG.md
  packages/cmr-client/CMR.js
  packages/cmr-client/UmmUtils.js
  packages/cmr-client/tests/test-CMR.js
  packages/cmr-client/tests/test-UmmUtils.js
  packages/cmrjs/tests/test-utils.js
Labels: needs review

#1230 Update terraform int tests
  bamboo/abort-if-not-pr-or-master.sh
  bamboo/abort-if-not-pr.sh
  bamboo/abort-if-terraform-branch.sh
  bamboo/audit.sh
  bamboo/bootstrap-integration-tests.sh
  bamboo/bootstrap-lint-audit.sh
  bamboo/bootstrap-unit-tests.sh
  bamboo/cleanup-integration-tests.sh
  bamboo/cleanup-unit-tests.sh
  bamboo/integration-tests.sh
  bamboo/lint.sh
  bamboo/set-bamboo-env-variables.sh
  bamboo/set-status.sh
  bamboo/unit-tests.sh
Labels: needs review

#1231 Fix issues found during release process
  bamboo/bootstrap-publish.sh
  package.json
Labels: needs review

#1243 CUMULUS-1571: Integrate new workflow reporting with TF deployment
  CHANGELOG.md
  docs/data-cookbooks/sns.md
  example/cumulus-tf/discover_and_queue_pdrs_workflow.tf
  example/cumulus-tf/discover_granules_workflow.tf
  example/cumulus-tf/ecs_hello_world_workflow.tf
  example/cumulus-tf/hello_world_fail_workflow.tf
  example/cumulus-tf/hello_world_workflow.tf
  example/cumulus-tf/ingest_and_publish_granule_workflow.tf
  example/cumulus-tf/ingest_granule_catch_duplicate_error_test_workflow.tf
  example/cumulus-tf/ingest_granule_workflow.tf
  example/cumulus-tf/kinesis_trigger_test_workflow.tf
  example/cumulus-tf/parse_pdr_workflow.tf
  example/cumulus-tf/publish_granule_workflow.tf
  example/cumulus-tf/retry_fail_workflow.tf
  example/cumulus-tf/retry_pass_workflow.tf
  example/cumulus-tf/sync_granule_catch_duplicate_error_test_workflow.tf
  example/cumulus-tf/sync_granule_workflow.tf
  packages/api/config/lambdas.yml
  packages/api/es/indexer.js
  packages/api/models/executions.js
  packages/api/tests/models/test-files-model.js
  packages/api/tests/serial/es/test-es-indexer.js
  packages/common/DynamoDb.js
  packages/common/tests/data/ingest_granule_fail_history.json
  packages/common/tests/data/ingest_publish_granule_fail_history.json
  packages/common/tests/test-DynamoDb.js
  packages/integration-tests/index.js
  tf-modules/archive/outputs.tf
  tf-modules/archive/publish_reports.tf
  tf-modules/archive/sns2elasticsearch.tf
  tf-modules/cumulus/ingest.tf
  tf-modules/cumulus/outputs.tf
  tf-modules/ingest/lambda-functions.tf
  tf-modules/ingest/message_template.tf
  tf-modules/ingest/outputs.tf
  tf-modules/ingest/variables.tf
  tf-modules/workflow/main.tf
  tf-modules/workflow/variables.tf
Labels: PR feedback

#1198 CUMULUS-1308 Handle deletion of fields via the API
  CHANGELOG.md
  audit-ci.json
  bamboo/select-stack.js
  example/app/config.yml
  example/spec/parallel/testAPI/ruleSpec.js
  example/spec/parallel/testAPI/snsRuleSpec.js
  packages/api/endpoints/collections.js
  packages/api/endpoints/providers.js
  packages/api/endpoints/rules.js
  packages/api/models/base.js
  packages/api/models/rules.js
  packages/api/models/schemas.js
  packages/api/tests/endpoints/collections/update-collection.js
  packages/api/tests/endpoints/providers/update-provider.js
  packages/api/tests/models/test-rules-model.js
  packages/api/tests/serial/endpoints/test-rules.js
  packages/integration-tests/api/api.js
  packages/integration-tests/api/rules.js
  packages/integration-tests/index.js
Labels: PR feedback

#1249 Simplify test config
  example/.gitignore
  example/app/config.yml
  example/config.yml
  example/cumulus-tf/main.tf
  example/cumulus-tf/variables.tf
  example/package.json
  example/spec/backupRestore/BackupRestoreSpec.js
  example/spec/discoverGranules/DiscoverGranulesHttpSpec.js
  example/spec/helpers/kinesisHelpers.js
  example/spec/helpers/testUtils.js
  example/spec/parallel/asyncOperations/asyncOperationRunnerSpec.js
  example/spec/parallel/bulkDelete/bulkDeleteSpec.js
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesHttpsSpec.js
  example/spec/parallel/distributionAPI/distributionSpec.js
  example/spec/parallel/emsReport/emsIngestDistributionReportSpec.js
  example/spec/parallel/emsReport/emsProductMetadataReportSpec.js
  example/spec/parallel/helloWorld/HelloWorldEcsSpec.js
  example/spec/parallel/ingest/ingestFromPdrSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleDuplicateHandlingSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleFailureSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleFtpSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestUMMGSuccessSpec.js
  example/spec/parallel/kinesisTests/KinesisTestErrorSpec.js
  example/spec/parallel/kinesisTests/KinesisTestTriggerSpec.js
  example/spec/parallel/kinesisTests/LambdaEventSourceSpec.js
  example/spec/parallel/kinesisTests/data/lambdaEventSourceTestRules/L2_HR_PIXC_kinesisRule.json
  example/spec/parallel/kinesisTests/data/lambdaEventSourceTestRules/MOD09GQ_kinesisRule.json
  example/spec/parallel/kinesisTests/data/rules/L2_HR_PIXC_kinesisRule.json
  example/spec/parallel/retryConfiguration/retryConfigurationSpec.js
  example/spec/parallel/s3Access/legacyS3AccessSpec.js
  example/spec/parallel/s3Access/teaS3AccessSpec.js
  example/spec/parallel/startSF/startSfSpec.js
  example/spec/parallel/syncGranule/SyncGranuleDuplicateHandlingSpec.js
  example/spec/parallel/syncGranule/SyncGranuleSuccessSpec.js
  example/spec/parallel/testAPI/ruleSpec.js
  example/spec/parallel/testAPI/snsRuleSpec.js
  example/spec/setup/CleansUpTestResources.js
  example/spec/standalone/redeployment/LambdaRedeploySpec.js
  example/spec/standalone/redeployment/LambdaVersionOption.js
  example/spec/standalone/redeployment/TemplateOverrideDeploySpec.js
  example/spec/standalone/redeployment/WorkflowRedeploySpec.js
  packages/integration-tests/index.js
  tf-modules/archive/api.tf
  tf-modules/archive/variables.tf
  tf-modules/cumulus/archive.tf
  tf-modules/cumulus/variables.tf
Labels: DON'T EVEN LOOK AT THIS

#1258 Speed up integration tests
  example/scripts/run_test.sh
  example/scripts/tests-parallel.sh
  packages/integration-tests/index.js
Labels: needs review

#1257 CUMULUS-1483: Add sourcemaps for all Cumulus lambdas
  packages/api/.babelrc
  packages/api/package.json
  packages/api/webpack.config.js
  packages/integration-tests/.babelrc
  packages/integration-tests/package.json
  packages/integration-tests/webpack.config.js
  tasks/discover-granules/.babelrc
  tasks/discover-granules/package.json
  tasks/discover-granules/webpack.config.js
  tasks/discover-pdrs/.babelrc
  tasks/discover-pdrs/package.json
  tasks/discover-pdrs/webpack.config.js
  tasks/files-to-granules/.babelrc
  tasks/files-to-granules/package.json
  tasks/files-to-granules/webpack.config.js
  tasks/hello-world/.babelrc
  tasks/hello-world/package.json
  tasks/hello-world/webpack.config.js
  tasks/move-granules/.babelrc
  tasks/move-granules/package.json
  tasks/move-granules/webpack.config.js
  tasks/parse-pdr/.babelrc
  tasks/parse-pdr/package.json
  tasks/parse-pdr/webpack.config.js
  tasks/pdr-status-check/.babelrc
  tasks/pdr-status-check/package.json
  tasks/pdr-status-check/webpack.config.js
  tasks/post-to-cmr/.babelrc
  tasks/post-to-cmr/package.json
  tasks/post-to-cmr/webpack.config.js
  tasks/queue-granules/.babelrc
  tasks/queue-granules/package.json
  tasks/queue-granules/webpack.config.js
  tasks/queue-pdrs/.babelrc
  tasks/queue-pdrs/package.json
  tasks/queue-pdrs/webpack.config.js
  tasks/sf-sns-report/.babelrc
  tasks/sf-sns-report/package.json
  tasks/sf-sns-report/webpack.config.js
  tasks/sync-granule/.babelrc
  tasks/sync-granule/package.json
  tasks/sync-granule/webpack.config.js
  tasks/test-processing/.babelrc
  tasks/test-processing/package.json
  tasks/test-processing/webpack.config.js
  tf-modules/distribution/package.json
  tf-modules/distribution/webpack.config.js
  tf-modules/report-executions/webpack.config.js
  tf-modules/report-granules/webpack.config.js
  tf-modules/report-pdrs/webpack.config.js
Labels: needs review

#1267 CUMULUS-1625: Restore consumer rate in terraform deployment.
  CHANGELOG.md
  tf-modules/ingest/cloudwatch-events.tf
  tf-modules/ingest/variables.tf
Labels: needs review

#1256 CUMULUS-1513: support SQS-type rule in the Cumulus API
  CHANGELOG.md
  docs/data-cookbooks/setup.md
  example/app/config.yml
  example/spec/parallel/helloWorld/HelloWorldEcsSpec.js
  example/spec/parallel/testAPI/data/rules/sqs/MOD09GQ_006_sqsRule.json
  example/spec/parallel/testAPI/sqsRuleSpec.js
  example/workflows/helloworld.yml
  packages/api/config/lambdas.yml
  packages/api/es/search.js
  packages/api/lambdas/sqs-message-consumer.js
  packages/api/lib/rulesHelpers.js
  packages/api/models/executions.js
  packages/api/models/rules.js
  packages/api/models/schemas.js
  packages/api/package.json
  packages/api/tests/lambdas/test-sqs-message-consumer.js
  packages/api/tests/models/test-rules-model.js
  packages/api/webpack.config.js
  packages/common/aws.js
  packages/common/tests/test-aws.js
  packages/deployment/app/cloudformation.template.yml
  packages/deployment/app/config.yml
  packages/integration-tests/index.js
Labels: PR feedback

#1274 Cumulus 1513 terraform
  example/cumulus-tf/ingest_and_publish_granule_workflow.tf
  example/spec/parallel/testAPI/sqsRuleSpec.js
  tf-modules/ingest/cloudwatch-events.tf
  tf-modules/ingest/lambda-functions.tf
Labels: needs review

#1261 Cumulus 1452
  CHANGELOG.md
  example/scripts/tests-parallel.sh
  packages/deployment/app/config.yml
  tf-modules/cumulus/ecs_cluster.tf
  tf-modules/cumulus/ecs_cluster_instance_autoscaling_cf_template.yml.tmpl
  tf-modules/cumulus/variables.tf
Labels: PR feedback

#1265 CUMULUS-1560: Update deployment docs for Terraform
  docs/deployment/README.md
  docs/deployment/components.md
  docs/deployment/obtain_cumulus_packages.md
  docs/deployment/thin-egress-app.md
  docs/workflows/input_output.md
  tf-modules/README.md
  tf-modules/archive/variables.tf
  tf-modules/cumulus-message-adapter/README.md
  tf-modules/cumulus-message-adapter/outputs.tf
  tf-modules/cumulus/README.md
  tf-modules/cumulus/variables.tf
  tf-modules/data-persistence/README.md
  tf-modules/data-persistence/terraform.tfvars.example
  tf-modules/distribution/README.md
Labels: in review
