Repository nasa/cumulus, pull requests merged in 2019-05, with the labels that each got.

#959 Cumulus 1156
  bamboo/audit.sh
  bamboo/bootstrap-sftp.sh
  bamboo/bootstrap-unit-tests.sh
  bamboo/cleanup-unit-tests.sh
  bamboo/docker-compose.yml
  bamboo/elasticsearch.config
  bamboo/httpd.conf
  bamboo/unit-test-install-dependencies.sh
  bamboo/unit-tests.sh
  package.json
  packages/cmrjs/index.js
Labels: needs review

#969 CUMULUS-1231 Use NGAP-approved AMI for integration tests fake provider
  example/data/providers/ftp/ftp_provider.json
  example/data/providers/http/http_provider.json
  example/data/providers/https/https_provider.json
  example/fake-server.yml
Labels: in review, needs review

#980 Update audit-ci to 1.7.0, remove tar whitelist
  audit-ci.json
  package.json
Labels: PR feedback

#971 Trim granule names upon discovery
  packages/ingest/http.js
  packages/ingest/test/test-http.js
Labels: in review

#975 CUMULUS-1160 Fix stack locking bug
  example/scripts/lock-stack.js
  travis-ci/init-integration-tests.sh
Labels: PR feedback

#982 Cumulus 1265 lambdas in vpc
  CHANGELOG.md
  docs/data-cookbooks/browse-generation.md
  example/lambdas.yml
  example/spec/parallel/ingestGranule/IngestGranuleFailureSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/syncGranule/SyncGranuleDuplicateHandlingSpec.js
  example/workflows/browseExample.yml
  example/workflows/ingestGranule.yml
  example/workflows/sips.yml
  example/workflows/syncGranule.yml
  packages/api/config/lambdas.yml
  packages/api/tests/endpoints/execution-status.js
Labels: PR feedback

#967 Cumulus-1102 Preparing local API for dashboard Cypress tests
  audit-ci.json
  packages/api/app/testAuth.js
  packages/api/bin/cli.js
  packages/api/bin/serve.js
  packages/api/endpoints/collections.js
  packages/api/endpoints/executions.js
  packages/api/endpoints/granules.js
  packages/api/endpoints/pdrs.js
  packages/api/endpoints/providers.js
  packages/api/endpoints/rules.js
  packages/api/es/indexer.js
  packages/api/lambdas/db-indexer.js
  packages/api/models/collections.js
  packages/api/models/executions.js
  packages/api/models/granules.js
  packages/api/models/pdrs.js
  packages/api/models/providers.js
  packages/api/models/rules.js
  packages/api/package.json
  packages/api/tests/endpoints/collections/create-collection.js
  packages/api/tests/endpoints/collections/delete-collection.js
  packages/api/tests/endpoints/collections/get-collection.js
  packages/api/tests/endpoints/collections/list-collections.js
  packages/api/tests/endpoints/collections/update-collection.js
  packages/api/tests/endpoints/providers/create-provider.js
  packages/api/tests/endpoints/providers/delete-provider.js
  packages/api/tests/endpoints/providers/get-provider.js
  packages/api/tests/endpoints/providers/list-providers.js
  packages/api/tests/endpoints/providers/update-provider.js
  packages/api/tests/endpoints/workflows.js
  packages/api/tests/serial/endpoints/test-executions.js
  packages/api/tests/serial/endpoints/test-granules.js
  packages/api/tests/serial/endpoints/test-pdrs.js
  packages/api/tests/serial/endpoints/test-rules.js
  packages/api/tests/serial/es/test-db-indexer.js
  packages/api/tests/serial/es/test-es-indexer-log.js
  packages/api/tests/serial/es/test-es-indexer.js
Labels: PR feedback

#989 Cumulus 1235 - Add SIT builds to bamboo CI
  bamboo/set-bamboo-env-variables.sh
  example/app/config.yml
  example/iam/config.yml
  example/scripts/tests-parallel.sh
Labels: PR feedback

#1002 Redeploy tests fix
  example/spec/helpers/testUtils.js
  example/spec/standalone/redeployment/TemplateOverrideDeploySpec.js
  travis-ci/select-stack.js
Labels: needs review

#1007 Cumulus 1161 -- Add github status to build
  bamboo/abort-if-not-pr-or-master.sh
  bamboo/abort-if-not-pr-or-redeployment.sh
  bamboo/abort-if-skip-integration-tests.sh
  bamboo/select-stack.js
  bamboo/set-status.sh
Labels: PR feedback

#1011 CUMULUS-1241: Change queue config structure
  example/app/config.yml
  packages/api/lambdas/sf-semaphore-down.js
  packages/api/lambdas/sf-starter.js
  packages/api/lib/message.js
  packages/api/tests/lambdas/test-sf-semaphore-down.js
  packages/api/tests/lambdas/test-sf-starter.js
  packages/deployment/lib/configValidators.js
  packages/deployment/lib/message.js
  packages/deployment/test/fixtures/config.json
  packages/deployment/test/test_configValidations.js
  packages/deployment/test/test_message.js
Labels: needs review

#1026 Fix unwaited for promise returns on genericRecordUpdate functions
  packages/api/tests/endpoints/providers/list-providers.js
  packages/api/tests/serial/endpoints/test-rules.js
Labels: PR feedback

#1015 Cumulus-1192 Add api endpoint to return CSV file of all granules
  example/app/config.yml
  packages/api/app/routes.js
  packages/api/bin/serve.js
  packages/api/endpoints/granule-csv.js
  packages/api/endpoints/granules.js
  packages/api/models/granules.js
  packages/api/package.json
  packages/api/tests/serial/endpoints/test-granule-csv.js
  travis-ci/select-stack.js
Labels: needs review

#1018 Cumulus 779 distribution metrics endpoint
  CHANGELOG.md
  docker-compose.yml
  docs/deployment/config_descriptions.md
  example/app/config.yml
  example/spec/parallel/distributionMetrics/distributionMetricsSpec.js
  packages/api/app/routes.js
  packages/api/config/backend_api_lambdas.yml
  packages/api/endpoints/distribution-metrics.js
  packages/api/tests/endpoints/fixtures/distribution-metrics-fixture.js
  packages/api/tests/endpoints/test-distribution-metrics.js
  packages/common/aws.js
  packages/common/test-utils.js
  packages/deployment/iam/cloudformation.template.yml
  packages/integration-tests/api/api.js
Labels: PR feedback
