Repository nasa/cumulus, pull requests merged in 2019-03, with the labels that each got.

#850 CUMULUS-671: Verify Earthdata login for distribution logs
  CHANGELOG.md
  docs/ems_reporting.md
  example/spec/distributionAPI/distributionSpec.js
  example/spec/ingestGranule/IngestUMMGSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/workflows/sips.yml
  packages/api/lambdas/ems-distribution-report.js
  packages/api/tests/models/test-granules-model.js
  packages/cmrjs/cmr-utils.js
  packages/cmrjs/tests/test-utils.js
  packages/cmrjs/utils.js
  packages/integration-tests/api/distribution.js
  packages/integration-tests/api/granules.js
  tasks/post-to-cmr/index.js
Labels: PR feedback

#854 CUMULUS-1187: Fix bug reading duplicate handling from collection
  CHANGELOG.md
  packages/ingest/granule.js
  tasks/move-granules/index.js
  tasks/move-granules/tests/test-index.js
  tasks/sync-granule/index.js
  tasks/sync-granule/package.json
  tasks/sync-granule/tests/sync_granule_test.js
Labels: PR feedback

#855 Fix tasks doc build failing if a task does not have package.json
  bin/build-tasks-doc.js
Labels: in review

#852 Move CUMULUS-1139 changelog to right place
  CHANGELOG.md
Labels: PR feedback

#841 CUMULUS-1101: Separate checksum validation code into separate package
  CHANGELOG.md
  example/package.json
  example/spec/distributionAPI/distributionSpec.js
  example/spec/ingestGranule/IngestUMMGSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  packages/checksum/.npmignore
  packages/checksum/README.md
  packages/checksum/checksum.js
  packages/checksum/index.js
  packages/checksum/package.json
  packages/checksum/tests/data/dummyfile.txt
  packages/checksum/tests/test-checksum.js
  packages/checksum/validate.js
  packages/common/aws.js
  packages/common/file.js
  packages/common/index.js
  packages/common/package.json
  packages/common/tests/test-aws.js
  packages/ingest/granule.js
  packages/ingest/test/test-ftp.js
  packages/ingest/test/test-granule.js
  packages/ingest/test/test-http.js
  packages/ingest/test/test-sftp.js
  tasks/move-granules/index.js
  tasks/sync-granule/tests/sync_granule_test.js
Labels: PR feedback

#839 Cumulus 666 s3 credential endpoint
  CHANGELOG.md
  example/README.md
  example/app/config.yml
  example/iam/config.yml
  example/lambdas/s3AccessTest/index.js
  example/spec/s3Access/s3AccessSpec.js
  packages/api/app/auth.js
  packages/api/app/routes.js
  packages/api/app/testAuth.js
  packages/api/config/api.yml
  packages/api/endpoints/s3credentials.js
  packages/api/lib/testUtils.js
  packages/api/tests/endpoints/test-s3credentials.js
  packages/deployment/app/config.yml
  travis-ci/init-integration-tests.sh
Labels: needs review

#863 fix packages/integration-tests/sfnStep.js
  packages/integration-tests/sfnStep.js
Labels: needs review

#859 Release 1.11.3
  CHANGELOG.md
  example/package.json
  lerna.json
  packages/api/package.json
  packages/deployment/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/move-granules/package.json
  tasks/parse-pdr/package.json
  tasks/pdr-status-check/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-granules/package.json
  tasks/queue-pdrs/package.json
  tasks/sf-sns-report/package.json
  tasks/sync-granule/package.json
  tasks/test-processing/package.json
  website/versions.json
Labels: in review

#870 Use granule UR to remove a granule from CMR
  CHANGELOG.md
  packages/api/app/routes.js
  packages/api/endpoints/granules.js
  packages/api/lib/testUtils.js
  packages/api/models/granules.js
  packages/api/tests/models/test-granules-model.js
  packages/api/tests/serial/endpoints/test-granules.js
Labels: PR feedback

#867 Cumulus 670 feature branch
  CHANGELOG.md
  example/data/collections/http_testcollection_001/http_testcollection_001.json
  example/lambdas.yml
  example/spec/createReconciliationReport/CreateReconciliationReportSpec.js
  example/spec/createReconciliationReport/IngestGranule.MYD13Q1_006.input.payload.json
  example/spec/discoverGranules/DiscoverGranulesHttpSpec.js
  example/spec/ingestGranule/IngestGranule.UMM.output.payload.template.json
  example/spec/ingestGranule/IngestUMMGSuccessSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesHttpsSpec.js
  example/spec/parallel/ingestGranule/IngestGranule.input.payload.json
  example/spec/parallel/ingestGranule/IngestGranule.output.payload.template.json
  example/spec/parallel/ingestGranule/IngestGranuleFtp.input.payload.json
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/ingestGranule/SyncGranule.output.payload.template.json
  example/spec/parallel/kinesisTests/KinesisTestTriggerSpec.js
  example/spec/parallel/syncGranule/SyncGranule.input.payload.json
  example/spec/parallel/syncGranule/SyncGranule.output.payload.template.json
  packages/api/lib/testUtils.js
  packages/api/models/schemas.js
  packages/cmrjs/cmr-utils.js
  packages/cmrjs/package.json
  packages/cmrjs/tests/cmr-utils/test-cmr-utils.js
  packages/cmrjs/tests/cmr-utils/test-constructonlineaccessurls.js
  packages/cmrjs/tests/fixtures/MOD09GQ.A3411593.1itJ_e.006.9747594822314.cmr.json
  packages/cmrjs/tests/fixtures/buckets.json
  packages/cmrjs/tests/fixtures/cmrFileUpdateFixture.cmr.xml
  packages/cmrjs/tests/fixtures/filesObjectFixture.json
  packages/common/test-utils.js
  packages/ingest/granule.js
  packages/ingest/parse-pdr.js
  packages/ingest/test/test-parse-pdr.js
  packages/integration-tests/cmr.js
  packages/test-data/cumulus_messages/post-to-cmr.json
  packages/test-data/payloads/new-message-schema/ingest.json
  packages/test-data/pdrs/MOD09GQ-with-invalid-file-type.PDR
  tasks/discover-granules/schemas/output.json
  tasks/discover-granules/tests/fixtures/mur.json
  tasks/discover-granules/tests/index.js
  tasks/move-granules/index.js
  tasks/move-granules/schemas/output.json
  tasks/move-granules/tests/data/payload.json
  tasks/move-granules/tests/test-index.js
  tasks/parse-pdr/schemas/output.json
  tasks/parse-pdr/tests/parse_pdrs_test.js
  tasks/post-to-cmr/schemas/output.json
  tasks/post-to-cmr/tests/data/payload.json
  tasks/queue-granules/schemas/input.json
  tasks/sync-granule/schemas/input.json
  tasks/sync-granule/schemas/output.json
Labels: PR feedback

#888 Just a quick change to travis
  .travis.yml
Labels: PR feedback

#890 Report should only scan completed granules
  CHANGELOG.md
  packages/api/lambdas/create-reconciliation-report.js
Labels: PR feedback, bug

#891 CUMULUS-1208: Update queue-granules to not transform granule objects
  CHANGELOG.md
  packages/ingest/queue.js
  packages/ingest/test/test-queue.js
Labels: in review

#885 CUMULUS-805: Create ElasticSearch Alarm and CW dashboard
  CHANGELOG.md
  docs/deployment/config_descriptions.md
  example/app/.env.sample
  packages/deployment/app.example/.env.sample
  packages/deployment/app/cloudformation.template.yml
  packages/deployment/app/cloudwatchDashboard.yml
  packages/deployment/app/config.yml
  packages/deployment/lib/kes.js
  packages/deployment/package.json
Labels: PR feedback

#893 Cumulus 853 feature docs
  docs/data-cookbooks/setup.md
  docs/features/ancillary_metadata.md
  docs/workflow_tasks/discover_granules.md
  docs/workflow_tasks/move_granules.md
  docs/workflow_tasks/parse_pdr
  docs/workflow_tasks/parse_pdr.md
  packages/ingest/parse-pdr.js
  tasks/move-granules/index.js
  tasks/parse-pdr/schemas/output.json
  website/sidebars.json
Labels: PR feedback

#895 Fix SIT build
  .travis.yml
Labels: PR feedback

#909 Re-factor users config for deployment
  docs/deployment/config_descriptions.md
  example/app/config.yml
  packages/deployment/README.md
  packages/deployment/app/cloudformation.template.yml
  packages/deployment/app/config.yml
Labels: PR feedback
