Repository nasa/cumulus, pull requests merged in 2019-11, with the labels that each got.

#1296 Reorganize docs & minor fixes
  bin/build-tasks-doc.js
  docs/README.md
  docs/additional-deployment-options/cmr_launchpad_authentication.md
  docs/additional-deployment-options/cumulus_api_launchpad_authentication.md
  docs/architecture.md
  docs/deployment/server_access_logging.md
  docs/deployment/troubleshoot_deployment.md
  docs/glossary.md
  docs/interfaces.md
  website/sidebars.json
  website/siteConfig.js
Labels: needs review

#1301 update cmr launchpad and cumulus api launchpad in terraform
  bamboo/bootstrap-tf-deployment.sh
  docs/additional-deployment-options/cmr_launchpad_authentication.md
  docs/additional-deployment-options/cumulus_api_launchpad_authentication.md
  example/cumulus-tf/ingest_and_publish_granule_workflow.tf
  example/cumulus-tf/main.tf
  example/cumulus-tf/terraform.tfvars.example
  example/cumulus-tf/variables.tf
  example/deployments/cumulus-from-source.tfvars
  example/deployments/jl-tf.tfvars
  example/deployments/sandbox.tfvars
  example/spec/parallel/testAPI/ruleSpec.js
  example/spec/parallel/testAPI/snsRuleSpec.js
  tf-modules/archive/bootstrap.tf
  tf-modules/archive/variables.tf
  tf-modules/cumulus/archive.tf
  tf-modules/cumulus/variables.tf
  tf-modules/cumulus_ecs_service/variables.tf
  tf-modules/ingest/variables.tf
Labels: PR feedback

#1299 Update audit whitelist
  audit-ci.json
Labels: needs review

#1288 [CUMULUS-1580] Use async-operations to kick off bulk operations
  CHANGELOG.md
  bamboo/select-stack.js
  bamboo/set-bamboo-env-variables.sh
  example/app/config.yml
  example/cumulus-tf/terraform.tfvars.example
  example/cumulus-tf/variables.tf
  example/package.json
  packages/api/config/backend_api_lambdas.yml
  packages/api/config/lambdas.yml
  packages/api/ecs/async-operation/README.md
  packages/api/endpoints/granules.js
  packages/api/lambdas/bulk-operation.js
  packages/api/lambdas/sf-scheduler.js
  packages/api/models/executions.js
  packages/api/models/granules.js
  packages/api/models/rules.js
  packages/api/models/schemas.js
  packages/api/tests/endpoints/granules/bulk-granule.js
  packages/api/tests/lambdas/test-sf-scheduler.js
  packages/api/webpack.config.js
  packages/common/message.js
  packages/common/tests/test-message.js
  packages/deployment/app/cloudformation.template.yml
  packages/deployment/app/cumulus_api.template.yml
  packages/deployment/iam/cloudformation.template.yml
  tf-modules/archive/api.tf
  tf-modules/archive/bulk_operation.tf
  tf-modules/archive/variables.tf
  tf-modules/cumulus/archive.tf
  tf-modules/cumulus/ecs_cluster.tf
  tf-modules/cumulus/variables.tf
Labels: in review

#1279 CUMULUS-1572: Fix granule discovery for files without file type config
  CHANGELOG.md
  docs/data-cookbooks/setup.md
  docs/workflow_tasks/discover_granules.md
  example/deployments/chuckulus-ci-tf.tfvars
  example/spec/discoverGranules/DiscoverGranulesHttpSpec.js
  example/spec/helpers/granuleUtils.js
  packages/api/models/schemas.js
  packages/api/tests/endpoints/granules/bulk-granule.js
  packages/common/test-utils.js
  packages/ingest/granule.js
  tasks/discover-granules/schemas/config.json
  tasks/discover-granules/tests/index.js
Labels: PR feedback
