Repository nasa/cumulus, pull requests merged in 2019-06, with the labels that each got.

#1034 Remove per-version notes. change upgrade docs to reference release
  docs/upgrade/1.11.0.md
  docs/upgrade/1.6.0.md
  docs/upgrade/1.7.0.md
  docs/upgrade/1.9.0.md
  docs/upgrade/README.md
  website/sidebars.json
Labels: PR feedback

#1035 Cumulus 1158
  bamboo/abort-if-not-publish.sh
  bamboo/bootstrap-integration-tests.sh
  bamboo/bootstrap-publish.sh
  bamboo/deploy-to-github-pages.sh
  bamboo/deploy-to-npm.sh
  bamboo/integration-tests.sh
  bamboo/lint.sh
  bamboo/npm-tag.js
  bamboo/set-bamboo-env-variables.sh
Labels: PR feedback

#1042 feat(audit): Update audit-ci to v2.0.1 and re-enable audit-ci in the …
  .travis.yml
  package.json
Labels: PR feedback

#1044 Remove jobs task
  packages/api/config/lambdas.yml
  packages/api/es/indexer.js
  packages/api/lambdas/jobs.js
  packages/api/package.json
  packages/api/tests/endpoints/providers/create-provider.js
  packages/api/tests/endpoints/test-distribution-metrics.js
  packages/api/tests/lambdas/test-bootstrap.js
  packages/api/tests/lambdas/test-sf-semaphore-down.js
  packages/api/tests/lambdas/test-sf-starter.js
  packages/api/tests/models/test-files-model.js
  packages/api/tests/serial/es/test-db-indexer.js
  packages/api/tests/serial/es/test-es-indexer.js
  packages/api/webpack.config.js
  packages/deployment/app/config.yml
  packages/deployment/test/fixtures/config.json
  packages/deployment/test/test_kes.js
  packages/ingest/aws.js
Labels: PR feedback

#956 Cumulus 1159 -- feature branch
  bamboo/abort-if-not-pr-or-master.sh
  bamboo/abort-if-not-pr-or-redeployment.sh
  bamboo/abort-if-not-publish.sh
  bamboo/abort-if-skip-integration-tests.sh
  bamboo/audit.sh
  bamboo/bootstrap-integration-tests.sh
  bamboo/bootstrap-lint-audit.sh
  bamboo/bootstrap-publish.sh
  bamboo/bootstrap-sftp.sh
  bamboo/bootstrap-unit-tests.sh
  bamboo/cleanup-integration-tests.sh
  bamboo/cleanup-unit-tests.sh
  bamboo/deploy-to-github-pages.sh
  bamboo/deploy-to-npm.sh
  bamboo/detect-pr.js
  bamboo/docker-compose.yml
  bamboo/elasticsearch.config
  bamboo/httpd.conf
  bamboo/integration-tests.sh
  bamboo/lint.sh
  bamboo/npm-tag.js
  bamboo/redeploy-integration-tests.sh
  bamboo/select-stack.js
  bamboo/set-bamboo-env-variables.sh
  bamboo/set-status.sh
  bamboo/unit-test-install-dependencies.sh
  bamboo/unit-tests.sh
  example/app/config.yml
  example/package.json
  example/scripts/tests-parallel.sh
  example/spec/helpers/reporters/junitReporter.js
  package.json
Labels: in review

#1024 Cumulus 796: Submit Cumulus distribution logs to EMS
  CHANGELOG.md
  docs/deployment/config_descriptions.md
  docs/deployment/server_access_logging.md
  docs/ems_reporting.md
  example/app/config.yml
  example/data/ems/20190530_CUMULUS_DataFileManifest.xls
  example/spec/parallel/emsReport/IngestGranule.MOD14A1_006.input.payload.json
  example/spec/parallel/emsReport/emsIngestDistributionReportSpec.js
  packages/api/config/lambdas.yml
  packages/api/lambdas/ems-distribution-report.js
  packages/api/lambdas/ems-ingest-report.js
  packages/api/lib/ems.js
  packages/api/models/files.js
  packages/api/tests/endpoints/providers/list-providers.js
  packages/api/tests/lambdas/ems-distribution-report.js
  packages/api/tests/lambdas/ems-ingest-report.js
  packages/api/tests/lambdas/fixtures/ems-distribution-report/s3-server-access-1.log
  packages/api/tests/lambdas/fixtures/ems-distribution-report/s3-server-access-2.log
  packages/api/tests/models/test-files-model.js
  packages/deployment/app/config.yml
  packages/test-data/granules/BROWSE.MOD14A1.A2000049.h00v10.006.2015041132152.1.jpg
Labels: PR feedback

#1049 Cumulus-1273: Cumulus Product Metadata Flat File
  CHANGELOG.md
  docs/ems_reporting.md
  example/data/collections/ems/A2_SI25_NRT_0.json
  example/data/collections/ems/MUR-JPL-L4-GLOB-v4.1_1.json
  example/data/collections/ems/MYDTEST_099.json
  example/data/ems/20190610_CUMULUS_DataFileManifest.xls
  example/spec/parallel/emsReport/emsProductMetadataReportSpec.js
  packages/api/config/lambdas.yml
  packages/api/lambdas/ems-metadata-report.js
  packages/api/models/collections.js
  packages/api/tests/endpoints/providers/list-providers.js
  packages/api/tests/lambdas/ems-metadata-report.js
  packages/api/tests/lambdas/fixtures/ems-metadata-report/A2_SI25_NRT___0.json
  packages/api/tests/lambdas/fixtures/ems-metadata-report/MOD11A1___006.json
  packages/api/tests/lambdas/fixtures/ems-metadata-report/MUR-JPL-L4-GLOB-v4.1___1.json
  packages/api/tests/lambdas/fixtures/ems-metadata-report/MYD13Q1___006.json
  packages/api/webpack.config.js
  packages/cmr-client/searchConcept.js
  packages/deployment/app/config.yml
Labels: needs review

#1062 CUMULUS-812: Add integration tests for executions started from queues with a maximum
  example/spec/parallel/startSF/startSfSpec.js
  packages/api/tests/lambdas/test-sf-scheduler.js
  packages/common/test-utils.js
  packages/ingest/consumer.js
  packages/ingest/test/test-queue.js
  tasks/queue-granules/tests/index.js
  tasks/queue-pdrs/tests/index.js
Labels: PR feedback

#1067 Update eslint import version, update failing lint due to new rules
  package.json
  tasks/discover-pdrs/tests/force.js
  tasks/discover-pdrs/tests/index.js
Labels: needs review

#1071 CUMULUS-1321 Create DAAC deployment docs for Thin Egress
  docs/deployment/README.md
  docs/deployment/components.md
  docs/deployment/thin-egress-app.md
  package.json
  website/i18n/en.json
  website/sidebars.json
Labels: PR feedback

#1068 Cumulus 1226 - Index from database
  CHANGELOG.md
  packages/api/config/backend_api_lambdas.yml
  packages/api/config/lambdas.yml
  packages/api/ecs/async-operation/Dockerfile
  packages/api/ecs/async-operation/README.md
  packages/api/ecs/async-operation/index.js
  packages/api/endpoints/elasticsearch.js
  packages/api/es/indexer.js
  packages/api/es/search.js
  packages/api/lambdas/index-from-database.js
  packages/api/lib/errors.js
  packages/api/lib/testUtils.js
  packages/api/tests/lambdas/test-index-from-database.js
  packages/api/tests/serial/endpoints/test-elasticsearch.js
  packages/api/tests/serial/es/test-es-indexer.js
  packages/api/webpack.config.js
  packages/deployment/app/cloudformation.template.yml
  packages/deployment/app/config.yml
  packages/deployment/app/cumulus_api.template.yml
  packages/deployment/iam/cloudformation.template.yml
Labels: needs review

#1055 Cumulus 800 add api gateway logging
  .gitignore
  CHANGELOG.md
  bamboo/set-bamboo-env-variables.sh
  docs/additional-deployment-options/additional_lambda_logging.md
  docs/additional-deployment-options/configure_cloudwatch_logs_delivery.md
  docs/additional-deployment-options/delete_api_gateway_stages.md
  docs/additional-deployment-options/enable_api_logs.md
  docs/additional-deployment-options/enable_gateway_logging_permissions.md
  docs/assets/APIGateway-Delete-Stage.png
  example/app/config.yml
  packages/api/config/distribution_api_lambdas.yml
  packages/deployment/app/cloudformation.template.yml
  packages/deployment/app/config.yml
  packages/deployment/app/cumulus_api.template.yml
  packages/deployment/bin/README.md
  packages/deployment/bin/delete-stage-cli.js
  packages/deployment/iam/cloudformation.template.yml
  packages/deployment/lib/kes.js
  packages/deployment/package.json
  website/i18n/en.json
  website/sidebars.json
Labels: PR feedback
