Repository nasa/cumulus, pull requests merged in 2019-02, with the labels that each got.

#757 Changes to use the new NGAP VPC
  .travis.yml
  example/app/config.yml
  example/data/providers/ftp/ftp_provider.json
  example/data/providers/http/http_provider.json
  example/data/providers/https/https_provider.json
  example/fake-server.yml
  packages/api/endpoints/async-operations.js
  packages/api/models/async-operation.js
  packages/api/models/base.js
  packages/api/models/schemas.js
  packages/api/tests/data/granule_success.json
  packages/api/tests/models/test-async-operation-model.js
  packages/integration-tests/index.js
Labels: needs review

#788 Activate apache logs
  .travis.yml
  CHANGELOG.md
  packages/api/app/distribution.js
  packages/api/app/index.js
  packages/api/endpoints/workflows.js
  packages/api/package.json
Labels: in review

#780 CUMULUS-1103
  CHANGELOG.md
  example/spec/createReconciliationReport/CreateReconciliationReportSpec.js
  packages/api/config/lambdas.yml
  packages/api/lambdas/create-reconciliation-report.js
  packages/api/models/collections.js
  packages/api/tests/lambdas/create-reconciliation-report.js
  packages/cmrjs/cmr.js
  packages/cmrjs/index.js
  packages/cmrjs/tests/test-cmr.js
Labels: PR feedback

#793 Cumulus 678 UMM-G in Fake Processing Task
  CHANGELOG.md
  example/.gitignore
  example/package.json
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestUMMGSuccessSpec.js
  example/workflows/sips.yml
  packages/cmrjs/cmr-utils.js
  packages/integration-tests/cmr.js
  packages/integration-tests/index.js
  packages/integration-tests/package.json
  tasks/test-processing/index.js
Labels: PR feedback

#801 Cumulus 678 integration tests enabled
  example/app/config.yml
  example/data/collections/s3_MOD09GQ_006-umm/s3_MOD09GQ_006.json
  example/spec/parallel/ingestGranule/IngestGranule.UMM.output.payload.template.json
  example/spec/parallel/ingestGranule/IngestUMMGSuccessSpec.js
  packages/cmrjs/cmr-utils.js
  packages/cmrjs/cmr.js
  packages/cmrjs/tests/cmr-utils/test-constructonlineaccessurls.js
  packages/deployment/app/cumulus_api.template.yml
  tasks/post-to-cmr/README.md
Labels: PR feedback

#815 CUMULUS-1169 Retry throttled requests to the AWS StepFunctions API
  CHANGELOG.md
  example/spec/parallel/startSF/startSfSpec.js
  example/spec/standalone/redeployment/LambdaVersionOption.js
  packages/api/lib/utils.js
  packages/api/models/granules.js
  packages/common/StepFunctions.js
  packages/common/aws.js
  packages/common/step-functions.js
  packages/common/test-utils.js
  packages/common/tests/test-StepFunctions.js
  packages/common/tests/test-aws.js
  packages/ingest/aws.js
  packages/integration-tests/index.js
  packages/integration-tests/sfnStep.js
  tasks/pdr-status-check/index.js
Labels: PR feedback

#820 Release 1.11.2 - actual release
  .travis.yml
  CHANGELOG.md
  example/package.json
  lerna.json
  packages/api/package.json
  packages/cmrjs/package.json
  packages/common/package.json
  packages/deployment/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  packages/pvl/package.json
  packages/task-debug/package.json
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/hello-world/package.json
  tasks/move-granules/package.json
  tasks/parse-pdr/package.json
  tasks/pdr-status-check/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-granules/package.json
  tasks/queue-pdrs/package.json
  tasks/sf-sns-report/package.json
  tasks/sync-granule/package.json
  tasks/test-processing/package.json
  website/i18n/en.json
  website/versioned_docs/version-v1.11.2/README.md
  website/versioned_docs/version-v1.11.2/deployment/README.md
  website/versioned_docs/version-v1.11.2/deployment/config_descriptions.md
  website/versioned_docs/version-v1.11.2/deployment/obtain_cumulus_packages.md
  website/versioned_docs/version-v1.11.2/glossary.md
  website/versioned_docs/version-v1.11.2/operator-docs/lifecycle-policies.md
  website/versioned_docs/version-v1.11.2/operator-docs/update-cumulus-dependencies.md
  website/versioned_docs/version-v1.11.2/team.md
  website/versioned_docs/version-v1.11.2/workflows/README.md
  website/versioned_docs/version-v1.11.2/workflows/developing-workflow-tasks.md
  website/versioned_docs/version-v1.11.2/workflows/lambda.md
  website/versioned_sidebars/version-v1.11.2-sidebars.json
  website/versions.json
Labels: needs review

#808 CUMULUS-1139 final updates
  CHANGELOG.md
  example/spec/helpers/testUtils.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  packages/api/endpoints/granules.js
  packages/api/lib/FileUtils.js
  packages/api/lib/granuleUtils.js
  packages/api/lib/testUtils.js
  packages/api/models/files.js
  packages/api/models/granules.js
  packages/api/models/schemas.js
  packages/api/package.json
  packages/api/tests/data/granule_failed.json
  packages/api/tests/data/granule_success.json
  packages/api/tests/lib/FileUtils/test-buildFileSourceURL.js
  packages/api/tests/lib/FileUtils/test-filterDatabaseProperties.js
  packages/api/tests/lib/FileUtils/test-getChecksum.js
  packages/api/tests/lib/FileUtils/test-getFileName.js
  packages/api/tests/models/test-files-model.js
  packages/api/tests/models/test-granules-model.js
  packages/api/tests/serial/endpoints/test-granules.js
  packages/api/tests/serial/es/test-db-indexer.js
  packages/api/tests/serial/es/test-es-indexer.js
  packages/cmrjs/cmr-utils.js
  packages/cmrjs/tests/cmr-utils/test-constructonlineaccessurls.js
  packages/cmrjs/tests/cmr-utils/test-onlineaccessurlstoremove.js
  packages/common/StepFunctions.js
  packages/common/aws.js
  packages/common/docs/API.md
  packages/common/package.json
  packages/common/tests/test-aws.js
  packages/common/util.js
  packages/ingest/granule.js
  packages/ingest/test/test-granule.js
  tasks/post-to-cmr/index.js
  tasks/post-to-cmr/package.json
  tasks/post-to-cmr/schemas/input.json
  travis-ci/cleanup-integration-tests.sh
  travis-ci/init-integration-tests.sh
Labels: PR feedback

#833 Update PR template
  .github/pull_request_template.md
Labels: PR feedback

#832 Cumulus 666 remove prototype
  example/app/config.yml
  example/lambdas.yml
  example/spec/s3Access/s3AccessSpec.js
  packages/api/config/lambdas.yml
  packages/api/index.js
  packages/api/lambdas/in-region-s3-policy.js
  packages/api/tests/lambdas/test-in-region-s3-policy.js
Labels: PR feedback

#834 fix interfaces diagram for all versions
  docs/interfaces.md
Labels: PR feedback

#831 CUMULUS-1166 Add node README updates, change dashboard package installation to yarn
  docs/deployment/README.md
Labels: PR feedback

#827 Cumulus-1151: Compare the granule holdings in CMR with Cumulus' internal data store
  CHANGELOG.md
  example/package.json
  example/spec/createReconciliationReport/CreateReconciliationReportSpec.js
  example/spec/helpers/testUtils.js
  packages/api/config/tables.yml
  packages/api/lambdas/create-reconciliation-report.js
  packages/api/migrations/migration_2.js
  packages/api/models/base.js
  packages/api/models/files.js
  packages/api/models/granules.js
  packages/api/tests/lambdas/create-reconciliation-report.js
  packages/api/tests/models/test-granules-model.js
  packages/common/aws.js
  packages/common/tests/aws/DynamoDbSearchQueue.js
  packages/deployment/app/cloudformation.template.yml
  packages/integration-tests/cmr.js
  packages/integration-tests/index.js
Labels: in review

#824 CUMULUS-672: Add tests for downloading science files via CMR
  CHANGELOG.md
  example/package.json
  example/spec/distributionAPI/distributionSpec.js
  example/spec/helpers/apiUtils.js
  example/spec/helpers/testUtils.js
  example/spec/ingestGranule/IngestGranule.UMM.output.payload.template.json
  example/spec/ingestGranule/IngestUMMGSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestGranule.output.payload.template.json
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/testAPI/distributionSpec.js
  example/workflows/sips.yml
  packages/api/bin/serve.js
  packages/api/index.js
  packages/cmrjs/cmr-utils.js
  packages/common/file.js
  packages/integration-tests/api/EarthdataLogin.js
  packages/integration-tests/api/distribution.js
  packages/integration-tests/cmr.js
  packages/integration-tests/index.js
  packages/integration-tests/package.json
  tasks/post-to-cmr/index.js
  tasks/test-processing/index.js
Labels: PR feedback

#835 CUMULUS-1139 Translate granule files
  packages/api/models/granules.js
  packages/api/tests/models/test-granules-model.js
Labels: PR feedback

#838 [CUMULUS-668] Discover granule S3 Credential URLs through the CMR
  example/spec/ingestGranule/IngestUMMGSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  packages/cmrjs/cmr-utils.js
  packages/cmrjs/tests/cmr-utils/test-constructonlineaccessurls.js
Labels: PR feedback
