Repository nasa/cumulus, pull requests merged in 2020-08, with the labels that each got.

#1801 CUMULUS-2116: Fix granule bulk delete
  CHANGELOG.md
  packages/api/lambdas/bulk-operation.js
  packages/api/models/granules.js
  packages/api/tests/lambdas/test-bulk-operation.js
  packages/api/tests/models/granules/test-granule-delete.js
Labels: pr feedback

#1792 Move sqs-message-remover lambda out of API package
  bamboo/create-release.sh
  lambdas/sqs-message-remover/main.tf
  lambdas/sqs-message-remover/outputs.tf
  lambdas/sqs-message-remover/package.json
  lambdas/sqs-message-remover/src/index.js
  lambdas/sqs-message-remover/tests/test-index.js
  lambdas/sqs-message-remover/variables.tf
  lambdas/sqs-message-remover/webpack.config.js
  lerna.json
  packages/api/webpack.config.js
  tf-modules/ingest/lambda-functions.tf
  tf-modules/ingest/outputs.tf
  tf-modules/ingest/sqs-message-remover.tf
Labels: needs review

#1813 Fixes for rec reports integration tests
  packages/api/es/esScrollSearch.js
  packages/api/lambdas/create-reconciliation-report.js
Labels: needs review

#1819 Release 2.0.2
  CHANGELOG.md
  DATA_MODEL_CHANGELOG.md
  example/lambdas/asyncOperations/package.json
  example/lambdas/python-processing/package.json
  example/lambdas/python-reference-activity/package.json
  example/lambdas/python-reference-task/package.json
  example/lambdas/s3AccessTest/package.json
  example/lambdas/snsS3Test/package.json
  example/lambdas/versionUpTest/package.json
  example/package.json
  lerna.json
  packages/api-client/package.json
  packages/api/package.json
  packages/aws-client/package.json
  packages/checksum/package.json
  packages/cmr-client/package.json
  packages/cmrjs/package.json
  packages/collection-config-store/package.json
  packages/common/package.json
  packages/earthdata-login-client/package.json
  packages/errors/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  packages/launchpad-auth/package.json
  packages/logger/package.json
  packages/message/package.json
  packages/pvl/package.json
  packages/s3-credentials-endpoint/package.json
  packages/sftp-client/package.json
  packages/tea-map-cache/package.json
  packages/test-data/package.json
  packages/tf-inventory/package.json
  packages/types/package.json
  tasks/add-missing-file-checksums/package.json
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/files-to-granules/package.json
  tasks/hello-world/package.json
  tasks/hyrax-metadata-updates/package.json
  tasks/move-granules/package.json
  tasks/parse-pdr/package.json
  tasks/pdr-status-check/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-granules/package.json
  tasks/queue-pdrs/package.json
  tasks/sf-sns-report/package.json
  tasks/sf-sqs-report/package.json
  tasks/sync-granule/package.json
  tasks/test-processing/package.json
  tf-modules/s3-replicator/package.json
  website/versioned_docs/version-v2.0.2/data-cookbooks/browse-generation.md
  website/versioned_docs/version-v2.0.2/data-cookbooks/choice-states.md
  website/versioned_docs/version-v2.0.2/data-cookbooks/ingest-notifications.md
  website/versioned_docs/version-v2.0.2/data-cookbooks/run-tasks-in-lambda-or-docker.md
  website/versioned_docs/version-v2.0.2/data-cookbooks/throttling-queued-executions.md
  website/versions.json
Labels: current sprint, pr feedback

#1833 Fix master
  bamboo/docker-compose-local.yml
  example/lambdas/db-provision-user-database/src/index.ts
  lambdas/db-migration/src/index.ts
Labels: current sprint

#1832 Cumulus 2123 -- Move DB connection logic to @cumulus/db
  CHANGELOG.md
  example/cumulus-tf/main.tf
  example/db-migration-tf/main.tf
  example/db-migration-tf/variables.tf
  example/lambdas/db-provision-user-database/main.tf
  example/lambdas/db-provision-user-database/package.json
  example/lambdas/db-provision-user-database/src/index.ts
  example/lambdas/db-provision-user-database/tests/index.js
  example/lambdas/db-provision-user-database/webpack.config.js
  lambdas/db-migration/main.tf
  lambdas/db-migration/package.json
  lambdas/db-migration/package.sh
  lambdas/db-migration/src/index.ts
  lambdas/db-migration/variables.tf
  lambdas/db-migration/webpack.config.js
  packages/db/package.json
  packages/db/src/config.ts
  packages/db/src/connection.ts
  packages/db/src/index.ts
  packages/db/tests/config.js
  packages/db/tests/connection.js
  tf-modules/archive/api.tf
  tf-modules/archive/variables.tf
  tf-modules/cumulus/archive.tf
  tf-modules/cumulus/variables.tf
  tf-modules/data-persistence/main.tf
Labels: current sprint

#1827 Fix SyncGranule checksum memory issue
  CHANGELOG.md
  example/fake-provider-cf.yml
  example/spec/parallel/SyncGranuleTask/ChecksumOneGigFileSpec.js
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  packages/aws-client/src/S3.ts
Labels: current sprint
