Repository nasa/cumulus, pull requests merged in 2020-09, with the labels that each got.

#1842 Integration test debugging and fixes
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/testAPI/createOneTimeRuleSpec.js
  packages/api-client/src/collections.ts
  packages/api-client/tests/test-collections.js
Labels: fix test failure, pr feedback

#1834 CUMULUS-2112: Internal Reconciliation Report
  CHANGELOG.md
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  packages/api/endpoints/reconciliation-reports.js
  packages/api/es/esSearchQueue.js
  packages/api/lambdas/create-reconciliation-report.js
  packages/api/lambdas/internal-reconciliation-report.js
  packages/api/lib/reconciliationReport.js
  packages/api/lib/testUtils.js
  packages/api/models/collections.js
  packages/api/models/granules.js
  packages/api/models/schemas.js
  packages/api/package.json
  packages/api/tests/endpoints/test-reconciliation-reports.js
  packages/api/tests/lambdas/test-create-reconciliation-report-internals.js
  packages/api/tests/lambdas/test-create-reconciliation-report.js
  packages/api/tests/lambdas/test-internal-reconciliation-report.js
  packages/api/tests/lib/test-reconciliationReport.js
  packages/api/tests/models/granules/test-granules-model.js
  packages/api/tests/models/test-collections-model.js
  packages/aws-client/src/DynamoDbSearchQueue.ts
Labels: pr feedback

#1844 Backport changes from https://github.com/nasa/cumulus/pull/1827
  CHANGELOG.md
  bamboo/bootstrap-tf-deployment.sh
  example/fake-provider-cf.yml
  example/spec/parallel/SyncGranuleTask/ChecksumOneGigFileSpec.js
  packages/aws-client/src/S3.ts
Labels: current sprint, needs review

#1845 Backport fixes from https://github.com/nasa/cumulus/pull/1821
  CHANGELOG.md
  packages/api/es/aggregations.js
  packages/api/es/collections.js
  packages/api/tests/es/test-collections.js
  packages/api/tests/es/test-stats.js
Labels: current sprint

#1847 Release-2.0.3
  CHANGELOG.md
  example/lambdas/asyncOperations/package.json
  example/lambdas/python-processing/package.json
  example/lambdas/python-reference-activity/package.json
  example/lambdas/python-reference-task/package.json
  example/lambdas/s3AccessTest/package.json
  example/lambdas/snsS3Test/package.json
  example/lambdas/versionUpTest/package.json
  example/package.json
  lerna.json
  packages/api-client/package.json
  packages/api/package.json
  packages/aws-client/README.md
  packages/aws-client/package.json
  packages/checksum/package.json
  packages/cmr-client/package.json
  packages/cmrjs/package.json
  packages/collection-config-store/package.json
  packages/common/package.json
  packages/earthdata-login-client/package.json
  packages/errors/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  packages/launchpad-auth/package.json
  packages/logger/package.json
  packages/message/package.json
  packages/pvl/package.json
  packages/s3-credentials-endpoint/package.json
  packages/sftp-client/package.json
  packages/tea-map-cache/package.json
  packages/test-data/package.json
  packages/tf-inventory/package.json
  packages/types/package.json
  tasks/add-missing-file-checksums/package.json
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/files-to-granules/package.json
  tasks/hello-world/package.json
  tasks/hyrax-metadata-updates/package.json
  tasks/move-granules/package.json
  tasks/parse-pdr/package.json
  tasks/pdr-status-check/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-granules/package.json
  tasks/queue-pdrs/package.json
  tasks/sf-sns-report/package.json
  tasks/sf-sqs-report/package.json
  tasks/sync-granule/package.json
  tasks/test-processing/package.json
  tf-modules/s3-replicator/package.json
  website/versions.json
Labels: current sprint, needs review

#1849 Update user database provisioner to wipe/recreate database on run and run database schema migrations in CI
  bamboo/bootstrap-tf-deployment.sh
  example/db-migration-tf/main.tf
  example/lambdas/db-provision-user-database/src/index.ts
  example/lambdas/db-provision-user-database/tests/test-index.js
  lambdas/db-migration/outputs.tf
Labels: current sprint

#1822 Update collections to write to DB
  CHANGELOG.md
  bin/db-local-migrate.js
  example/db-migration-tf/main.tf
  example/lambdas/db-provision-user-database/src/index.ts
  example/lambdas/db-provision-user-database/tests/test-index.js
  lambdas/data-migration1/src/index.ts
  lambdas/db-migration/main.tf
  lambdas/db-migration/outputs.tf
  lambdas/db-migration/package.json
  lambdas/db-migration/src/index.ts
  packages/api/app/routes.js
  packages/api/endpoints/collections.js
  packages/api/package.json
  packages/api/tests/endpoints/collections/create-collection.js
  packages/api/tests/endpoints/collections/delete-collection.js
  packages/api/tests/endpoints/collections/update-collection.js
  packages/api/tests/endpoints/utils.js
  packages/api/webpack.config.js
  packages/common/src/test-utils.ts
  packages/db/src/config.ts
  packages/db/src/connection.ts
  packages/db/src/index.ts
  packages/db/tests/config.js
  packages/db/tests/connection.js
  tf-modules/archive/api.tf
  tf-modules/archive/iam.tf
Labels: current sprint

#1854 Release 2.0.4
  CHANGELOG.md
  example/lambdas/asyncOperations/package.json
  example/lambdas/python-processing/package.json
  example/lambdas/python-reference-activity/package.json
  example/lambdas/python-reference-task/package.json
  example/lambdas/s3AccessTest/package.json
  example/lambdas/snsS3Test/package.json
  example/lambdas/versionUpTest/package.json
  example/package.json
  lerna.json
  packages/api-client/package.json
  packages/api/package.json
  packages/aws-client/package.json
  packages/checksum/package.json
  packages/cmr-client/package.json
  packages/cmrjs/package.json
  packages/collection-config-store/package.json
  packages/common/package.json
  packages/earthdata-login-client/package.json
  packages/errors/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  packages/launchpad-auth/package.json
  packages/logger/package.json
  packages/message/package.json
  packages/pvl/package.json
  packages/s3-credentials-endpoint/package.json
  packages/sftp-client/package.json
  packages/tea-map-cache/package.json
  packages/test-data/package.json
  packages/tf-inventory/package.json
  packages/types/package.json
  tasks/add-missing-file-checksums/package.json
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/files-to-granules/package.json
  tasks/hello-world/package.json
  tasks/hyrax-metadata-updates/package.json
  tasks/move-granules/package.json
  tasks/parse-pdr/package.json
  tasks/pdr-status-check/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-granules/package.json
  tasks/queue-pdrs/package.json
  tasks/sf-sns-report/package.json
  tasks/sf-sqs-report/package.json
  tasks/sync-granule/package.json
  tasks/test-processing/package.json
  tf-modules/distribution/main.tf
  tf-modules/s3-replicator/package.json
  website/versions.json
Labels: in review

#1843 Add Files/Granules tables
  lambdas/data-migration1/tests/test-collections.js
  lambdas/db-migration/package.json
  lambdas/db-migration/src/index.ts
  lambdas/db-migration/src/migrations/20200813174231_create_collections_table.ts
  lambdas/db-migration/src/migrations/20200901060126_create_granules.ts
  lambdas/db-migration/src/migrations/20200901060127_create_files.ts
  packages/db/src/config.ts
Labels: current sprint

#1856 Mhs/cumulus 1965/allow array of collection ids on reconciliation report
  CHANGELOG.md
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  packages/api/lambdas/create-reconciliation-report.js
  packages/api/lambdas/internal-reconciliation-report.js
  packages/api/lib/reconciliationReport.js
  packages/api/tests/es/test-queries-package.js
  packages/api/tests/lambdas/test-create-reconciliation-report-internals.js
  packages/api/tests/lambdas/test-create-reconciliation-report.js
  packages/api/tests/lambdas/test-internal-reconciliation-report.js
  packages/api/tests/lib/test-reconciliationReport.js
Labels: in review

#1858 Update CI cleanup to *not* use bootstrap
  bamboo/cleanup-integration-tests.sh
  example/scripts/lock-stack.js
Labels: low priority

#1857 Cumulus 2155
  CHANGELOG.md
  example/cumulus-tf/main.tf
  example/cumulus-tf/terraform.tfvars.example
  example/cumulus-tf/variables.tf
  example/data-persistence-tf/main.tf
  example/data-persistence-tf/terraform.tfvars.example
  example/data-persistence-tf/variables.tf
  example/lambdas/db-provision-user-database/main.tf
  example/lambdas/db-provision-user-database/src/index.ts
  example/lambdas/db-provision-user-database/variables.tf
  lambdas/data-migration1/main.tf
  lambdas/data-migration1/variables.tf
  lambdas/db-migration/main.tf
  packages/db/package.json
  packages/db/src/config.ts
  packages/db/src/connection.ts
  packages/db/tests/config.js
  packages/db/tests/connection.js
  tf-modules/archive/api.tf
  tf-modules/archive/variables.tf
  tf-modules/cumulus/archive.tf
  tf-modules/cumulus/variables.tf
Labels: current sprint

#1855 Increase timeouts
  example/spec/parallel/discoverGranules/DiscoverGranulesDuplicateHandlingErrorSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesDuplicateHandlingSkipSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleWithDuplicateHandlingErrorSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleWithDuplicateHandlingVersionSpec.js
  example/spec/parallel/testAPI/createOneTimeRuleSpec.js
  example/spec/serial/DiscoverGranulesHttpSpec.js
  packages/integration-tests/Executions.js
Labels: fix test failure

#1861 Ignore NGAP tags on deployed resources
  example/cumulus-tf/main.tf
  packages/db/package.json
Labels: low priority

#1862 Make Lambda subnet config optional
  bamboo/bootstrap-tf-deployment.sh
  example/cumulus-tf/cnm_response_task.tf
  example/cumulus-tf/cnm_to_cma_task.tf
  example/cumulus-tf/lambdas.tf
  example/cumulus-tf/main.tf
  example/cumulus-tf/python-reference-task.tf
  example/cumulus-tf/terraform.tfvars.example
  example/cumulus-tf/variables.tf
Labels: low priority

#1840 CUMULUS-2107: UpdateCmrAccessConstraints Workflow & Tests
  CHANGELOG.md
  docs/assets/cd_operations_page.png
  docs/operator-docs/bulk-operations.md
  docs/operator-docs/cmr-operations.md
  example/cumulus-tf/update_cmr_access_constraints_workflow.asl.json
  example/cumulus-tf/update_cmr_access_constraints_workflow.tf
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  packages/api-client/src/granules.ts
  packages/api-client/tests/test-granules.js
  packages/api/endpoints/granules.js
  packages/api/lambdas/bulk-operation.js
  packages/api/models/granules.js
  tasks/update-cmr-access-constraints/index.js
  tasks/update-cmr-access-constraints/package.json
  tasks/update-cmr-access-constraints/tests/fixtures/MOD09GQ.A2016358.h13v04.006.2016360104606.cmr.xml
  tf-modules/cumulus/outputs.tf
  tf-modules/ingest/outputs.tf
  tf-modules/ingest/update-cmr-access-constraints.tf
  website/sidebars.json
Labels: in review, pr feedback

#1872 Move event validation from lambda to endpoint.
  CHANGELOG.md
  packages/api/endpoints/reconciliation-reports.js
  packages/api/lambdas/create-reconciliation-report.js
  packages/api/lib/RecordDoesNotExist.js
  packages/api/lib/reconciliationReport/normalizeEvent.js
  packages/api/tests/endpoints/test-reconciliation-reports.js
  packages/api/tests/lambdas/test-create-reconciliation-report-internals.js
  packages/api/tests/lambdas/test-create-reconciliation-report.js
  packages/api/tests/lib/reconciliationReport/test-normalizeEvent.js
Labels: needs review

#1863 CUMULUS-2111: Deploy TEA separately
  CHANGELOG.md
  bamboo/bootstrap-tf-deployment.sh
  docs/deployment/thin-egress-app.md
  docs/tasks.md
  docs/upgrade-notes/migrate-tea-standalone.md
  example/cumulus-tf/main.tf
  example/cumulus-tf/outputs.tf
  example/cumulus-tf/thin-egress-app/bucket_map.yaml.tmpl
  example/data-persistence-tf/main.tf
  example/db-migration-tf/variables.tf
  example/deployments/cumulus/mboyd-int-tf.tfvars
  example/deployments/db-migration/bt-ci-tf.tfvars
  example/deployments/db-migration/chuckulus-ci-tf.tfvars
  example/deployments/db-migration/cumulus-from-npm-tf.tfvars
  example/deployments/db-migration/cumulus-from-pr-tf.tfvars
  example/deployments/db-migration/cumulus-nightly-tf.tfvars
  example/deployments/db-migration/cumulus-sit.tfvars
  example/deployments/db-migration/cumulus-source-tf.tfvars
  example/deployments/db-migration/jc-tf.tfvars
  example/deployments/db-migration/jk-tf.tfvars
  example/deployments/db-migration/jk-tf3.tfvars
  example/deployments/db-migration/jk-tf4.tfvars
  example/deployments/db-migration/jl-tf.tfvars
  example/deployments/db-migration/kk-int-tf.tfvars
  example/deployments/db-migration/lf-test-tf.tfvars
  example/deployments/db-migration/mboyd-int-tf.tfvars
  example/deployments/db-migration/mhs-tf.tfvars
  example/deployments/db-migration/mth-ci-tf.tfvars
  example/deployments/db-migration/mvd-tf.tfvars
  example/deployments/db-migration/sandbox.tfvars
  example/deployments/db-migration/sit.tfvars
  tf-modules/cumulus/README.md
  tf-modules/cumulus/archive.tf
  tf-modules/cumulus/distribution.tf
  tf-modules/cumulus/ingest.tf
  tf-modules/cumulus/outputs.tf
  tf-modules/cumulus/variables.tf
  tf-modules/distribution/README.md
  tf-modules/distribution/main.tf
  tf-modules/distribution/outputs.tf
  tf-modules/distribution/variables.tf
  website/sidebars.json
Labels: current sprint

#1875 Update @cumulus/integration-tests/Collection to throw on failed addCollection
  packages/integration-tests/Collections.js
  packages/integration-tests/tests/test-Collections.js
Labels: low priority

#1841 Fix SIT CI env variables
  bamboo/set-bamboo-env-variables.sh
  example/config.yml
  tf-modules/cumulus-rds-tf/main.tf
Labels: current sprint

#1880 Cumulus-1962 Adding location params for rec reports
  CHANGELOG.md
  example/config.yml
  packages/api/lambdas/create-reconciliation-report.js
  packages/api/lib/reconciliationReport.js
  packages/api/tests/lambdas/test-create-reconciliation-report.js
Labels: needs review

#1879 CUMULUS-2157: Dynamo providers migration
  CHANGELOG.md
  example/data-migration1-tf/README.md
  example/data-migration1-tf/main.tf
  example/data-migration1-tf/terraform.tfvars.example
  example/data-migration1-tf/variables.tf
  example/db-migration-tf/main.tf
  lambdas/data-migration1/main.tf
  lambdas/data-migration1/package.json
  lambdas/data-migration1/src/collections.ts
  lambdas/data-migration1/src/errors.ts
  lambdas/data-migration1/src/index.ts
  lambdas/data-migration1/src/providers.ts
  lambdas/data-migration1/src/types.ts
  lambdas/data-migration1/tests/test-collections.js
  lambdas/data-migration1/tests/test-providers.js
  lambdas/data-migration1/variables.tf
  lambdas/db-migration/package.json
  lambdas/db-migration/src/index.ts
  lambdas/db-migration/src/migrations/20200911162949_create_collections_table.ts
  lambdas/db-migration/src/migrations/20200911163145_create_providers_table.ts
  lambdas/db-migration/src/migrations/20200911163153_create_granules_table.ts
  lambdas/db-migration/src/migrations/20200911163156_create_files_table.ts
  packages/api/lambdas/providerSecretsMigration.js
  packages/api/lambdas/verifyProviderSecretsMigration.js
  packages/api/tests/lambdas/test-providerSecretsMigration.js
  packages/api/tests/lambdas/test-verifyProviderSecretsMigration.js
  packages/api/webpack.config.js
  tf-modules/archive/provider_credentials_encryption.tf
Labels: current sprint

#1836 Cumulus 2145 docs
  docs/additional-deployment-options/cmr_launchpad_authentication.md
  docs/additional-deployment-options/cumulus_api_launchpad_authentication.md
  docs/additional-deployment-options/cumulus_saml_launchpad_integration.md
  docs/configuration/cloudwatch-retention.md
  docs/configuration/collection-storage-best-practices.md
  docs/configuration/lifecycle-policies.md
  docs/configuration/monitoring.md
  docs/configuration/server_access_logging.md
  docs/deployment/README.md
  docs/deployment/api_gateway_logging.md
  docs/deployment/configure_cloudwatch_logs_delivery.md
  docs/deployment/share-s3-access-logs.md
  docs/features/replay-kinesis-messages.md
  docs/getting-started.md
  docs/team.md
  docs/troubleshooting/rerunning-workflow-executions.md
  website/sidebars.json
  website/siteConfig.js
Labels: pr feedback

#1883 CUMULUS-2168 Update collection stats query
  CHANGELOG.md
  packages/api/es/collections.js
Labels: current sprint, pr feedback

#1884 Backport #1883 -- CUMULUS-2168
  CHANGELOG.md
  packages/api/es/collections.js
Labels: current sprint

#1888 Release 2.0.6
  CHANGELOG.md
  example/lambdas/asyncOperations/package.json
  example/lambdas/python-processing/package.json
  example/lambdas/python-reference-activity/package.json
  example/lambdas/python-reference-task/package.json
  example/lambdas/s3AccessTest/package.json
  example/lambdas/snsS3Test/package.json
  example/lambdas/versionUpTest/package.json
  example/package.json
  lerna.json
  packages/api-client/package.json
  packages/api/package.json
  packages/aws-client/package.json
  packages/checksum/package.json
  packages/cmr-client/API.md
  packages/cmr-client/package.json
  packages/cmrjs/package.json
  packages/collection-config-store/package.json
  packages/common/package.json
  packages/earthdata-login-client/package.json
  packages/errors/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  packages/launchpad-auth/package.json
  packages/logger/package.json
  packages/message/package.json
  packages/pvl/package.json
  packages/s3-credentials-endpoint/package.json
  packages/sftp-client/package.json
  packages/tea-map-cache/package.json
  packages/test-data/package.json
  packages/tf-inventory/package.json
  packages/types/package.json
  tasks/add-missing-file-checksums/package.json
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/files-to-granules/package.json
  tasks/hello-world/package.json
  tasks/hyrax-metadata-updates/package.json
  tasks/move-granules/package.json
  tasks/parse-pdr/package.json
  tasks/pdr-status-check/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-granules/package.json
  tasks/queue-pdrs/package.json
  tasks/sf-sns-report/package.json
  tasks/sf-sqs-report/package.json
  tasks/sync-granule/package.json
  tasks/test-processing/package.json
  tf-modules/s3-replicator/package.json
  website/versions.json
Labels: current sprint, needs review

#1891 Update knex versoning (to fix CI TS errors)
  lambdas/data-migration1/package.json
  packages/db/package.json
Labels: current sprint

#1892 CUMULUS-2181: update bamboo script for RDS feature branch
  bamboo/set-bamboo-env-variables.sh
Labels: current sprint
