Repository nasa/cumulus, pull requests merged in 2020-05, with the labels that each got.

#1597 Add release 1.22.1 updates
  CHANGELOG.md
  DATA_MODEL_CHANGELOG.md
  bamboo/deploy-to-npm.sh
  docs/development/release.md
  example/lambdas/asyncOperations/package.json
  example/lambdas/python-processing/package.json
  example/lambdas/python-reference-activity/package.json
  example/lambdas/python-reference-task/package.json
  example/lambdas/s3AccessTest/package.json
  example/lambdas/snsS3Test/package.json
  example/lambdas/versionUpTest/package.json
  example/package.json
  lerna.json
  packages/api-client/package.json
  packages/api/package.json
  packages/aws-client/package.json
  packages/checksum/package.json
  packages/cmr-client/package.json
  packages/cmrjs/package.json
  packages/collection-config-store/package.json
  packages/common/package.json
  packages/errors/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  packages/launchpad-auth/package.json
  packages/logger/package.json
  packages/message/package.json
  packages/pvl/package.json
  packages/sftp-client/package.json
  packages/test-data/package.json
  packages/tf-inventory/package.json
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/files-to-granules/package.json
  tasks/hello-world/package.json
  tasks/hyrax-metadata-updates/package.json
  tasks/move-granules/package.json
  tasks/parse-pdr/package.json
  tasks/pdr-status-check/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-granules/package.json
  tasks/queue-pdrs/package.json
  tasks/sf-sns-report/package.json
  tasks/sf-sqs-report/package.json
  tasks/sync-granule/package.json
  tasks/test-processing/package.json
  tf-modules/distribution/package.json
  tf-modules/s3-replicator/package.json
  website/versioned_docs/version-v1.22.0/data-cookbooks/cnm-workflow.md
  website/versioned_docs/version-v1.22.0/data-cookbooks/setup.md
  website/versioned_docs/version-v1.22.0/features/distribution-metrics.md
  website/versioned_docs/version-v1.22.0/features/logging-esdis-metrics.md
  website/versioned_docs/version-v1.22.0/glossary.md
  website/versioned_docs/version-v1.22.0/operator-docs/serve-dashboard-from-cloudfront.md
  website/versioned_docs/version-v1.22.0/tasks.md
  website/versioned_docs/version-v1.22.0/troubleshooting/troubleshoot_deployment.md
  website/versioned_docs/version-v1.22.0/workflow_tasks/discover_granules.md
  website/versioned_sidebars/version-v1.22.0-sidebars.json
  website/versions.json
Labels: needs review

#1621 CUMULUS-1911:Add Reconciliation Reports to Elasticsearch
  CHANGELOG.md
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  packages/api/endpoints/elasticsearch.js
  packages/api/es/indexer.js
  packages/api/lambdas/create-reconciliation-report.js
  packages/api/lambdas/db-indexer.js
  packages/api/lambdas/executeMigrations.js
  packages/api/lambdas/index-from-database.js
  packages/api/lib/testUtils.js
  packages/api/migrations/migration_5.js
  packages/api/models/index.js
  packages/api/models/mappings.json
  packages/api/models/reconciliation-reports.js
  packages/api/models/schemas.js
  packages/api/tests/lambdas/create-reconciliation-report.js
  packages/api/tests/lambdas/test-index-from-database.js
  packages/api/tests/migrations/migration_5.js
  packages/api/tests/models/test-reconciliation-reports-model.js
  tf-modules/archive/db_indexer.tf
  tf-modules/archive/execute_migrations.tf
  tf-modules/archive/reconciliation_report.tf
  tf-modules/data-persistence/dynamo.tf
  tf-modules/data-persistence/outputs.tf
Labels: PR feedback

#1630 Update MoveGranules to use multipart copies
  CHANGELOG.md
  example/cumulus-tf/iam.tf
  example/fake-provider-cf.yml
  example/spec/helpers/Providers.js
  example/spec/helpers/kinesisHelpers.js
  example/spec/parallel/ingestGranule/IngestElevenGiBFileSpec.js
  example/spec/parallel/moveGranules/MoveGranulesTagsSpec.js
  packages/aws-client/README.md
  packages/aws-client/src/S3.ts
  packages/aws-client/tests/S3/test-moveObject.js
  packages/ingest/granule.js
  packages/integration-tests/Collections.js
  tasks/move-granules/index.js
  tasks/move-granules/tests/test-index.js
Labels: PR feedback

#1640 CUMULUS-1912: Update Reconciliation Report API Endpoints
  CHANGELOG.md
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  packages/api-client/index.js
  packages/api-client/reconciliationReports.js
  packages/api/endpoints/reconciliation-reports.js
  packages/api/lambdas/create-reconciliation-report.js
  packages/api/tests/endpoints/test-reconciliation-reports.js
  tf-modules/archive/api.tf
Labels: PR feedback

#1662 Disable unreliable EMS ingest dist report test
  example/spec/parallel/emsReport/emsIngestDistributionReportSpec.js
  example/spec/parallel/testAPI/createOneTimeRuleSpec.js
  example/spec/parallel/testAPI/ruleSpec.js
  packages/api/tests/endpoints/test-rules.js
Labels: needs review

#1667 Make the GranuleFetcher.ingest function a little easier to read
  tasks/sync-granule/GranuleFetcher.js
Labels: low priority

#1646 Update discover_and_queue_pdrs workflow to use meta.provider_path
  example/cumulus-tf/discover_and_queue_pdrs_workflow.tf
  example/spec/parallel/ingest/ingestFromPdrSpec.js
Labels: current sprint

#1670 Remove "provider_path" from "collection"
  CHANGELOG.md
  DATA_MODEL_CHANGELOG.md
  docs/data-cookbooks/browse-generation.md
  docs/data-cookbooks/setup.md
  docs/data-cookbooks/sips-workflow.md
  docs/operator-docs/discovery-filtering.md
  example/data/collections/L2_HR_PIXC-000/L2_HR_PIXC-000.json
  example/data/collections/ems/A2_RainOcn_NRT_0.json
  example/data/collections/ems/A2_SI25_NRT_0.json
  example/data/collections/ems/MUR-JPL-L4-GLOB-v4.1_1.json
  example/data/collections/ems/MYDTEST_099.json
  example/data/collections/http_testcollection_001/http_testcollection_001.json
  example/data/collections/http_testcollection_002/http_testcollection_002.json
  example/data/collections/https_testcollection_001/https_testcollection_001.json
  example/data/collections/s3_MOD09GQ_006-umm/s3_MOD09GQ_006.json
  example/data/collections/s3_MOD09GQ_006/s3_MOD09GQ_006.json
  example/data/collections/s3_MOD09GQ_006_no_cmr/s3_MOD09GQ_006.json
  example/data/collections/s3_MOD14A1_006/s3_MOD14A1_006.json
  example/data/collections/s3_MYD13Q1_006/s3_MYD13Q1_006.json
  example/spec/parallel/discoverGranules/DiscoverGranulesS3FailureSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleWithDuplicateHandlingErrorSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleWithDuplicateHandlingVersionSpec.js
  example/spec/parallel/syncGranule/SyncGranuleCopyTagsSpec.js
  packages/api-client/collections.js
  packages/api/lib/testUtils.js
  packages/api/models/collections.js
  packages/api/models/schemas.js
  packages/api/tests/data/collections_post.json
  packages/api/tests/data/granule_failed.json
  packages/api/tests/data/granule_success.json
  packages/api/tests/data/pdr_failure.json
  packages/api/tests/data/pdr_success.json
  packages/api/tests/endpoints/collections/update-collection.js
  packages/api/tests/models/test-collections-model.js
  packages/test-data/cumulus_messages/discover-pdrs.json
  packages/test-data/cumulus_messages/discover-s3-granules.json
  packages/test-data/cumulus_messages/parse-pdr.json
  packages/test-data/cumulus_messages/pdr-status-check.json
  packages/test-data/cumulus_messages/post-to-cmr.json
  packages/test-data/cumulus_messages/sync-granule.json
  packages/test-data/payloads/amsr2/discover.json
  packages/test-data/payloads/modis/cmr.json
  packages/test-data/payloads/modis/discover.json
  packages/test-data/payloads/modis/ingest-checksumfile.json
  packages/test-data/payloads/modis/ingest.json
  packages/test-data/payloads/modis/parse.json
  packages/test-data/payloads/mur/discover.json
  packages/test-data/payloads/new-message-schema/cmr.json
  packages/test-data/payloads/new-message-schema/discover.json
  packages/test-data/payloads/new-message-schema/ingest-checksumfile.json
  packages/test-data/payloads/new-message-schema/ingest-multigran.json
  packages/test-data/payloads/new-message-schema/ingest.json
  packages/test-data/payloads/new-message-schema/parse.json
  tasks/discover-granules/tests/fixtures/mur.json
  tasks/discover-pdrs/tests/fixtures/input.json
  tasks/hyrax-metadata-updates/tests/data/payload-json-broken.json
  tasks/hyrax-metadata-updates/tests/data/payload-json.json
  tasks/hyrax-metadata-updates/tests/data/payload-xml.json
  tasks/move-granules/tests/data/payload.json
Labels: current sprint
