Repository nasa/cumulus, pull requests merged in 2020-06, with the labels that each got.

#1635 Cumulus 1997
  CHANGELOG.md
  example/cumulus-tf/ingest_and_publish_granule_workflow.tf
  example/deployments/cumulus/lf-test-tf.tfvars
  packages/api/lambdas/bootstrap.js
  packages/api/lambdas/create-reconciliation-report.js
  packages/api/lambdas/ems-metadata-report.js
  packages/api/models/granules.js
  packages/api/tests/lambdas/create-reconciliation-report.js
  packages/api/tests/lambdas/ems-metadata-report.js
  packages/cmr-client/CMR.js
  packages/cmr-client/CMRSearchConceptQueue.js
  packages/cmr-client/searchConcept.js
  packages/cmr-client/tests/test-CMRSearchConceptQueue.js
  packages/cmrjs/cmr-utils.js
  packages/cmrjs/tests/cmr-utils/test-cmr-utils.js
  tasks/hyrax-metadata-updates/index.js
  tasks/hyrax-metadata-updates/schemas/config.json
  tasks/post-to-cmr/index.js
  tf-modules/archive/ems_reporting.tf
  tf-modules/archive/outputs.tf
  tf-modules/archive/reconciliation_report.tf
  tf-modules/ingest/hyrax-metadata-updates-task.tf
Labels: current sprint

#1679 Release v1.24.0
  CHANGELOG.md
  DATA_MODEL_CHANGELOG.md
  example/package.json
  lerna.json
  packages/api-client/package.json
  packages/api/package.json
  packages/aws-client/package.json
  packages/checksum/package.json
  packages/cmr-client/API.md
  packages/cmr-client/package.json
  packages/cmrjs/package.json
  packages/collection-config-store/package.json
  packages/common/package.json
  packages/errors/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  packages/launchpad-auth/package.json
  packages/logger/package.json
  packages/message/package.json
  packages/pvl/package.json
  packages/sftp-client/package.json
  packages/test-data/package.json
  packages/tf-inventory/package.json
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/files-to-granules/package.json
  tasks/hello-world/package.json
  tasks/hyrax-metadata-updates/package.json
  tasks/move-granules/package.json
  tasks/parse-pdr/package.json
  tasks/pdr-status-check/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-granules/package.json
  tasks/queue-pdrs/package.json
  tasks/sf-sns-report/package.json
  tasks/sf-sqs-report/package.json
  tasks/sync-granule/package.json
  tasks/test-processing/package.json
  tf-modules/distribution/package.json
  tf-modules/s3-replicator/package.json
  website/versioned_docs/version-v1.24.0/additional-deployment-options/share-s3-access-logs.md
  website/versioned_docs/version-v1.24.0/data-cookbooks/browse-generation.md
  website/versioned_docs/version-v1.24.0/data-cookbooks/run-tasks-in-lambda-or-docker.md
  website/versioned_docs/version-v1.24.0/data-cookbooks/setup.md
  website/versioned_docs/version-v1.24.0/data-cookbooks/sips-workflow.md
  website/versioned_docs/version-v1.24.0/operator-docs/discovery-filtering.md
  website/versioned_docs/version-v1.24.0/workflows/workflow-configuration-how-to.md
  website/versions.json
Labels: needs review

#1676 Remove deprecated code from common
  CHANGELOG.md
  packages/api/es/collections.js
  packages/api/tests/lambdas/test-sf-semaphore-down.js
  packages/api/tests/lambdas/test-sf-starter.js
  packages/common/DynamoDb.js
  packages/common/LaunchpadToken.js
  packages/common/Semaphore.js
  packages/common/aws.js
  packages/common/bucketsConfigJsonObject.js
  packages/common/cloud-watch-logger.js
  packages/common/collection-config-store.js
  packages/common/concurrency.js
  packages/common/config.js
  packages/common/field-pattern.js
  packages/common/index.js
  packages/common/launchpad.js
  packages/common/message.js
  packages/common/string.js
  packages/common/tests/collection-config-store.js
  packages/common/tests/test-LaunchpadToken.js
  packages/common/tests/test-Semaphore.js
  packages/common/tests/test-bucketsConfigJsonObject.js
  packages/common/tests/test-message.js
  packages/common/tests/test-workflows.js
  packages/common/workflows.js
  tasks/parse-pdr/tests/test-parse-pdr.js
Labels: low priority

#1675 Enable unicorn/no-null eslint rule as a warning
  .eslintrc.js
Labels: low priority

#1674 Enable the unicorn/prefer-number-properties eslint rule
  .eslintrc.js
  example/spec/parallel/startSF/startSfSpec.js
  example/spec/parallel/testAPI/sqsRuleSpec.js
  packages/api/bin/cli.js
  packages/api/endpoints/stats.js
  packages/api/es/search.js
  packages/api/lambdas/cleanExecutions.js
  packages/api/lambdas/db-indexer.js
  packages/api/lambdas/ems-ingest-report.js
  packages/api/lambdas/index-from-database.js
  packages/api/lambdas/sqs-message-consumer.js
  packages/api/lib/DistributionEvent.js
  packages/api/lib/testUtils.js
  packages/api/models/rules.js
  packages/ingest/FtpProviderClient.js
  tasks/sync-granule/tests/sync_granule_test.js
Labels: low priority

#1673 Enable unicorn/no-zero-fractions eslint rule
  .eslintrc.js
  example/spec/helpers/reporters/suiteTimeReporter.js
Labels: low priority

#1669 RuleSpec intermittent test fail fix
  example/spec/parallel/testAPI/ruleSpec.js
  packages/api-client/rules.js
  packages/integration-tests/Executions.js
Labels: current sprint, fix test failure, pr feedback

#1690 Make provider.globalConnectionLimit optional
  CHANGELOG.md
  DATA_MODEL_CHANGELOG.md
  docs/data-cookbooks/setup.md
  packages/api/models/providers.js
  packages/api/models/schemas.js
  packages/api/tests/endpoints/providers/update-provider.js
  packages/api/tests/models/test-providers-model.js
  packages/aws-client/src/client.ts
  packages/ingest/lock.js
  packages/ingest/test/test-lock.js
  packages/integration-tests/README.md
Labels: current sprint

#1672 Enable unicorn/explicit-length-check eslint rule
  .eslintrc.js
  packages/api/lambdas/ems-ingest-report.js
Labels: low priority

#1699 Knock 30s off EMS distribution tests
  packages/api/lib/DistributionEvent.js
Labels: low priority

#1693 Make eslint unicorn/catch-error-name a warning
  .eslintrc.js
Labels: low priority

#1680 Add support for EDL Token authentication to the /s3credentials endpoint
  CHANGELOG.md
  packages/api/lib/EarthdataLogin.js
  packages/api/lib/errors.js
  packages/api/tests/lib/test-EarthdataLogin.js
  tf-modules/distribution/index.js
  tf-modules/distribution/package.json
  tf-modules/distribution/tests/test-handler-with-edl-token.js
Labels: current sprint

#1706 Jump to TS implementation
  tsconfig.json
Labels: low priority

#1705 CUMULUS-2019: add infix search to es query builder
  CHANGELOG.md
  packages/api/es/queries.js
  packages/api/package.json
  packages/api/tests/es/test-queries.js
Labels: current sprint

#1708 Deprecate @cumulus/common/util.sleep()
  .eslintignore
  CHANGELOG.md
  example/spec/helpers/kinesisHelpers.js
  example/spec/parallel/kinesisTests/KinesisReplaySpec.js
  example/spec/parallel/kinesisTests/KinesisTestErrorSpec.js
  example/spec/parallel/testAPI/sqsRuleSpec.js
  packages/api/tests/lambdas/test-sqs-message-consumer.js
  packages/api/tests/lambdas/test-sqs-message-remover.js
  packages/common/util.js
  packages/ingest/lock.js
  packages/ingest/package.json
  packages/ingest/test/test-consumer.js
  packages/integration-tests/cmr.js
  packages/integration-tests/index.js
  packages/integration-tests/package.json
Labels: low priority

#1697 Updates cmr-js 'constructOnlineAccessUrls' to respect TEA
  .eslintrc.js
  CHANGELOG.md
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  example/spec/parallel/moveGranules/MoveGranulesTagsSpec.js
  packages/api/lambdas/create-reconciliation-report.js
  packages/api/models/granules.js
  packages/api/tests/endpoints/test-granules.js
  packages/api/tests/lambdas/create-reconciliation-report.js
  packages/cmrjs/cmr-utils.js
  packages/cmrjs/tests/cmr-utils/test-cmr-utils.js
  packages/cmrjs/tests/cmr-utils/test-constructurls.js
  packages/cmrjs/tests/cmr-utils/test-reconcilecmrmetadata.js
  packages/common/stack.js
  packages/errors/src/index.ts
  packages/tea-map-cache/index.js
  packages/tea-map-cache/package.json
  packages/tea-map-cache/tea.js
  packages/tea-map-cache/tests/test-tea.js
  tasks/move-granules/index.js
  tasks/move-granules/tests/test-index.js
Labels: current sprint, needs review

#1719 Update LICENSE
  LICENSE
Labels: current sprint, needs review

#1698 Update thin-egress-app documentatation re: CUMULUS-1958
  docs/deployment/thin-egress-app.md
Labels: current sprint, needs review

#1692 Enable the eslint unicorn/better-regex rule
  .eslintrc.js
  example/spec/parallel/ingestGranule/IngestUMMGSuccessSpec.js
  example/spec/parallel/testAPI/bulkDeleteFailureSpec.js
  example/spec/parallel/testAPI/bulkDeleteSuccessSpec.js
  packages/api/lambdas/db-indexer.js
  packages/api/lambdas/ems-metadata-report.js
  packages/api/models/rules.js
  packages/aws-client/src/StepFunctions.ts
  packages/ingest/HttpProviderClient.js
  packages/ingest/url-path-template.js
  packages/pvl/lib/patterns.js
  packages/pvl/t.js
  tasks/post-to-cmr/tests/cmr-test.js
Labels: low priority

#1716 Deprecate the collection-config-store package
  CHANGELOG.md
  packages/collection-config-store/index.js
  packages/collection-config-store/package.json
Labels: low priority

#1709 Migrate common/log to TS
  CHANGELOG.md
  packages/api/endpoints/logs.js
  packages/api/es/indexer.js
  packages/api/es/logUtils.js
  packages/common/.gitignore
  packages/common/package.json
  packages/common/src/log.ts
  packages/common/tsconfig.json
Labels: low priority

#1700 Update get object size
  CHANGELOG.md
  packages/api/lib/FileUtils.js
  packages/api/lib/granules.js
  packages/api/models/granules.js
  packages/api/tests/lib/FileUtils/test-getChecksum.js
  packages/api/tests/lib/FileUtils/test-getFileName.js
  packages/api/tests/lib/FileUtils/test-setS3FileSize.js
  packages/api/tests/models/granules/test-granule-generateGranuleRecord.js
  packages/aws-client/README.md
  packages/aws-client/src/S3.ts
  packages/aws-client/tests/test-S3.js
  packages/logger/src/index.ts
  tasks/sync-granule/GranuleFetcher.js
Labels: low priority

#1696 Add promises extension to eslint
  .eslintrc.js
  example/spec/parallel/startSF/startSfSpec.js
  package.json
  packages/api/bin/Importer.js
  packages/api/endpoints/elasticsearch.js
  packages/api/package.json
  packages/api/tests/lambdas/create-reconciliation-report.js
  packages/api/tests/lambdas/ems-metadata-report.js
  packages/api/tests/lambdas/test-publish-collections.js
  packages/ingest/granule.js
  packages/ingest/test/test-granule.js
  tasks/sync-granule/tests/sync_granule_test.js
Labels: low priority

#1683 Move earthdata login client to its own package
  .eslintrc.js
  CHANGELOG.md
  package.json
  packages/api/endpoints/distribution.js
  packages/api/endpoints/token.js
  packages/api/lib/EarthdataLogin.js
  packages/api/lib/GoogleOAuth2.js
  packages/api/lib/OAuth2.js
  packages/api/lib/OAuth2AuthenticationError.js
  packages/api/lib/OAuth2AuthenticationFailure.js
  packages/api/package.json
  packages/api/tests/endpoints/test-distribution.js
  packages/api/tests/endpoints/test-token.js
  packages/api/tests/lib/OAuth2.js
  packages/api/tests/lib/test-EarthdataLogin.js
  packages/earthdata-login-client/.npmignore
  packages/earthdata-login-client/README.md
  packages/earthdata-login-client/package.json
  packages/earthdata-login-client/src/EarthdataLoginClient.ts
  packages/earthdata-login-client/src/EarthdataLoginError.ts
  packages/earthdata-login-client/src/index.ts
  packages/earthdata-login-client/templates/README.md.hbs
  packages/earthdata-login-client/tests/test-EarthdataLoginClient.ts
  packages/earthdata-login-client/tsconfig.json
  packages/integration-tests/api/EarthdataLogin.js
  packages/integration-tests/package.json
  tf-modules/distribution/index.js
  tf-modules/distribution/package.json
  tf-modules/distribution/tests/test-index.js
Labels: current sprint

#1695 Document Terraform best practices
  docs/deployment/README.md
  docs/deployment/terraform-best-practices.md
  docs/troubleshooting/troubleshoot_deployment.md
  example/README.md
  website/sidebars.json
Labels: current sprint

#1701 Cumulus 2011 - Put rec reports in an async operation
  CHANGELOG.md
  DATA_MODEL_CHANGELOG.md
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  example/spec/serial/AsyncOperationRunnerFailingLambdaSpec.js
  example/spec/serial/AsyncOperationRunnerNonExistentLambdaSpec.js
  example/spec/serial/AsyncOperationRunnerNonExistentPayloadSpec.js
  example/spec/serial/AsyncOperationRunnerNonJsonPayloadSpec.js
  example/spec/serial/AsyncOperationRunnerSuccessfulLambdaSpec.js
  packages/api-client/asyncOperations.js
  packages/api-client/index.js
  packages/api-client/tests/test-asyncOperations.js
  packages/api/endpoints/reconciliation-reports.js
  packages/api/lambdas/create-reconciliation-report.js
  packages/api/models/async-operation.js
  packages/api/models/schemas.js
  packages/api/tests/endpoints/test-reconciliation-reports.js
  packages/api/tests/lambdas/create-reconciliation-report.js
  packages/api/tests/models/test-async-operation-model.js
  packages/integration-tests/index.js
  tf-modules/archive/iam.tf
  tf-modules/cumulus/ecs_cluster.tf
Labels: current sprint

#1721 Create add-missing-file-checksums task
  .eslintrc.js
  CHANGELOG.md
  docs/tasks.md
  example/cumulus-tf/ingest_and_publish_granule_workflow.tf
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestUMMGSuccessSpec.js
  package.json
  packages/aws-client/package.json
  packages/aws-client/src/S3.ts
  packages/aws-client/tests/test-S3.js
  packages/logger/src/index.ts
  packages/logger/tests/test-buildMessage.js
  packages/sftp-client/index.js
  tasks/add-missing-file-checksums/.npmignore
  tasks/add-missing-file-checksums/README.md
  tasks/add-missing-file-checksums/bin/package.sh
  tasks/add-missing-file-checksums/package.json
  tasks/add-missing-file-checksums/schemas/config.json
  tasks/add-missing-file-checksums/schemas/input.json
  tasks/add-missing-file-checksums/schemas/output.json
  tasks/add-missing-file-checksums/src/index.ts
  tasks/add-missing-file-checksums/src/types.ts
  tasks/add-missing-file-checksums/tests/test-index.ts
  tasks/add-missing-file-checksums/tsconfig.json
  tasks/add-missing-file-checksums/webpack.config.js
  tf-modules/cumulus/outputs.tf
  tf-modules/ingest/add-missing-file-checksums.tf
  tf-modules/ingest/outputs.tf
Labels: current sprint

#1685 Move s3-credentials-endpoint to its own package
  CHANGELOG.md
  bamboo/create-release.sh
  packages/s3-credentials-endpoint/index.js
  packages/s3-credentials-endpoint/package.json
  packages/s3-credentials-endpoint/tests/test-handler-with-edl-token.js
  packages/s3-credentials-endpoint/tests/test-index.js
  packages/s3-credentials-endpoint/webpack.config.js
  tf-modules/distribution/.npmignore
  tf-modules/distribution/bin/build-tf-module.sh
  tf-modules/distribution/main.tf
Labels: current sprint

#1743 Update to use cumulus-ecs-task 1.7.0
  CHANGELOG.md
  docs/data-cookbooks/run-tasks-in-lambda-or-docker.md
  docs/workflows/developing-workflow-tasks.md
  example/cumulus-tf/ecs_hello_world_workflow.tf
  tf-modules/cumulus_ecs_service/README.md
Labels: needs review

#1741 Use client name in role session name
  CHANGELOG.md
  packages/s3-credentials-endpoint/index.js
  packages/s3-credentials-endpoint/tests/test-index.js
Labels: current sprint

#1722 CUMULUS-1861 Remove collection as required execution constraint
  CHANGELOG.md
  example/spec/parallel/ingest/ingestFromPdrSpec.js
  example/spec/parallel/testAPI/ruleSpec.js
  packages/api/lambdas/sf-event-sqs-to-db-records.js
  packages/api/models/errors.js
  packages/api/models/executions.js
  packages/api/models/granules.js
  packages/api/models/pdrs.js
  packages/api/models/schemas.js
  packages/api/tests/endpoints/test-rules.js
  packages/api/tests/lambdas/test-sf-event-sqs-to-db-records.js
  packages/integration-tests/Collections.js
  packages/integration-tests/index.js
  packages/integration-tests/utils.js
  packages/message/Collections.js
  packages/message/errors.js
  packages/message/tests/test-Collections.js
  tf-modules/archive/sf_event_sqs_to_db_records.tf
Labels: current sprint
