Repository nasa/cumulus, pull requests merged in 2020-07, with the labels that each got.

#1734 Build cmr-client with tsc
  .eslintignore
  packages/cmr-client/.gitignore
  packages/cmr-client/package.json
  packages/cmr-client/src/CMR.js
  packages/cmr-client/src/CMRSearchConceptQueue.js
  packages/cmr-client/src/UmmUtils.js
  packages/cmr-client/src/Utils.js
  packages/cmr-client/src/ValidationError.js
  packages/cmr-client/src/deleteConcept.js
  packages/cmr-client/src/getConcept.js
  packages/cmr-client/src/getUrl.js
  packages/cmr-client/src/index.js
  packages/cmr-client/src/ingestConcept.js
  packages/cmr-client/src/searchConcept.js
  packages/cmr-client/src/validate.js
  packages/cmr-client/tsconfig.json
Labels: pr feedback

#1735 Build cmrjs using tsc
  .eslintignore
  packages/cmrjs/.gitignore
  packages/cmrjs/package.json
  packages/cmrjs/src/cmr-utils.js
  packages/cmrjs/src/index.js
  packages/cmrjs/src/utils.js
  packages/cmrjs/tsconfig.json
Labels: pr feedback

#1747 Restore Team page
  docs/team.md
Labels: current sprint, needs review

#1733 Buld api-client with tsc
  .eslintignore
  packages/api-client/.gitignore
  packages/api-client/package.json
  packages/api-client/src/CumulusApiClientError.js
  packages/api-client/src/asyncOperations.js
  packages/api-client/src/collections.js
  packages/api-client/src/cumulusApiClient.js
  packages/api-client/src/ems.js
  packages/api-client/src/executions.js
  packages/api-client/src/granules.js
  packages/api-client/src/index.js
  packages/api-client/src/providers.js
  packages/api-client/src/reconciliationReports.js
  packages/api-client/src/rules.js
  packages/api-client/src/workflows.js
  packages/api-client/tsconfig.json
Labels: pr feedback

#1757 Fix aws-elasticsearch-connector issue
  packages/api/package.json
Labels: needs review

#1761 Do not run nyc in "npm test"
  example/package.json
  package.json
  packages/api-client/package.json
  packages/api/ecs/async-operation/package.json
  packages/api/package.json
  packages/aws-client/package.json
  packages/checksum/package.json
  packages/cmr-client/package.json
  packages/cmrjs/package.json
  packages/collection-config-store/package.json
  packages/common/package.json
  packages/earthdata-login-client/package.json
  packages/errors/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  packages/launchpad-auth/package.json
  packages/logger/package.json
  packages/message/package.json
  packages/pvl/package.json
  packages/s3-credentials-endpoint/package.json
  packages/sftp-client/package.json
  packages/tea-map-cache/package.json
  packages/test-data/package.json
  packages/tf-inventory/package.json
  tasks/add-missing-file-checksums/package.json
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/files-to-granules/package.json
  tasks/hello-world/package.json
  tasks/hyrax-metadata-updates/package.json
  tasks/move-granules/package.json
  tasks/parse-pdr/package.json
  tasks/pdr-status-check/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-granules/package.json
  tasks/queue-pdrs/package.json
  tasks/sf-sns-report/package.json
  tasks/sf-sqs-report/package.json
  tasks/sync-granule/package.json
  tasks/test-processing/package.json
  tf-modules/s3-replicator/package.json
Labels: needs review

#1759 Add processing role name to cumulus module outputs
  CHANGELOG.md
  tf-modules/cumulus/outputs.tf
Labels: low priority

#1756 Run python lambdas as part of unit tests
  bamboo/bootstrap-unit-tests.sh
  lerna.json
Labels: current sprint

#1766 Update CI scripts to not call python dependency install concurrently
  bamboo/bootstrap-lint-audit.sh
  bamboo/bootstrap-unit-tests.sh
  example/package.json
  package.json
Labels: needs review

#1767 Update python reference tasks to use updated CMA
  example/lambdas/python-processing/requirements.txt
  example/lambdas/python-reference-activity/requirements.txt
  example/lambdas/python-reference-task/requirements.txt
Labels: current sprint

#1755 Cumulus 2032
  CHANGELOG.md
  docs/data-cookbooks/setup.md
  packages/ingest/HttpProviderClient.js
  packages/ingest/package.json
  packages/ingest/test/test-HttpProviderClient.js
  tasks/discover-granules/index.js
  tasks/discover-granules/schemas/config.json
  tasks/discover-pdrs/README.md
  tasks/discover-pdrs/index.js
  tasks/discover-pdrs/schemas/config.json
Labels: current sprint

#1765 CUMULUS-1936: Migrate @cumulus/message to TS
  .eslintignore
  packages/message/.gitignore
  packages/message/README.md
  packages/message/docs/API.md
  packages/message/package.json
  packages/message/src/Build.ts
  packages/message/src/Collections.ts
  packages/message/src/Executions.ts
  packages/message/src/Granules.ts
  packages/message/src/Queue.ts
  packages/message/src/StepFunctions.ts
  packages/message/src/errors.ts
  packages/message/src/types.ts
  packages/message/templates/README.md.hbs
  packages/message/templates/docs-API.hbs
  packages/message/tests/test-Build.js
  packages/message/tests/test-StepFunctions.js
  packages/message/tsconfig.json
  packages/types/message.d.ts
  packages/types/package.json
Labels: pr feedback

#1780 Fix granules API client list querying
  CHANGELOG.md
  packages/api-client/src/executions.ts
  packages/api-client/src/granules.ts
  packages/api-client/tests/test-executions.js
  packages/api-client/tests/test-granules.js
Labels: fix test failure, pr feedback

#1737 cumulus-1961/replace dynamodb with ES in parts of reconciliation report creation
  .gitignore
  CHANGELOG.md
  example/spec/helpers/granuleUtils.js
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  packages/api/endpoints/reconciliation-reports.js
  packages/api/es/esCollectionGranuleQueue.js
  packages/api/es/esFileQueue.js
  packages/api/es/esScrollSearch.js
  packages/api/es/esSearchQueue.js
  packages/api/es/queries.js
  packages/api/es/search.js
  packages/api/lambdas/create-reconciliation-report.js
  packages/api/package.json
  packages/api/tests/endpoints/test-reconciliation-reports.js
  packages/api/tests/es/fixtures/granulesFileList.json
  packages/api/tests/es/helpers/helpers.js
  packages/api/tests/es/search.js
  packages/api/tests/es/test-esCollectionGranulesQueue.js
  packages/api/tests/es/test-esFileSearchQueue-buildFileResponse.js
  packages/api/tests/es/test-esFileSearchQueue.js
  packages/api/tests/es/test-esScrollSearch.js
  packages/api/tests/es/test-esSearchQueue.js
  packages/api/tests/lambdas/create-reconciliation-report.js
  tf-modules/archive/reconciliation_report.tf
Labels: in review, work in progress

#1773 CUMULUS-1934: Migrate @cumulus/launchpad-auth to TS
  .eslintignore
  packages/launchpad-auth/.gitignore
  packages/launchpad-auth/LaunchpadToken.js
  packages/launchpad-auth/README.md
  packages/launchpad-auth/docs/API.md
  packages/launchpad-auth/package.json
  packages/launchpad-auth/src/LaunchpadToken.ts
  packages/launchpad-auth/src/index.ts
  packages/launchpad-auth/src/types.ts
  packages/launchpad-auth/src/utils.ts
  packages/launchpad-auth/templates/README.md.hbs
  packages/launchpad-auth/templates/docs-API.hbs
  packages/launchpad-auth/tsconfig.json
Labels: pr feedback

#1783 CUMULUS-2100 Update tea-map-cache to typescript
  packages/tea-map-cache/nyc.config.js
  packages/tea-map-cache/package.json
  packages/tea-map-cache/src/index.ts
  packages/tea-map-cache/src/tea.ts
  packages/tea-map-cache/src/types.ts
  packages/tea-map-cache/tests/test-index.js
  packages/tea-map-cache/tests/test-tea.js
  packages/tea-map-cache/tsconfig.json
Labels: pr feedback

#1740 Cumulus 1902 ops docs
  CHANGELOG.md
  CONTRIBUTORS.md
  docs/assets/CD_run_bulk_modal.png
  docs/assets/cd_add_collection.png
  docs/assets/cd_add_collection_filled.png
  docs/assets/cd_add_collection_overview.png
  docs/assets/cd_add_rule.png
  docs/assets/cd_add_rule_filled.png
  docs/assets/cd_add_rule_form_blank.png
  docs/assets/cd_add_rule_overview.png
  docs/assets/cd_bulk_delete.png
  docs/assets/cd_collection.png
  docs/assets/cd_collections_page.png
  docs/assets/cd_executions_page.png
  docs/assets/cd_granules.png
  docs/assets/cd_granules_page.png
  docs/assets/cd_reingest_bulk.png
  docs/assets/cd_reingest_collection.png
  docs/assets/cd_reingest_granule_modal.png
  docs/assets/cd_reingest_modal_bulk.png
  docs/assets/cd_rules_page.png
  docs/assets/cd_run_bulk_granules.png
  docs/assets/cd_running_granules.png
  docs/assets/cd_workflow_json.png
  docs/assets/cd_workflow_page.png
  docs/assets/icon_note.svg
  docs/assets/icon_warning.svg
  docs/operator-docs/common-use-cases.md
  docs/operator-docs/create-rule-in-cumulus.md
  docs/operator-docs/granule-workflows.md
  docs/operator-docs/kinesis-stream-for-ingest.md
  docs/tasks.md
  example/spec/helpers/granuleUtils.js
  website/sidebars.json
  website/siteConfig.js
Labels: needs review

#1788 CUMULUS-1886: Add multiple sort keys support to api
  CHANGELOG.md
  packages/api/app/index.js
  packages/api/es/collections.js
  packages/api/es/queries.js
  packages/api/tests/es/test-queries.js
Labels: pr feedback

#1795 Migrate ingest/lock to TS
  CHANGELOG.md
  packages/ingest/src/lock.ts
  packages/ingest/test/test-lock.js
Labels: needs review

#1799 Temporarily whiteilst dot-prop from the dev dependencies
  audit-ci.json
Labels: current sprint
