Repository nasa/cumulus, pull requests merged in 2020-12, with the labels that each got.

#2000 [CUMULUS-2198] Write Dynamo to RDS Migration for Rules
  audit-ci.json
  lambdas/data-migration1/src/index.ts
  lambdas/data-migration1/src/rules.ts
  lambdas/data-migration1/tests/test-rules.js
  lambdas/db-migration/src/migrations/20201014105024_create_rules_table.ts
  packages/db/src/database.ts
  packages/db/src/index.ts
  packages/db/src/tables.ts
  packages/db/src/types.ts
Labels: pr feedback

#1963 [CUMULUS-2020] Update Elasticsearch mapping
  CHANGELOG.md
  packages/api/es/collections.js
  packages/api/es/esCollectionGranuleQueue.js
  packages/api/es/queries.js
  packages/api/es/stats.js
  packages/api/es/textFields.js
  packages/api/models/mappings.json
  packages/api/tests/data/testEsMappings.json
  packages/api/tests/data/testEsMappingsNoFields.json
  packages/api/tests/data/testEsMappingsSubset.json
  packages/api/tests/es/test-textFields.js
Labels: pr feedback

#2017 CUMULUS-2190: Write PDRs in parallel to Dynamo and RDS
  CHANGELOG.md
  example/lambdas/db-provision-user-database/package.json
  lambdas/data-migration1/package.json
  lambdas/db-migration/package.json
  lambdas/db-migration/src/migrations/20201014105054_create_pdrs_table.ts
  package.json
  packages/api/lambdas/sf-event-sqs-to-db-records/write-execution.js
  packages/api/lambdas/sf-event-sqs-to-db-records/write-pdr.js
  packages/api/models/executions.js
  packages/api/models/pdrs.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-write-pdr.js
  packages/api/tests/models/test-executions-model.js
  packages/api/tests/models/test-pdrs-model.js
  packages/db/package.json
  packages/db/src/database.ts
  packages/message/src/PDRs.ts
  packages/message/src/workflows.ts
  packages/message/tests/test-PDRs.js
  packages/message/tests/test-workflows.js
Labels: in review

#2020 CUMULUS-1 Merge master at aebdfc582 to feature-rds
  CHANGELOG.md
  docs/README.md
  docs/assets/granule_not_found_report.png
  docs/faqs.md
  docs/features/reports.md
  docs/getting-started.md
  docs/glossary.md
  docs/helpful-tips.md
  docs/tasks.md
  example/cumulus-tf/ingest_and_publish_granule_workflow.asl.json
  example/cumulus-tf/ingest_and_publish_granule_workflow.tf
  example/cumulus-tf/main.tf
  example/cumulus-tf/outputs.tf
  example/cumulus-tf/variables.tf
  example/data/collections/s3_MOD09GQ_006_full_ingest/s3_MOD09GQ_006.json
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/lzardsBackup/LzardsBackupSpec.js
  example/spec/parallel/lzardsBackup/test_data/testGranule.dat
  example/spec/parallel/lzardsBackup/test_data/testGranule.jpg
  package.json
  packages/api/es/collections.js
  packages/api/es/esCollectionGranuleQueue.js
  packages/api/es/queries.js
  packages/api/es/stats.js
  packages/api/es/textFields.js
  packages/api/models/mappings.json
  packages/api/models/schemas.js
  packages/api/tests/data/testEsMappings.json
  packages/api/tests/data/testEsMappingsNoFields.json
  packages/api/tests/data/testEsMappingsSubset.json
  packages/api/tests/es/test-textFields.js
  packages/aws-client/src/services.ts
  packages/launchpad-auth/src/index.ts
  packages/types/api/collections.d.ts
  tasks/discover-granules/index.js
  tasks/lzards-backup/.npmignore
  tasks/lzards-backup/README.md
  tasks/lzards-backup/bin/package.sh
  tasks/lzards-backup/nyc.config.js
  tasks/lzards-backup/package.json
  tasks/lzards-backup/schemas/input.json
  tasks/lzards-backup/schemas/output.json
  tasks/lzards-backup/src/aws4.d.ts
  tasks/lzards-backup/src/crypto-js.d.ts
  tasks/lzards-backup/src/errors.ts
  tasks/lzards-backup/src/index.ts
  tasks/lzards-backup/src/typeGuards.ts
  tasks/lzards-backup/src/types.ts
  tasks/lzards-backup/tests/test-index.js
  tasks/lzards-backup/tsconfig.json
  tasks/lzards-backup/webpack.config.js
  tasks/move-granules/schemas/output.json
  tf-modules/cumulus/ingest.tf
  tf-modules/cumulus/outputs.tf
  tf-modules/cumulus/variables.tf
  tf-modules/ingest/lzards-backup-task.tf
  tf-modules/ingest/main.tf
  tf-modules/ingest/outputs.tf
  tf-modules/ingest/variables.tf
  website/sidebars.json
Labels: pr feedback

#2028 Jk/cumulus 2318 update ci feature rds
  bamboo/bootstrap-tf-deployment.sh
  bamboo/set-bamboo-env-variables.sh
  example/cumulus-tf/ecs_hello_world_workflow.tf
  example/cumulus-tf/main.tf
  example/cumulus-tf/python_processing_workflow.tf
  example/cumulus-tf/python_reference_workflow.tf
  example/cumulus-tf/variables.tf
Labels: current sprint

#2031 Update terraform to use data resource for ECR URL
  bamboo/bootstrap-tf-deployment.sh
  bamboo/set-bamboo-env-variables.sh
  example/cumulus-tf/ecs_hello_world_workflow.tf
  example/cumulus-tf/main.tf
  example/cumulus-tf/python_processing_workflow.tf
  example/cumulus-tf/python_reference_workflow.tf
  example/cumulus-tf/variables.tf
Labels: current sprint
