Repository nasa/cumulus, pull requests merged in 2020-11, with the labels that each got.

#1978 [CUMULUS-2233] Fix s3credentials endpoint
  CHANGELOG.md
  package.json
  packages/s3-credentials-endpoint/index.js
  packages/s3-credentials-endpoint/tests/test-index.js
Labels: pr feedback

#1986 Add CHANGELOG entry for 2191, update task to use cumuluss project
  CHANGELOG.md
  tf-modules/archive/async_operation.tf
Labels: current sprint

#1984 CUMULUS-2257: update table and column names to snake_case
  CHANGELOG.md
  lambdas/data-migration1/package.json
  lambdas/data-migration1/src/collections.ts
  lambdas/data-migration1/src/providers.ts
  lambdas/data-migration1/tests/test-collections.js
  lambdas/data-migration1/tests/test-providers.js
  lambdas/db-migration/src/migrations/20201014104958_create_collections_table.ts
  lambdas/db-migration/src/migrations/20201014105016_create_providers_table.ts
  lambdas/db-migration/src/migrations/20201014105024_create_rules_table.ts
  lambdas/db-migration/src/migrations/20201014105030_create_async_operations_table.ts
  lambdas/db-migration/src/migrations/20201014105045_create_executions_table.ts
  lambdas/db-migration/src/migrations/20201014105054_create_pdrs_table.ts
  lambdas/db-migration/src/migrations/20201014105058_create_granules_table.ts
  lambdas/db-migration/src/migrations/20201014105102_create_files_table.ts
  package.json
  packages/api/ecs/async-operation/tests/test-index.js
  packages/api/endpoints/collections.js
  packages/api/lambdas/sf-event-sqs-to-db-records.js
  packages/api/tests/endpoints/collections/update-collection.js
  packages/api/tests/lambdas/test-sf-event-sqs-to-db-records.js
  packages/async-operations/package.json
  packages/async-operations/src/async_operations.ts
  packages/async-operations/tests/test-async_operations.js
  packages/db/package.json
  packages/db/src/async_operations.ts
  packages/db/src/collections.ts
  packages/db/src/index.ts
  packages/db/src/tables.ts
  packages/db/src/types.ts
  packages/db/tests/test-async-operations.js
  packages/db/tests/test-collections.js
  packages/types/api/async_operations.d.ts
  packages/types/api/collections.d.ts
  tf-modules/archive/async_operation.tf
Labels: current sprint

#1992 Cumulus 2189 - Add Postgres provider writes
  CHANGELOG.md
  example/spec/helpers/Providers.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestUMMGSuccessSpec.js
  lambdas/data-migration1/src/providers.ts
  lambdas/db-migration/src/migrations/20201014105016_create_providers_table.ts
  packages/api/endpoints/providers.js
  packages/api/lib/errors.js
  packages/api/tests/endpoints/providers/create-provider.js
  packages/api/tests/endpoints/providers/delete-provider.js
  packages/api/tests/endpoints/providers/update-provider.js
  packages/api/tests/lib/test-errors.js
  packages/aws-client/src/index.ts
  packages/db/package.json
  packages/db/src/config.ts
  packages/db/src/database.ts
  packages/db/src/declarations.d.ts
  packages/db/src/index.ts
  packages/db/src/provider.ts
  packages/db/src/tables.ts
  packages/db/src/test-utils.ts
  packages/db/src/types.ts
  packages/db/tests/test-connection.js
  packages/db/tests/test-providers.js
  packages/errors/src/index.ts
  packages/integration-tests/index.js
  packages/types/api/providers.d.ts
  packages/types/index.d.ts
  tasks/sync-granule/tests/sync_granule_test.js
Labels: current sprint

#2004 Add npauzenga to archive api users
  example/cumulus-tf/main.tf
Labels: needs review

#2006 CUMULUS-2198: getCumulusId refactor
  lambdas/data-migration1/src/rules.ts
  packages/db/src/database.ts
  packages/db/src/index.ts
  packages/db/src/tables.ts
  packages/db/src/types.ts
Labels: needs review
