Repository nasa/cumulus, pull requests merged in 2020-10, with the labels that each got.

#1903 Cumulus 1 cve 2020 7720 suggestion
  audit-ci.json
Labels: fix test failure, needs review

#1901 CUMULUS-2195: Fix Launchpad SAML redirect
  CHANGELOG.md
  example/cumulus-tf/variables.tf
  example/spec/helpers/granuleUtils.js
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  packages/api/bin/serve.js
  packages/api/endpoints/launchpadSaml.js
  packages/api/tests/endpoints/test-launchpadSaml.js
  tf-modules/archive/api.tf
Labels: current sprint

#1899 Migrate some ingest files to TypeScript
  packages/aws-client/src/S3.ts
  packages/aws-client/src/SQS.ts
  packages/aws-client/src/lib/S3MultipartUploads.ts
  packages/ingest/src/FtpProviderClient.js
  packages/ingest/src/HttpProviderClient.js
  packages/ingest/src/S3ProviderClient.ts
  packages/ingest/src/consumer.ts
  packages/ingest/src/emptyProviderConnectEndMixin.js
  packages/ingest/src/types.ts
  packages/ingest/test/test-consumer.js
Labels: :turkey:

#1885 Support an optional prefix for execution names
  CHANGELOG.md
  docs/operator-docs/naming-executions.md
  example/cumulus-tf/discover_and_queue_pdrs_with_execution_name_prefix_workflow.asl.json
  example/cumulus-tf/discover_and_queue_pdrs_with_execution_name_prefix_workflow.tf
  example/cumulus-tf/discover_granules_with_execution_name_prefix_workflow.asl.json
  example/cumulus-tf/discover_granules_with_execution_name_prefix_workflow.tf
  example/spec/parallel/discoverGranules/DiscoverGranulesWithExecutionNamePrefixSpec.js
  example/spec/parallel/ingest/ingestFromPdrWithExecutionNamePrefixSpec.js
  example/spec/parallel/kinesisTests/KinesisTestTriggerSpec.js
  example/spec/parallel/testAPI/ruleSpec.js
  example/spec/parallel/testAPI/snsRuleSpec.js
  example/spec/parallel/testAPI/sqsRuleSpec.js
  packages/api/lambdas/sf-scheduler.js
  packages/api/lib/rulesHelpers.js
  packages/api/models/rules.js
  packages/api/models/schemas.js
  packages/ingest/src/queue.js
  packages/ingest/test/test-queue.js
  packages/integration-tests/index.js
  packages/message/src/Build.ts
  packages/message/tests/test-Build.js
  tasks/queue-granules/index.js
  tasks/queue-granules/schemas/config.json
  tasks/queue-granules/tests/index.js
  tasks/queue-pdrs/index.js
  tasks/queue-pdrs/schemas/config.json
  tasks/queue-pdrs/tests/index.js
Labels: :turkey:, current sprint

#1910 Use random provider name node_name test
  example/spec/parallel/ingest/ingestPdrWithNodeNameSpec.js
Labels: :turkey:

#1911 Fix reconciliation reports cmr_oauth_provider in deployment
  CHANGELOG.md
  tf-modules/archive/reconciliation_report.tf
Labels: release-critical

#1913 Compact discover_and_queue_pdrs_with_execution_name_prefix_workflow
  example/cumulus-tf/discover_and_queue_pdrs_with_execution_name_prefix_workflow.tf
  example/spec/parallel/ingest/ingestFromPdrWithExecutionNamePrefixSpec.js
Labels: release-critical

#1896 [CUMULUS-2197] Make EMS deployment optional
  CHANGELOG.md
  example/cumulus-tf/main.tf
  example/cumulus-tf/variables.tf
  packages/api/endpoints/ems.js
  tf-modules/archive/api.tf
  tf-modules/archive/ems_reporting.tf
  tf-modules/archive/variables.tf
  tf-modules/cumulus/archive.tf
  tf-modules/cumulus/variables.tf
Labels: pr feedback, release-critical

#1914 CUMULUS-2201-2: update CreateReconciliationReportSpec to ingest granule xml to CMR
  CHANGELOG.md
  example/package.json
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
Labels: in review

#1915 Cumulus 2200 fix queries spaces
  CHANGELOG.md
  packages/api/es/queries.js
  packages/api/tests/es/test-queries.js
Labels: release-critical

#1917 Mhs/cumulus 2224/add extended metadata type to reconciliation report
  CHANGELOG.md
  packages/api/lambdas/create-reconciliation-report.js
  packages/api/tests/lambdas/test-create-reconciliation-report.js
Labels: blocked

#1912 CUMULUS-2108 followup: dashboard screenshots for CMR operation operator docs
  docs/assets/cd_execute_publish.png
  docs/assets/cd_execute_updateconstraints.png
  docs/operator-docs/bulk-operations.md
  docs/operator-docs/cmr-operations.md
Labels: pr feedback, release-critical

#1918 CUMULUS-2201-3: Reconciliation Report integration test failures
  example/spec/helpers/granuleUtils.js
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
Labels: needs review

#1919 Release 3.0.0
  CHANGELOG.md
  CONTRIBUTORS.md
  example/lambdas/asyncOperations/package.json
  example/lambdas/python-processing/package.json
  example/lambdas/python-reference-activity/package.json
  example/lambdas/python-reference-task/package.json
  example/lambdas/s3AccessTest/package.json
  example/lambdas/snsS3Test/package.json
  example/lambdas/versionUpTest/package.json
  example/package.json
  lambdas/sqs-message-remover/package.json
  lerna.json
  packages/api-client/package.json
  packages/api/package.json
  packages/aws-client/README.md
  packages/aws-client/package.json
  packages/checksum/package.json
  packages/cmr-client/API.md
  packages/cmr-client/package.json
  packages/cmrjs/package.json
  packages/collection-config-store/package.json
  packages/common/docs/API.md
  packages/common/package.json
  packages/earthdata-login-client/package.json
  packages/errors/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  packages/launchpad-auth/package.json
  packages/logger/package.json
  packages/message/README.md
  packages/message/package.json
  packages/pvl/package.json
  packages/s3-credentials-endpoint/package.json
  packages/sftp-client/package.json
  packages/tea-map-cache/package.json
  packages/test-data/package.json
  packages/tf-inventory/package.json
  packages/types/package.json
  tasks/add-missing-file-checksums/package.json
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/files-to-granules/package.json
  tasks/hello-world/package.json
  tasks/hyrax-metadata-updates/package.json
  tasks/move-granules/package.json
  tasks/parse-pdr/package.json
  tasks/pdr-status-check/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-granules/package.json
  tasks/queue-pdrs/package.json
  tasks/sf-sqs-report/package.json
  tasks/sync-granule/package.json
  tasks/test-processing/package.json
  tasks/update-cmr-access-constraints/package.json
  tf-modules/s3-replicator/package.json
  website/versions.json
Labels: current sprint

#1921 Cumulus 2081 - Integrator Onboarding Docs
  CHANGELOG.md
  docs/assets/cd_add_provider_form.png
  docs/assets/cd_collections_page.png
  docs/assets/cd_provider_page.png
  docs/helpful-tips.md
  docs/integrator-guide/about-int-guide.md
  docs/integrator-guide/create-cumulus-data-mgmt-types.md
  docs/integrator-guide/int-common-use-cases.md
  docs/integrator-guide/workflow-add-new-lambda.md
  docs/integrator-guide/workflow-ts-failed-step.md
  docs/operator-docs/about-operator-docs.md
  docs/operator-docs/ops-common-use-cases.md
  website/sidebars.json
Labels: in review

#1923 Release 3.0.x
  CHANGELOG.md
  CONTRIBUTORS.md
  example/lambdas/asyncOperations/package.json
  example/lambdas/python-processing/package.json
  example/lambdas/python-reference-activity/package.json
  example/lambdas/python-reference-task/package.json
  example/lambdas/s3AccessTest/package.json
  example/lambdas/snsS3Test/package.json
  example/lambdas/versionUpTest/package.json
  example/package.json
  lambdas/sqs-message-remover/package.json
  lerna.json
  packages/api-client/package.json
  packages/api/package.json
  packages/aws-client/README.md
  packages/aws-client/package.json
  packages/checksum/package.json
  packages/cmr-client/API.md
  packages/cmr-client/package.json
  packages/cmrjs/package.json
  packages/collection-config-store/package.json
  packages/common/docs/API.md
  packages/common/package.json
  packages/earthdata-login-client/package.json
  packages/errors/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  packages/launchpad-auth/package.json
  packages/logger/package.json
  packages/message/README.md
  packages/message/package.json
  packages/pvl/package.json
  packages/s3-credentials-endpoint/package.json
  packages/sftp-client/package.json
  packages/tea-map-cache/package.json
  packages/test-data/package.json
  packages/tf-inventory/package.json
  packages/types/package.json
  tasks/add-missing-file-checksums/package.json
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/files-to-granules/package.json
  tasks/hello-world/package.json
  tasks/hyrax-metadata-updates/package.json
  tasks/move-granules/package.json
  tasks/parse-pdr/package.json
  tasks/pdr-status-check/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-granules/package.json
  tasks/queue-pdrs/package.json
  tasks/sf-sqs-report/package.json
  tasks/sync-granule/package.json
  tasks/test-processing/package.json
  tasks/update-cmr-access-constraints/package.json
  tf-modules/s3-replicator/package.json
  website/versions.json
Labels: current sprint, high priority

#1924 Fix docs render
  website/package.json
Labels: high priority

#1926 Cumulus 2203 -- Release 2.0.8
  CHANGELOG.md
  example/lambdas/asyncOperations/package.json
  example/lambdas/python-processing/package.json
  example/lambdas/python-reference-activity/package.json
  example/lambdas/python-reference-task/package.json
  example/lambdas/s3AccessTest/package.json
  example/lambdas/snsS3Test/package.json
  example/lambdas/versionUpTest/package.json
  example/package.json
  lerna.json
  packages/api-client/package.json
  packages/api/package.json
  packages/aws-client/package.json
  packages/checksum/package.json
  packages/cmr-client/API.md
  packages/cmr-client/package.json
  packages/cmrjs/package.json
  packages/collection-config-store/package.json
  packages/common/package.json
  packages/earthdata-login-client/package.json
  packages/errors/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  packages/launchpad-auth/package.json
  packages/logger/package.json
  packages/message/package.json
  packages/pvl/package.json
  packages/s3-credentials-endpoint/package.json
  packages/sftp-client/package.json
  packages/tea-map-cache/package.json
  packages/test-data/package.json
  packages/tf-inventory/package.json
  packages/types/package.json
  tasks/add-missing-file-checksums/package.json
  tasks/add-missing-file-checksums/src/index.ts
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/files-to-granules/package.json
  tasks/hello-world/package.json
  tasks/hyrax-metadata-updates/package.json
  tasks/move-granules/package.json
  tasks/parse-pdr/package.json
  tasks/pdr-status-check/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-granules/package.json
  tasks/queue-pdrs/package.json
  tasks/sf-sns-report/package.json
  tasks/sf-sqs-report/package.json
  tasks/sync-granule/package.json
  tasks/test-processing/package.json
  tf-modules/s3-replicator/package.json
  website/versions.json
Labels: current sprint, high priority

#1897 Migrate the cmr-client package to TypeScript
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  package.json
  packages/api/lambdas/create-reconciliation-report.js
  packages/api/lambdas/ems-metadata-report.js
  packages/api/tests/endpoints/test-granules.js
  packages/api/tests/lambdas/ems-metadata-report.js
  packages/api/tests/lambdas/test-create-reconciliation-report.js
  packages/cmr-client/package.json
  packages/cmr-client/src/CMR.ts
  packages/cmr-client/src/CMRSearchConceptQueue.ts
  packages/cmr-client/src/UmmUtils.ts
  packages/cmr-client/src/Utils.js
  packages/cmr-client/src/Utils.ts
  packages/cmr-client/src/ValidationError.ts
  packages/cmr-client/src/deleteConcept.js
  packages/cmr-client/src/deleteConcept.ts
  packages/cmr-client/src/getConcept.ts
  packages/cmr-client/src/getUrl.js
  packages/cmr-client/src/getUrl.ts
  packages/cmr-client/src/index.js
  packages/cmr-client/src/index.ts
  packages/cmr-client/src/ingestConcept.ts
  packages/cmr-client/src/searchConcept.js
  packages/cmr-client/src/searchConcept.ts
  packages/cmr-client/src/types.ts
  packages/cmr-client/src/validate.ts
  packages/cmr-client/tests/test-CMR.js
  packages/cmr-client/tests/test-CMRSearchConceptQueue.js
  packages/cmr-client/tests/test-deleteConcept.js
  packages/cmr-client/tests/test-getUrl.js
  packages/cmr-client/tests/test-ingestConcept.js
  packages/cmr-client/tests/test-searchConcept.js
  packages/cmrjs/src/cmr-utils.js
  packages/cmrjs/src/index.js
  packages/cmrjs/src/utils.js
  packages/cmrjs/tests/cmr-utils/test-reconcilecmrmetadata.js
  packages/integration-tests/cmr.js
  packages/integration-tests/package.json
Labels: :turkey:

#1928 Mhs/cumulus 2063/private mmt links
  CHANGELOG.md
  packages/api/endpoints/collections.js
  packages/api/lib/mmt.js
  packages/api/tests/lib/test-mmt.js
  packages/api/tests/lib/test-reconciliationReport.js
  packages/cmrjs/src/index.js
Labels: needs review

#1905 Migrate FtpProviderClient to TS
  packages/ingest/src/FtpProviderClient.ts
  packages/ingest/src/jsftp.d.ts
  packages/ingest/src/recursion.ts
  packages/ingest/src/types.ts
Labels: :turkey:

#1941 Updating package versions to remediate high vulnerabilities [SNYK]
  CHANGELOG.md
  lambdas/sqs-message-remover/package.json
  package.json
  packages/api/ecs/async-operation/package.json
  packages/api/package.json
  packages/aws-client/package.json
  packages/cmr-client/package.json
  packages/cmrjs/package.json
  packages/common/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  packages/launchpad-auth/package.json
  packages/message/package.json
  packages/pvl/package.json
  packages/sftp-client/package.json
  packages/tf-inventory/package.json
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/files-to-granules/package.json
  tasks/hyrax-metadata-updates/package.json
  tasks/move-granules/package.json
  tasks/parse-pdr/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-pdrs/package.json
  tasks/sf-sqs-report/package.json
  tasks/sync-granule/package.json
Labels: needs review

#1931 Update Core to use cumulus-message-adapter-js 2.0.0
  CHANGELOG.md
  tasks/add-missing-file-checksums/package.json
  tasks/add-missing-file-checksums/src/index.ts
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/files-to-granules/package.json
  tasks/hello-world/package.json
  tasks/hyrax-metadata-updates/package.json
  tasks/move-granules/package.json
  tasks/parse-pdr/package.json
  tasks/pdr-status-check/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-granules/package.json
  tasks/queue-pdrs/package.json
  tasks/sf-sqs-report/package.json
  tasks/sync-granule/package.json
  tasks/test-processing/package.json
  tasks/update-cmr-access-constraints/package.json
Labels: current sprint

#1948 Cumulus-2232 Updating rewire
  tasks/hyrax-metadata-updates/package.json
Labels: needs review

#1916 CI speed improvement: cache compiled TS code
  bamboo/Dockerfile-ci
  bamboo/bootstrap-integration-tests.sh
  bamboo/bootstrap-lint-audit.sh
  bamboo/bootstrap-publish.sh
  bamboo/bootstrap-unit-tests.sh
  bamboo/deploy-dev-integration-test-stack.sh
  bamboo/extract-ts-build-cache.sh
  bamboo/generate-ts-build-cache.sh
  bamboo/lint.sh
  bamboo/set-bamboo-env-variables.sh
  package.json
  packages/api-client/package.json
  packages/aws-client/package.json
  packages/checksum/package.json
  packages/cmr-client/package.json
  packages/cmrjs/package.json
  packages/common/package.json
  packages/earthdata-login-client/package.json
  packages/errors/package.json
  packages/ingest/package.json
  packages/launchpad-auth/package.json
  packages/logger/package.json
  packages/message/package.json
  packages/sftp-client/package.json
  packages/tea-map-cache/package.json
  packages/test-data/package.json
  tasks/add-missing-file-checksums/bin/package.sh
  tasks/add-missing-file-checksums/package.json
Labels: in review, pr feedback

#1951 Merge CI config updates to 3.0.x release branch
  bamboo/Dockerfile-ci
  bamboo/bootstrap-integration-tests.sh
  bamboo/bootstrap-lint-audit.sh
  bamboo/bootstrap-publish.sh
  bamboo/bootstrap-unit-tests.sh
  bamboo/deploy-dev-integration-test-stack.sh
  bamboo/extract-ts-build-cache.sh
  bamboo/generate-ts-build-cache.sh
  bamboo/lint.sh
  bamboo/set-bamboo-env-variables.sh
  package.json
  packages/api-client/package.json
  packages/aws-client/package.json
  packages/checksum/package.json
  packages/cmr-client/package.json
  packages/cmrjs/package.json
  packages/common/package.json
  packages/earthdata-login-client/package.json
  packages/errors/package.json
  packages/ingest/package.json
  packages/launchpad-auth/package.json
  packages/logger/package.json
  packages/message/package.json
  packages/sftp-client/package.json
  packages/tea-map-cache/package.json
  packages/test-data/package.json
  tasks/add-missing-file-checksums/bin/package.sh
  tasks/add-missing-file-checksums/package.json
Labels: needs review

#1947 CUMULUS-2211:Add bulkReingest endpoint
  CHANGELOG.md
  example/spec/helpers/granuleUtils.js
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  packages/api-client/src/granules.ts
  packages/api/endpoints/granules.js
  packages/api/lambdas/bulk-operation.js
  packages/api/models/granules.js
  packages/api/models/schemas.js
  packages/api/tests/endpoints/granules/test-bulk-reingest.js
  packages/api/tests/lambdas/test-bulk-operation.js
  tf-modules/cumulus/ecs_cluster.tf
Labels: in review

#1945 CUMULUS-2239 - Add new aws_vpc_endpoint resource for deploying outside of NGAP
  CHANGELOG.md
  tf-modules/cumulus/distribution.tf
  tf-modules/cumulus/variables.tf
  tf-modules/distribution/main.tf
  tf-modules/distribution/variables.tf
  tf-modules/tea-map-cache/main.tf
  tf-modules/tea-map-cache/variables.tf
Labels: pr feedback

#1906 Upgrade the got package
  CHANGELOG.md
  example/spec/parallel/emsReport/emsIngestDistributionReportSpec.js
  package.json
  packages/api/ecs/async-operation/index.js
  packages/api/ecs/async-operation/package.json
  packages/api/package.json
  packages/common/package.json
  packages/common/src/http.ts
  packages/common/src/index.ts
  packages/common/tests/http/download.js
  packages/earthdata-login-client/package.json
  packages/ingest/package.json
  packages/ingest/src/HttpProviderClient.js
  packages/integration-tests/api/EarthdataLogin.js
  packages/integration-tests/cmr.js
  packages/integration-tests/package.json
  packages/launchpad-auth/package.json
  packages/s3-credentials-endpoint/package.json
  packages/tea-map-cache/package.json
  tasks/discover-granules/package.json
Labels: :turkey:

#1952 Release 3.0.1 release version up/etc
  CHANGELOG.md
  example/lambdas/asyncOperations/package.json
  example/lambdas/python-processing/package.json
  example/lambdas/python-reference-activity/package.json
  example/lambdas/python-reference-task/package.json
  example/lambdas/s3AccessTest/package.json
  example/lambdas/snsS3Test/package.json
  example/lambdas/versionUpTest/package.json
  example/package.json
  lambdas/sqs-message-remover/package.json
  lerna.json
  packages/api-client/package.json
  packages/api/package.json
  packages/aws-client/package.json
  packages/checksum/package.json
  packages/cmr-client/API.md
  packages/cmr-client/package.json
  packages/cmrjs/package.json
  packages/collection-config-store/package.json
  packages/common/package.json
  packages/earthdata-login-client/package.json
  packages/errors/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  packages/launchpad-auth/package.json
  packages/logger/package.json
  packages/message/package.json
  packages/pvl/package.json
  packages/s3-credentials-endpoint/package.json
  packages/sftp-client/package.json
  packages/tea-map-cache/package.json
  packages/test-data/package.json
  packages/tf-inventory/package.json
  packages/types/package.json
  tasks/add-missing-file-checksums/package.json
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/files-to-granules/package.json
  tasks/hello-world/package.json
  tasks/hyrax-metadata-updates/package.json
  tasks/move-granules/package.json
  tasks/parse-pdr/package.json
  tasks/pdr-status-check/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-granules/package.json
  tasks/queue-pdrs/package.json
  tasks/sf-sqs-report/package.json
  tasks/sync-granule/package.json
  tasks/test-processing/package.json
  tasks/update-cmr-access-constraints/package.json
  tf-modules/s3-replicator/package.json
  website/package.json
  website/versions.json
Labels: current sprint

#1953 Cumulus 2182 pdr migration
  CHANGELOG.md
  lambdas/db-migration/src/migrations/20201014105054_create_pdrs_table.ts
Labels: current sprint

#1961 Cumulus 2145 bootcamp docs - Update deployment docs
  .markdownlint.json
  docs/deployment/README.md
  docs/deployment/thin-egress-app.md
  example/cumulus-tf/variables.tf
  website/siteConfig.js
Labels: in review

#1943 CUMULUS-2228: Add branching write logic for executions to RDS
  lambdas/data-migration1/package.json
  lambdas/data-migration1/src/collections.ts
  lambdas/data-migration1/src/providers.ts
  lambdas/db-migration/package.json
  lambdas/db-migration/src/migrations/20201014105045_create_executions_table.ts
  packages/api/lambdas/sf-event-sqs-to-db-records.js
  packages/api/models/executions.js
  packages/api/models/schemas.js
  packages/api/package.json
  packages/api/tests/lambdas/test-sf-event-sqs-to-db-records.js
  packages/api/tests/models/test-executions-model.js
  packages/db/package.json
  packages/db/src/database.ts
  packages/db/src/index.ts
  packages/db/src/tables.ts
  packages/db/src/types.ts
  packages/db/tests/test-config.js
  packages/db/tests/test-connection.js
  packages/db/tests/test-database.js
  packages/message/src/AsyncOperations.ts
  packages/message/src/Collections.ts
  packages/message/src/Executions.ts
  packages/message/tests/test-AsyncOperations.js
  packages/message/tests/test-Collections.js
  packages/message/tests/test-Executions.js
  packages/types/message.d.ts
  tf-modules/archive/sf_event_sqs_to_db_records.tf
  tf-modules/ingest/.gitignore
  tf-modules/ingest/message_template.tf
  tf-modules/ingest/package.json
  tf-modules/ingest/scripts/write-cumulus-version.js
Labels: pr feedback

#1972 [CUMULUS-2248] Update Integration Test README
  CHANGELOG.md
  example/README.md
Labels: pr feedback

#1957 CMA module output = cumulus module expected input
  bamboo/bootstrap-tf-deployment.sh
  docs/workflows/input_output.md
  example/cumulus-tf/cnm_response_task.tf
  example/cumulus-tf/cnm_to_cma_task.tf
  example/cumulus-tf/main.tf
  example/cumulus-tf/python-reference-task.tf
  example/cumulus-tf/terraform.tfvars.example
  example/cumulus-tf/variables.tf
  tf-modules/cumulus-message-adapter/outputs.tf
  tf-modules/cumulus/README.md
  tf-modules/cumulus/ingest.tf
  tf-modules/cumulus/variables.tf
  tf-modules/ingest/add-missing-file-checksums.tf
  tf-modules/ingest/discover-granules-task.tf
  tf-modules/ingest/discover-pdrs-task.tf
  tf-modules/ingest/fake-processing-task.tf
  tf-modules/ingest/files-to-granules-task.tf
  tf-modules/ingest/hello-world-task.tf
  tf-modules/ingest/hyrax-metadata-updates-task.tf
  tf-modules/ingest/lambda-functions.tf
  tf-modules/ingest/move-granules-task.tf
  tf-modules/ingest/parse-pdr-task.tf
  tf-modules/ingest/pdr-status-check-task.tf
  tf-modules/ingest/post-to-cmr-task.tf
  tf-modules/ingest/queue-granules-task.tf
  tf-modules/ingest/queue-pdrs-task.tf
  tf-modules/ingest/sync-granule-task.tf
  tf-modules/ingest/update-cmr-access-constraints.tf
  tf-modules/ingest/variables.tf
Labels: pr feedback

#1944 [CUMULUS-2170] Add FilterExpression to granule scan
  CHANGELOG.md
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  packages/api/lambdas/reports/granule-inventory-report.js
  packages/api/lib/reconciliationReport.js
  packages/api/lib/reconciliationReport/normalizeEvent.js
  packages/api/models/granules.js
  packages/api/tests/lambdas/test-create-reconciliation-report.js
  packages/api/tests/lambdas/test-granule-inventory-report.js
  packages/api/tests/models/granules/test-granules-model.js
Labels: pr feedback

#1980 adding required field to execution writes
  packages/api/lambdas/sf-event-sqs-to-db-records.js
Labels: needs review
