Repository nasa/cumulus, pull requests merged in 2021-03, with the labels that each got.

#2115 [CUMULUS-2383] Handle CMR 5XX Errors in PostToCmr
  CHANGELOG.md
  packages/cmr-client/package.json
  packages/cmr-client/src/UmmUtils.ts
  packages/cmr-client/src/ValidationError.ts
  packages/cmr-client/src/index.ts
  packages/cmr-client/src/validate.ts
  packages/cmr-client/tests/test-CMR.js
  packages/cmr-client/tests/test-UmmUtils.js
  packages/cmr-client/tests/test-ingestConcept.js
  packages/cmrjs/src/utils.js
  packages/errors/src/index.ts
  tasks/hyrax-metadata-updates/tests/test-integration-index.js
  tasks/post-to-cmr/tests/cmr-test.js
Labels: in review

#2108 Feature/cumulus 2309 granule bulk deletes
  CHANGELOG.md
  example/.env.sample
  packages/api/lambdas/bulk-operation.js
  packages/api/lib/create-test-data.js
  packages/api/lib/granule-delete.js
  packages/api/lib/granule-remove-from-cmr.js
  packages/api/lib/granules.js
  packages/api/models/granules.js
  packages/api/tests/endpoints/test-granules.js
  packages/api/tests/lambdas/test-bulk-granule-delete.js
  packages/api/tests/lambdas/test-bulk-operation.js
  packages/api/tests/lib/test-granule-delete.js
  packages/api/tests/lib/test-granule-remove-from-cmr.js
  packages/api/tests/models/granules/test-granule-delete.js
Labels: pr feedback

#2118 replaces a sequence of calls to cmr with a single compound call.
  CHANGELOG.md
  packages/api/lib/mmt.js
  packages/api/tests/lib/fixtures/cmrResults.json
  packages/api/tests/lib/fixtures/collectionESResult.json
  packages/api/tests/lib/test-mmt.js
  packages/cmrjs/package.json
  packages/cmrjs/src/cmr-utils.js
  packages/cmrjs/src/index.js
  packages/cmrjs/tests/cmr-utils/test-cmr-utils.js
Labels: in review

#2125 Changes waitForAsyncOperationStatus to fail if status not reached.
  CHANGELOG.md
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  packages/integration-tests/index.js
Labels: in review

#2067 CUMULUS-2328: Separate s3-credentials deployment to separate module
  CHANGELOG.md
  bamboo/create-release-artifacts.sh
  bamboo/create-release.sh
  docs/architecture.md
  docs/deployment/README.md
  docs/deployment/components.md
  docs/deployment/create_bucket.md
  docs/development/release.md
  example/cumulus-tf/main.tf
  example/cumulus-tf/outputs.tf
  example/cumulus-tf/s3_credentials.tf
  example/cumulus-tf/thin_egress_app.tf
  example/cumulus-tf/variables.tf
  tf-modules/archive/api.tf
  tf-modules/archive/variables.tf
  tf-modules/cumulus/README.md
  tf-modules/cumulus/archive.tf
  tf-modules/cumulus/distribution.tf
  tf-modules/cumulus/outputs.tf
  tf-modules/cumulus/variables.tf
  tf-modules/distribution/README.md
  tf-modules/distribution/bin/build-tf-module.sh
  tf-modules/distribution/main.tf
  tf-modules/distribution/outputs.tf
  tf-modules/distribution/variables.tf
  tf-modules/s3-credentials/README.md
  tf-modules/s3-credentials/bin/build-tf-module.sh
  tf-modules/s3-credentials/main.tf
  tf-modules/s3-credentials/outputs.tf
  tf-modules/s3-credentials/variables.tf
Labels: pr feedback

#2114 CUMULUS-2424: Update queue-pdrs to have ChildWorkflowMeta
  CHANGELOG.md
  example/cumulus-tf/discover_and_queue_pdrs_with_child_workflow_meta_workflow.asl.json
  example/cumulus-tf/discover_and_queue_pdrs_with_child_workflow_meta_workflow.tf
  example/deployments/cumulus/mvd-tf.tfvars
  example/spec/parallel/ingest/ingestFromPdrWithChildWorkflowMetaSpec.js
  tasks/queue-pdrs/index.js
  tasks/queue-pdrs/schemas/config.json
  tasks/queue-pdrs/tests/index.js
Labels: needs review

#2123 CUMULUS-2394 -- Update granule/pdr writes to not allow old workflows to overwrite new records
  CHANGELOG.md
  packages/api/models/granules.js
  packages/api/models/pdrs.js
  packages/api/tests/models/granules/test-granule-reporting.js
  packages/api/tests/models/test-pdrs-model.js
  packages/errors/src/index.ts
  packages/message/package.json
  packages/message/src/workflows.ts
  packages/message/tests/test-workflows.js
  packages/types/message.d.ts
Labels: current sprint

#2134 Revert CUMULUS-2328: Separate s3-credentials deployment to separate module
  CHANGELOG.md
  bamboo/create-release-artifacts.sh
  bamboo/create-release.sh
  docs/architecture.md
  docs/deployment/README.md
  docs/deployment/components.md
  docs/deployment/create_bucket.md
  docs/development/release.md
  example/cumulus-tf/main.tf
  example/cumulus-tf/outputs.tf
  example/cumulus-tf/s3_credentials.tf
  example/cumulus-tf/thin_egress_app.tf
  example/cumulus-tf/variables.tf
  tf-modules/archive/api.tf
  tf-modules/archive/variables.tf
  tf-modules/cumulus/README.md
  tf-modules/cumulus/archive.tf
  tf-modules/cumulus/distribution.tf
  tf-modules/cumulus/outputs.tf
  tf-modules/cumulus/variables.tf
  tf-modules/distribution/README.md
  tf-modules/distribution/bin/build-tf-module.sh
  tf-modules/distribution/main.tf
  tf-modules/distribution/outputs.tf
  tf-modules/distribution/variables.tf
  tf-modules/s3-credentials/README.md
  tf-modules/s3-credentials/bin/build-tf-module.sh
  tf-modules/s3-credentials/main.tf
  tf-modules/s3-credentials/outputs.tf
  tf-modules/s3-credentials/variables.tf
Labels: release-critical

#2128 Jk/cumulus 2394 feature rds
  CHANGELOG.md
  packages/api/models/granules.js
  packages/api/models/pdrs.js
  packages/api/tests/lib/test-granule-delete.js
  packages/api/tests/models/granules/test-granule-reporting.js
  packages/api/tests/models/granules/test-granules-model.js
  packages/api/tests/models/test-pdrs-model.js
  packages/db/src/lib/timestamp.ts
  packages/db/src/models/granule.ts
  packages/db/src/models/pdr.ts
  packages/db/src/test-utils.ts
  packages/db/tests/models/test-granule-model.js
  packages/db/tests/models/test-pdr-model.js
  packages/errors/src/index.ts
  packages/message/package.json
  packages/message/src/errors.ts
  packages/message/src/workflows.ts
  packages/message/tests/test-workflows.js
Labels: current sprint

#2135 Prevent elasticsearch from reindexing when source index matches destination index
  CHANGELOG.md
  packages/api/endpoints/elasticsearch.js
  packages/api/tests/endpoints/test-elasticsearch.js
Labels: needs review, pr feedback

#2137 Fix Reconcilation test scroll id timeouts
  CHANGELOG.md
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  packages/api/es/esDefaults.js
Labels: needs review

#2130 CUMULUS-2427: SQS/Kinesis rules should use custom queue
  CHANGELOG.md
  docs/configuration/data-management-types.md
  docs/tasks.md
  example/spec/parallel/kinesisTests/KinesisTestTriggerSpec.js
  example/spec/parallel/startSF/startSfSpec.js
  example/spec/parallel/testAPI/sqsRuleSpec.js
  packages/api/lambdas/sf-scheduler.js
  packages/api/lambdas/sf-starter.js
  packages/api/lambdas/sqs-message-consumer.js
  packages/api/lib/rulesHelpers.js
  packages/api/tests/lambdas/test-sf-scheduler.js
  packages/api/tests/lambdas/test-sf-starter.js
  packages/api/tests/lib/test-rulesHelpers.js
  packages/ingest/src/consumer.ts
  packages/ingest/src/queue.js
  packages/ingest/test/test-queue.js
  packages/message/src/Build.ts
  packages/message/src/Queue.ts
  packages/message/tests/test-Build.js
  packages/types/message.d.ts
  tasks/queue-pdrs/tests/index.js
  tasks/queue-workflow/tests/index.js
  website/sidebars.json
Labels: current sprint, pr feedback, release-critical

#2131 Add documentation on validating and resuming an Elasticsearch reindex
  docs/external-contributions/external-contributions.md
  docs/troubleshooting/reindex-elasticsearch.md
Labels: pr feedback

#2140 CUMULUS-2186: Migrate PDRs - Add call to migrate in index.ts
  lambdas/data-migration1/src/index.ts
  lambdas/data-migration1/tests/test-index.js
  lambdas/data-migration2/src/index.ts
  lambdas/data-migration2/tests/test-index.js
Labels: high priority, pr feedback
