Repository nasa/cumulus, pull requests merged in 2021-05, with the labels that each got.

#2191 [PRE-RDS release] Update env var for minimum RDS version
  tf-modules/archive/sf_event_sqs_to_db_records.tf
Labels: blocked

#2210 execution name fix to avoid dropping message with bad cumulus_meta
  packages/api/lambdas/write-db-dlq-records-to-s3.js
  packages/api/tests/lambdas/test-write-db-dlq-records-to-s3.js
Labels: pr feedback

#2211 log existing errors before overwrite in granule records on file write failure
  example/spec/parallel/ingestGranule/IngestGranuleFailureSpec.js
  packages/api/lambdas/sf-event-sqs-to-db-records/write-granules.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-write-granules.js
Labels: pr feedback

#2200 CUMULUS-2434: Update granules CMR metadata task to have both S3 and distribution links
  CHANGELOG.md
  docs/data-cookbooks/tracking-files.md
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  example/spec/parallel/ingestGranule/IngestGranule.UMM.output.payload.template.json
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestUMMGSuccessSpec.js
  example/spec/parallel/ingestGranule/ingestGranuleQueueSpec.js
  packages/api/lambdas/create-reconciliation-report.js
  packages/cmrjs/src/cmr-utils.js
  packages/cmrjs/src/utils.js
  packages/cmrjs/tests/cmr-utils/test-cmr-utils.js
  packages/cmrjs/tests/cmr-utils/test-constructurls.js
  packages/cmrjs/tests/cmr-utils/test-mergeURLs.js
  packages/cmrjs/tests/cmr-utils/test-reconcilecmrmetadata.js
  packages/cmrjs/tests/test-utils.js
  packages/integration-tests/api/distribution.js
  packages/integration-tests/cmr.js
  tasks/move-granules/schemas/config.json
  tasks/update-granules-cmr-metadata-file-links/index.js
  tasks/update-granules-cmr-metadata-file-links/schemas/config.json
  tasks/update-granules-cmr-metadata-file-links/tests/test-index.js
Labels: in review

#2219 [CUMULUS-2488] Add back reportToEms field
  docs/operator-docs/trigger-workflow.md
  example/data/collections/L2_HR_PIXC-000/L2_HR_PIXC-000.json
  example/data/collections/ems/A2_RainOcn_NRT_0.json
  example/data/collections/ems/A2_SI25_NRT_0.json
  example/data/collections/ems/MUR-JPL-L4-GLOB-v4.1_1.json
  example/data/collections/ems/MYDTEST_099.json
  example/data/collections/http_testcollection_001/http_testcollection_001.json
  example/data/collections/http_testcollection_002/http_testcollection_002.json
  example/data/collections/https_testcollection_001/https_testcollection_001.json
  example/data/collections/s3_MOD09GQ_006-umm/s3_MOD09GQ_006.json
  example/data/collections/s3_MOD09GQ_006/s3_MOD09GQ_006.json
  example/data/collections/s3_MOD09GQ_006_full_ingest/s3_MOD09GQ_006.json
  example/data/collections/s3_MOD09GQ_006_no_cmr/s3_MOD09GQ_006.json
  example/data/collections/s3_MOD09GQ_006_orca/s3_MOD09GQ_006.json
  example/data/collections/s3_MYD13Q1_006/s3_MYD13Q1_006.json
  example/scripts/generate_ingest/sample_collection/MOD09GQ.006.json
  example/spec/loadTest/collection/s3_loadtest_MOD09GQ_006L.json
  lambdas/data-migration1/tests/test-collections.js
  lambdas/data-migration1/tests/test-index.js
  lambdas/db-migration/src/migrations/20210504103649_collections_table_remove_report_to_ems_column.ts
  packages/api/lib/testUtils.js
  packages/api/models/collections.js
  packages/api/models/schemas.js
  packages/api/tests/lib/fixtures/collectionESResult.json
  packages/api/tests/models/test-collections-model.js
  packages/db/src/translate/collections.ts
  packages/db/src/types/collection.ts
  packages/integration-tests/Collections.js
  packages/integration-tests/README.md
Labels: needs review

#2213 Update unit test stack commands to use built-in compose
  package.json
Labels: low priority

#2225 CUMULUS-2434-2:Update CMR S3 Link type based on UMM-G version
  CHANGELOG.md
  packages/api/lambdas/create-reconciliation-report.js
  packages/cmrjs/src/cmr-utils.js
  packages/cmrjs/tests/cmr-utils/test-cmr-utils.js
  packages/cmrjs/tests/cmr-utils/test-constructurls.js
  packages/cmrjs/tests/fixtures/MOD09GQ.A3411593.1itJ_e.006.9747594822314_v1.6.2.cmr.json
Labels: pr feedback

#2218 HYRAX-439: Corrected README for hyrax-metadata-update in tasks.
  CHANGELOG.md
  tasks/hyrax-metadata-updates/README.md
Labels: User Contribution

#2192 [CUMULUS-2474] Add S3ObjectStore to aws-client
  .eslintignore
  CHANGELOG.md
  packages/aws-client/src/S3ObjectStore.ts
  packages/aws-client/src/index.ts
  packages/aws-client/tests/test-S3ObjectStore.js
  packages/object-store/.gitignore
  packages/object-store/.npmignore
  packages/object-store/README.md
  packages/object-store/package.json
  packages/object-store/src/index.ts
  packages/object-store/tests/test-index.js
  packages/object-store/tsconfig.json
Labels: pr feedback

#2232 [CUMULUS-2231] Adds .md extension to docs/README.md links
  CHANGELOG.md
  docs/README.md
Labels: User Contribution

#2255 Release 8.1.1
  CHANGELOG.md
  example/lambdas/asyncOperations/package.json
  example/lambdas/python-processing/package.json
  example/lambdas/python-reference-activity/package.json
  example/lambdas/python-reference-task/package.json
  example/lambdas/s3AccessTest/package.json
  example/lambdas/snsS3Test/package.json
  example/lambdas/versionUpTest/package.json
  example/package.json
  lambdas/sqs-message-remover/package.json
  lerna.json
  packages/api-client/package.json
  packages/api/package.json
  packages/aws-client/package.json
  packages/checksum/package.json
  packages/cmr-client/package.json
  packages/cmrjs/package.json
  packages/collection-config-store/package.json
  packages/common/package.json
  packages/earthdata-login-client/package.json
  packages/errors/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  packages/launchpad-auth/package.json
  packages/logger/package.json
  packages/message/package.json
  packages/pvl/package.json
  packages/s3-credentials-endpoint/package.json
  packages/sftp-client/package.json
  packages/tea-map-cache/package.json
  packages/test-data/package.json
  packages/tf-inventory/package.json
  packages/types/package.json
  tasks/add-missing-file-checksums/package.json
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/files-to-granules/package.json
  tasks/hello-world/package.json
  tasks/hyrax-metadata-updates/package.json
  tasks/lzards-backup/package.json
  tasks/move-granules/package.json
  tasks/parse-pdr/package.json
  tasks/pdr-status-check/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-granules/package.json
  tasks/queue-pdrs/package.json
  tasks/queue-workflow/package.json
  tasks/sf-sqs-report/package.json
  tasks/sync-granule/package.json
  tasks/test-processing/package.json
  tasks/update-cmr-access-constraints/package.json
  tasks/update-granules-cmr-metadata-file-links/package.json
  tf-modules/s3-replicator/package.json
  website/versions.json
Labels: needs review

#2253 deployment-readme-ecs-ami
  docs/deployment/README.md
Labels: User Contribution

#2259 Jk/cumulus 2512 v9
  CHANGELOG.md
  packages/ingest/src/FtpProviderClient.ts
  packages/ingest/src/HttpProviderClient.js
  packages/ingest/src/S3ProviderClient.ts
  packages/ingest/src/SftpProviderClient.js
  packages/ingest/src/providerClientUtils.js
  packages/ingest/src/types.ts
  packages/ingest/test/test-FtpProviderClient.js
  packages/ingest/test/test-HttpProviderClient.js
  packages/ingest/test/test-HttpsProviderClient.js
  packages/ingest/test/test-S3ProviderClient.js
  packages/ingest/test/test-SftpProviderClient.js
  tasks/parse-pdr/index.js
  tasks/sync-granule/GranuleFetcher.js
  tasks/sync-granule/tests/sync_granule_test.js
Labels: current sprint, pr feedback
