Repository nasa/cumulus, pull requests merged in 2021-01, with the labels that each got.

#2019 Add retry to ensure localstack is up and running.
  CHANGELOG.md
  packages/api/bin/serve.js
Labels: low priority

#2027 CUMULUS-2234 populate test bucket
  example/scripts/generate_ingest/README.md
  example/scripts/generate_ingest/generate_files.js
  example/scripts/generate_ingest/package.json
  example/scripts/generate_ingest/sample_collection/MOD09GQ.006.json
Labels: current sprint

#1868 Update rds module/docs to cover disaster recovery scenarios
  docs/assets/rds_cluster_update.jpg
  docs/assets/secrets_manager_update.jpg
  docs/features/backup_and_restore.md
  example/rds-cluster-tf/main.tf
  example/rds-cluster-tf/variables.tf
  tf-modules/cumulus-rds-tf/main.tf
  tf-modules/cumulus-rds-tf/variables.tf
Labels: current sprint, needs review

#2014 CUMULUS-2279: Change CMR Links
  CHANGELOG.md
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  packages/cmr-client/src/CMR.ts
  packages/cmr-client/src/getConcept.ts
  packages/cmr-client/tests/test-getConcept.js
  packages/cmrjs/src/cmr-utils.js
  packages/cmrjs/tests/cmr-utils/test-cmr-utils.js
  packages/integration-tests/cmr.js
  tasks/post-to-cmr/tests/cmr-test.js
Labels: pr feedback

#2047 Update docker-compose configuration
  bamboo/docker-compose-local.yml
  bamboo/docker-compose.yml
Labels: high priority, needs review

#2038 CUMULUS-2283: Lock & Install Python dependencies with pipenv
  example/lambdas/python-processing/Dockerfile
  example/lambdas/python-processing/Pipfile
  example/lambdas/python-processing/Pipfile.lock
  example/lambdas/python-processing/package.json
  example/lambdas/python-processing/requirements-dev.txt
  example/lambdas/python-processing/requirements.txt
  example/lambdas/python-reference-activity/Dockerfile
  example/lambdas/python-reference-activity/Pipfile
  example/lambdas/python-reference-activity/Pipfile.lock
  example/lambdas/python-reference-activity/package.json
  example/lambdas/python-reference-activity/requirements-dev.txt
  example/lambdas/python-reference-activity/requirements.txt
  example/lambdas/python-reference-task/Pipfile
  example/lambdas/python-reference-task/Pipfile.lock
  example/lambdas/python-reference-task/package.json
  example/lambdas/python-reference-task/package.sh
  example/lambdas/python-reference-task/requirements-dev.txt
  example/lambdas/python-reference-task/requirements.txt
Labels: pr feedback

#2032 CUMULUS-2128: Add parallel write to Postgres for granules/files
  CHANGELOG.md
  example/spec/parallel/ingestGranule/IngestElevenGiBFileSpec.js
  lambdas/db-migration/src/migrations/20201014105058_create_granules_table.ts
  lambdas/db-migration/src/migrations/20201014105102_create_files_table.ts
  packages/api/endpoints/collections.js
  packages/api/lambdas/sf-event-sqs-to-db-records/index.js
  packages/api/lambdas/sf-event-sqs-to-db-records/utils.js
  packages/api/lambdas/sf-event-sqs-to-db-records/write-granules.js
  packages/api/lib/FileUtils.js
  packages/api/lib/granules.js
  packages/api/lib/utils.js
  packages/api/models/granules.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-write-execution.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-write-granules.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-write-pdr.js
  packages/api/tests/lib/FileUtils/test-setS3FileSize.js
  packages/api/tests/lib/test-granules.js
  packages/api/tests/models/granules/test-granule-generateGranuleRecord.js
  packages/api/tests/models/granules/test-granule-reporting.js
  packages/cmrjs/src/cmr-utils.js
  packages/cmrjs/tests/cmr-utils/test-cmr-utils.js
  packages/db/src/models/collection.ts
  packages/db/src/types/granule.ts
  packages/db/tests/models/test-collection-model.js
  packages/db/tests/models/test-granule-model.js
  packages/message/src/Granules.ts
  packages/message/src/Providers.ts
  packages/message/tests/test-Granules.js
  packages/message/tests/test-Providers.js
  packages/types/message.d.ts
  tf-modules/archive/sf_event_sqs_to_db_records.tf
Labels: current sprint

#2045 [CUMULUS-2344] Remove some restrictions from ES endpoints
  CHANGELOG.md
  docs/troubleshooting/README.md
  docs/troubleshooting/reindex-elasticsearch.md
  packages/api/endpoints/elasticsearch.js
  packages/api/tests/endpoints/test-elasticsearch.js
  website/sidebars.json
Labels: pr feedback
