Repository nasa/cumulus, pull requests merged in 2021-04, with the labels that each got.

#2146 [CUMULUS-2374] Add cookbook entry for workflow re-queueing
  CHANGELOG.md
  docs/assets/queue-workflow.png
  docs/data-cookbooks/queue-post-to-cmr.md
  example/cumulus-tf/ingest_granule_with_queue_workflow.asl.json
  example/cumulus-tf/ingest_granule_with_queue_workflow.tf
  example/cumulus-tf/publish_granule_with_requeue_workflow.asl.json
  example/cumulus-tf/publish_granule_with_requeue_workflow.tf
  example/deployments/cumulus/dop-ci-tf.tfvars
  example/spec/parallel/ingestGranule/ingestGranuleQueueSpec.js
  example/spec/parallel/testAPI/bulkOperationsSuccessSpec.js
  packages/ingest/src/queue.js
  tasks/queue-workflow/index.js
  tasks/queue-workflow/schemas/config.json
  tasks/queue-workflow/schemas/input.json
  tasks/queue-workflow/schemas/output.json
  tasks/queue-workflow/tests/index.js
  tf-modules/cumulus/outputs.tf
  tf-modules/ingest/outputs.tf
  website/sidebars.json
Labels: in review

#2164 CUMULUS-2406: Ensure that same updatedAt value is used for Dynamo/PG across all data types
  CHANGELOG.md
  packages/api/ecs/async-operation/index.js
  packages/api/ecs/async-operation/tests/test-index.js
  packages/api/endpoints/rules.js
  packages/api/lambdas/sf-event-sqs-to-db-records/write-execution.js
  packages/api/lambdas/sf-event-sqs-to-db-records/write-granules.js
  packages/api/lambdas/sf-event-sqs-to-db-records/write-pdr.js
  packages/api/lib/testUtils.js
  packages/api/models/base.js
  packages/api/models/executions.js
  packages/api/models/granules.js
  packages/api/models/pdrs.js
  packages/api/models/rules.js
  packages/api/tests/endpoints/collections/create-collection.js
  packages/api/tests/endpoints/collections/delete-collection.js
  packages/api/tests/endpoints/collections/update-collection.js
  packages/api/tests/endpoints/providers/create-provider.js
  packages/api/tests/endpoints/providers/delete-provider.js
  packages/api/tests/endpoints/providers/update-provider.js
  packages/api/tests/endpoints/test-rules.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-index.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-write-execution.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-write-granules.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-write-pdr.js
  packages/api/tests/models/rules/test-query-rules.js
  packages/api/tests/models/rules/test-rules-model.js
  packages/api/tests/models/test-executions-model.js
  packages/async-operations/src/async_operations.ts
  packages/async-operations/tests/test-async_operations.js
Labels: current sprint

#2165 [CUMULUS-2313] Postgres Migration Async Operation
  CHANGELOG.md
  example/cumulus-tf/main.tf
  example/cumulus-tf/variables.tf
  example/deployments/cumulus/jtran-int-tf.tfvars
  lambdas/db-migration/src/migrations/20201014105030_create_async_operations_table.ts
  lambdas/postgres-migration-async-operation/README.md
  lambdas/postgres-migration-async-operation/iam.tf
  lambdas/postgres-migration-async-operation/main.tf
  lambdas/postgres-migration-async-operation/outputs.tf
  lambdas/postgres-migration-async-operation/package.json
  lambdas/postgres-migration-async-operation/src/index.ts
  lambdas/postgres-migration-async-operation/tests/test-index.js
  lambdas/postgres-migration-async-operation/tsconfig.json
  lambdas/postgres-migration-async-operation/variables.tf
  lambdas/postgres-migration-async-operation/versions.tf
  lambdas/postgres-migration-async-operation/webpack.config.js
  packages/api/models/schemas.js
  tf-modules/archive/api.tf
  tf-modules/archive/outputs.tf
  tf-modules/archive/variables.tf
  tf-modules/cumulus/archive.tf
  tf-modules/cumulus/postgres-migration-async-operation.tf
Labels: in review

#2158 Remove dependence on process.env.GRANULES in logs #2157
  CHANGELOG.md
  packages/logger/src/index.ts
  tasks/discover-granules/index.js
Labels: needs review, pr feedback

#2154 CUMULUS-2421: docker cleanup cronjob flag & variable
  CHANGELOG.md
  example/cumulus-tf/main.tf
  example/cumulus-tf/variables.tf
  tf-modules/cumulus/ecs_cluster.tf
  tf-modules/cumulus/ecs_cluster_instance_autoscaling_cf_template.yml.tmpl
  tf-modules/cumulus/variables.tf
Labels: release-critical

#2167 CUMULUS-2348: Add Granule Recovery status to granules endpoint
  CHANGELOG.md
  example/deployments/cumulus/cumulus-sit.tfvars
  example/spec/parallel/orca/OrcaBackupAndRecoverySpec.js
  packages/api-client/src/granules.ts
  packages/api-client/tests/test-granules.js
  packages/api/endpoints/granules.js
  packages/api/endpoints/orca.js
  packages/api/lib/orca.js
  packages/api/package.json
  packages/api/tests/lib/test-orca.js
Labels: in review

#2169 [CUMULUS-1808] Expanded error messaging when disabling rule
  CHANGELOG.md
  example/spec/parallel/orca/OrcaBackupAndRecoverySpec.js
  packages/api/lib/errors.js
  packages/api/models/rules.js
  packages/api/tests/models/rules/test-sns-rules.js
Labels: pr feedback

#2193 Update queue-post-to-cmr.md
  docs/data-cookbooks/queue-post-to-cmr.md
Labels: User Contribution, needs review

#2198 Update queue-post-to-cmr.md
  docs/data-cookbooks/queue-post-to-cmr.md
Labels: needs review

#2179 [CUMULUS-2453] Store errors for executions and granules and files in a JSON file
  CHANGELOG.md
  lambdas/data-migration2/README.md
  lambdas/data-migration2/main.tf
  lambdas/data-migration2/package.json
  lambdas/data-migration2/src/executions.ts
  lambdas/data-migration2/src/granulesAndFiles.ts
  lambdas/data-migration2/src/storeErrors.ts
  lambdas/data-migration2/tests/test-executions.js
  lambdas/data-migration2/tests/test-granulesAndFiles.js
  lambdas/data-migration2/tests/test-storeErrors.js
  lambdas/data-migration2/variables.tf
  tf-modules/cumulus/data-migrations.tf
Labels: pr feedback

#2188 CUMULUS-2469: Standup skeleton distribution API
  CHANGELOG.md
  example/cumulus-tf/cumulus_distribution.tf
  example/cumulus-tf/outputs.tf
  example/spec/parallel/orca/OrcaBackupAndRecoverySpec.js
  packages/api/app/distribution-routes.js
  tf-modules/cumulus_distribution/api.tf
  tf-modules/cumulus_distribution/iam.tf
  tf-modules/cumulus_distribution/main.tf
  tf-modules/cumulus_distribution/outputs.tf
  tf-modules/cumulus_distribution/variables.tf
  tf-modules/cumulus_distribution/vpc.tf
Labels: needs review

#2181 CUMULUS-2380: process dead letter archive
  CHANGELOG.md
  example/spec/parallel/dbRecords/DbRecordsDLQSpec.js
  example/spec/parallel/dbRecords/DeadLetterArchiveProcessingSpec.js
  lambdas/db-migration/src/migrations/20201014105030_create_async_operations_table.ts
  packages/api-client/src/deadLetterArchive.ts
  packages/api-client/tests/test-deadLetterArchive.js
  packages/api/app/routes.js
  packages/api/endpoints/dead-letter-archive.js
  packages/api/lambdas/process-s3-dead-letter-archive.js
  packages/api/lib/testUtils.js
  packages/api/models/schemas.js
  packages/api/tests/endpoints/test-dead-letter-archive.js
  packages/api/tests/lambdas/test-process-s3-dead-letter-archive.js
  packages/api/webpack.config.js
  packages/types/api/async_operations.d.ts
  packages/types/api/dead_letters.d.ts
  tf-modules/archive/api.tf
  tf-modules/archive/process_dead_letter_archive.tf
Labels: pr feedback

#2207 Update release docs
  CHANGELOG.md
  docs/upgrade-notes/data-migrations-rds.md
  docs/upgrade-notes/upgrade-rds.md
  lambdas/data-migration2/README.md
  lambdas/data-migration2/src/executions.ts
  lambdas/data-migration2/src/granulesAndFiles.ts
  lambdas/data-migration2/src/pdrs.ts
  website/sidebars.json
Labels: pr feedback
