Repository nasa/cumulus, pull requests merged in 2021-10, with the labels that each got.

#2496 CUMULUS-2705: Add schemaspy generated doc/images
  bin/build_db_schema.sh
  docs/architecture.md
  docs/assets/db_schema/relationships.real.compact.png
  docs/assets/db_schema/relationships.real.large.png
  package.json
Labels: pr feedback

#2482 Various snyk upgrades
  CHANGELOG.md
  bamboo/generate-ts-build-cache.sh
  lambdas/sqs-message-remover/package.json
  packages/es-client/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  tasks/add-missing-file-checksums/package.json
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/files-to-granules/package.json
  tasks/hello-world/package.json
  tasks/hyrax-metadata-updates/package.json
  tasks/lzards-backup/package.json
  tasks/move-granules/package.json
  tasks/parse-pdr/package.json
  tasks/pdr-status-check/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-granules/package.json
  tasks/queue-pdrs/package.json
  tasks/queue-workflow/package.json
  tasks/sf-sqs-report/package.json
  tasks/sync-granule/package.json
  tasks/test-processing/package.json
  tasks/update-cmr-access-constraints/package.json
  tasks/update-granules-cmr-metadata-file-links/package.json
Labels: Very Small

#2514 CUMULUS-2388: Update docs
  CHANGELOG.md
  docs/configuration/data-management-types.md
  docs/data-cookbooks/browse-generation.md
  docs/data-cookbooks/sips-workflow.md
  docs/upgrade-notes/upgrade-task-file-schemas.md
  docs/workflow_tasks/files_to_granules.md
  docs/workflows/workflow-configuration-how-to.md
  website/sidebars.json
Labels: needs review
