Repository nasa/cumulus, pull requests merged in 2021-11, with the labels that each got.

#2548 Updated webpack configuration for html-loader v2
  CHANGELOG.md
  example/spec/parallel/orca/OrcaBackupAndRecoverySpec.js
  packages/api/webpack.config.js
  packages/s3-credentials-endpoint/webpack.config.js
Labels: needs review

#2550 Jk/pr2504
  CHANGELOG.md
Labels: User Contribution

#2532 CUMULUS-2683:configure a default chunk size for multi-part uploads across the system
  CHANGELOG.md
  packages/aws-client/src/S3.ts
  packages/aws-client/src/lib/S3MultipartUploads.ts
  packages/aws-client/tests/S3/test-moveObject.js
  packages/aws-client/tests/S3/test-multipartCopyObject.js
  tasks/move-granules/index.js
  tf-modules/cumulus/ingest.tf
  tf-modules/cumulus/variables.tf
  tf-modules/ingest/move-granules-task.tf
  tf-modules/ingest/variables.tf
Labels: pr feedback

#2563 Mhs/cumulus 2638/update documentation about bucket config clarify recreport usage
  CHANGELOG.md
  docs/features/reports.md
  docs/workflows/workflow-configuration-how-to.md
  packages/api/lambdas/create-reconciliation-report.js
  packages/common/src/BucketsConfig.ts
  packages/common/src/types.ts
  tasks/move-granules/index.js
Labels: in review

#2568 CUMULUS-2694: Remove dynamo only writes
  CHANGELOG.md
  packages/api/lambdas/sf-event-sqs-to-db-records/index.js
  packages/api/lib/writeRecords/utils.js
  packages/api/models/granules.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-index.js
  packages/api/tests/models/granules/test-granule-reporting.js
  packages/errors/src/index.ts
Labels: pr feedback

#2574 [CUMULUS-2744] Add associated granules to execution status
  CHANGELOG.md
  packages/api/endpoints/execution-status.js
  packages/api/tests/endpoints/test-execution-status.js
Labels: needs review
