Repository nasa/cumulus, pull requests merged in 2021-02, with the labels that each got.

#2058 Add the ability to attach extra security groups to ECS cluster
  tf-modules/cumulus/ecs_cluster.tf
  tf-modules/cumulus/variables.tf
Labels: in review

#2070 CUMULUS-2395: Add the ability to attach extra security groups to ECS cluster
  CHANGELOG.md
  example/cumulus-tf/main.tf
  example/cumulus-tf/variables.tf
  tf-modules/cumulus/ecs_cluster.tf
  tf-modules/cumulus/variables.tf
Labels: User Contribution

#2072 Adds new endpoint to distribution module at /s3credentialsREADME
  CHANGELOG.md
  example/deployments/cumulus/mhs-tf.tfvars
  packages/s3-credentials-endpoint/index.js
  packages/s3-credentials-endpoint/instructions/index.html
  packages/s3-credentials-endpoint/instructions/index.md
  packages/s3-credentials-endpoint/package.json
  packages/s3-credentials-endpoint/tests/test-index.js
  packages/s3-credentials-endpoint/webpack.config.js
  tf-modules/distribution/README.md
  tf-modules/distribution/main.tf
Labels: in review

#2076 Update build image to pin to latest v6
  bamboo/Dockerfile
Labels: needs review

#2078 expose sftp function in cumulus/sftp-client
  CHANGELOG.md
  packages/sftp-client/README.md
  packages/sftp-client/src/index.ts
Labels: needs review

#2061 Merge 5.0.1 to master
  .gitignore
  CHANGELOG.md
  example/lambdas/asyncOperations/package.json
  example/lambdas/python-processing/package.json
  example/lambdas/python-reference-activity/package.json
  example/lambdas/python-reference-task/package.json
  example/lambdas/s3AccessTest/package.json
  example/lambdas/snsS3Test/package.json
  example/lambdas/versionUpTest/package.json
  example/package.json
  lambdas/sqs-message-remover/package.json
  lerna.json
  packages/api-client/package.json
  packages/api/package.json
  packages/aws-client/package.json
  packages/checksum/package.json
  packages/cmr-client/package.json
  packages/cmrjs/package.json
  packages/collection-config-store/package.json
  packages/common/package.json
  packages/earthdata-login-client/package.json
  packages/errors/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  packages/launchpad-auth/package.json
  packages/logger/package.json
  packages/message/package.json
  packages/pvl/package.json
  packages/s3-credentials-endpoint/package.json
  packages/sftp-client/package.json
  packages/tea-map-cache/package.json
  packages/test-data/package.json
  packages/tf-inventory/package.json
  packages/types/package.json
  tasks/add-missing-file-checksums/package.json
  tasks/discover-granules/package.json
  tasks/discover-pdrs/package.json
  tasks/files-to-granules/package.json
  tasks/hello-world/package.json
  tasks/hyrax-metadata-updates/package.json
  tasks/lzards-backup/package.json
  tasks/move-granules/package.json
  tasks/parse-pdr/package.json
  tasks/pdr-status-check/package.json
  tasks/post-to-cmr/package.json
  tasks/queue-granules/package.json
  tasks/queue-pdrs/package.json
  tasks/sf-sqs-report/package.json
  tasks/sync-granule/package.json
  tasks/test-processing/package.json
  tasks/update-cmr-access-constraints/package.json
  tasks/update-granules-cmr-metadata-file-links/package.json
  tf-modules/s3-replicator/package.json
  website/versioned_docs/version-v5.0.1/troubleshooting/README.md
  website/versioned_docs/version-v5.0.1/troubleshooting/reindex-elasticsearch.md
  website/versioned_sidebars/version-v5.0.1-sidebars.json
  website/versions.json
Labels: in review

#2074 CUMULUS-2321: reconciliationReport API returns pre-signed URL
  CHANGELOG.md
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  packages/api/endpoints/reconciliation-reports.js
  packages/api/package.json
  packages/api/tests/endpoints/test-reconciliation-reports.js
Labels: in review

#2083 CUMULUS-2411 - Fix lambda_invocation data resources and thin_egress_app example terraform
  example/cumulus-tf/main.tf
  example/cumulus-tf/thin_egress_app.tf
  tasks/sync-granule/GranuleFetcher.js
  tf-modules/archive/bootstrap.tf
  tf-modules/distribution/main.tf
Labels: current sprint, release-critical

#2082 CUMULUS-2411 (feature RDS) - Fix lambda_invocation data resources and thin_egress_app example terraform
  example/cumulus-tf/main.tf
  example/cumulus-tf/thin_egress_app.tf
  example/lambdas/db-provision-user-database/main.tf
  lambdas/db-migration/main.tf
  tf-modules/archive/bootstrap.tf
  tf-modules/cumulus/variables.tf
  tf-modules/distribution/main.tf
Labels: current sprint

#2084 add tags to API gateways and TEA cloudformation stack
  example/cumulus-tf/thin_egress_app.tf
  tf-modules/archive/api.tf
Labels: low priority

#2075 Fix data migrations deploy
  example/cumulus-tf/data-migrations.tf
  example/cumulus-tf/variables.tf
  example/data-migration-ecs/main.tf
  example/data-migration-ecs/terraform.tf.example
  example/data-migration-ecs/terraform.tfvars.example
  example/data-migration-ecs/variables.tf
  example/data-migration-ecs/versions.tf
  example/data-migration1-tf/main.tf
  example/data-migration1-tf/terraform.tfvars.example
  example/data-migration1-tf/variables.tf
  example/data-migration2-tf/main.tf
  example/data-migration2-tf/outputs.tf
  example/data-migration2-tf/terraform.tf.example
  example/data-migration2-tf/terraform.tfvars.example
  example/data-migration2-tf/variables.tf
  example/data-migration2-tf/versions.tf
  lambdas/data-migration1/main.tf
  lambdas/data-migration2/main.tf
  tf-modules/cumulus/data-migrations.tf
  tf-modules/dynamo-to-pg-data-migration/main.tf
  tf-modules/dynamo-to-pg-data-migration/outputs.tf
  tf-modules/dynamo-to-pg-data-migration/variables.tf
  tf-modules/dynamo-to-pg-data-migration/versions.tf
Labels: low priority

#2089 [CUMULUS-2364] Remove log2elasticsearch
  CHANGELOG.md
  docs/data-cookbooks/run-tasks-in-lambda-or-docker.md
  docs/features/lambda_dead_letter_queue.md
  example/cumulus-tf/ecs_hello_world_workflow.tf
  example/cumulus-tf/python_processing_workflow.tf
  example/cumulus-tf/python_reference_workflow.tf
  packages/api/es/indexer.js
  packages/api/es/logUtils.js
  packages/api/tests/endpoints/logs.js
  packages/api/tests/es/test-es-indexer-log.js
  packages/api/tests/es/test-es-indexer.js
  tf-modules/archive/log2elasticsearch.tf
  tf-modules/archive/outputs.tf
  tf-modules/cumulus/log_subscription_filter.tf
  tf-modules/cumulus/outputs.tf
  tf-modules/cumulus_ecs_service/README.md
  tf-modules/cumulus_ecs_service/main.tf
  tf-modules/cumulus_ecs_service/variables.tf
  tf-modules/log-subscription-filter/async_operation_log_subscriptions.tf
  tf-modules/log-subscription-filter/ingest_log_subscriptions.tf
  tf-modules/log-subscription-filter/main.tf
  tf-modules/log-subscription-filter/variables.tf
Labels: pr feedback

#2102 Fix branch merging feature-rds to master
  example/lambdas/db-provision-user-database/package.json
  example/scripts/generate_ingest/package.json
  lambdas/data-migration1/package.json
  packages/api/ecs/async-operation/package.json
  packages/api/package.json
  packages/async-operations/package.json
  packages/db/package.json
Labels: needs review

#2097 CUMULUS-2345: Deploy ORCA with Cumulus
  CHANGELOG.md
  bamboo/bootstrap-tf-deployment.sh
  bamboo/set-bamboo-env-variables.sh
  example/cumulus-tf/ingest_and_publish_granule_workflow.asl.json
  example/cumulus-tf/ingest_and_publish_granule_workflow.tf
  example/cumulus-tf/orca.tf
  example/cumulus-tf/terraform.tfvars.example
  example/cumulus-tf/variables.tf
  example/data/collections/L2_HR_PIXC-000/L2_HR_PIXC-000.json
  example/data/collections/ems/A2_RainOcn_NRT_0.json
  example/data/collections/ems/A2_SI25_NRT_0.json
  example/data/collections/ems/MUR-JPL-L4-GLOB-v4.1_1.json
  example/data/collections/ems/MYDTEST_099.json
  example/data/collections/http_testcollection_001/http_testcollection_001.json
  example/data/collections/http_testcollection_002/http_testcollection_002.json
  example/data/collections/https_testcollection_001/https_testcollection_001.json
  example/data/collections/s3_MOD09GQ_006-umm/s3_MOD09GQ_006.json
  example/data/collections/s3_MOD09GQ_006/s3_MOD09GQ_006.json
  example/data/collections/s3_MOD09GQ_006_full_ingest/s3_MOD09GQ_006.json
  example/data/collections/s3_MOD09GQ_006_no_cmr/s3_MOD09GQ_006.json
  example/data/collections/s3_MOD14A1_006/s3_MOD14A1_006.json
  example/data/collections/s3_MYD13Q1_006/s3_MYD13Q1_006.json
  example/deployments/cumulus/jl-tf.tfvars
  example/deployments/cumulus/sandbox.tfvars
  example/deployments/cumulus/sit.tfvars
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  packages/integration-tests/Collections.js
Labels: in review

#2107 Adds SIT var for FAKE_PROVIDER_CONFIG_BUCKET
  bamboo/set-bamboo-env-variables.sh
Labels: in review

#2094 Improve spelling in documentation
  docs/README.md
  docs/data-cookbooks/choice-states.md
  docs/data-cookbooks/cnm-workflow.md
  docs/docs-how-to.md
  docs/features/logging-esdis-metrics.md
  docs/operator-docs/trigger-workflow.md
Labels: User Contribution, needs review

#2110 From: tniessen docs minor improvements
  docs/README.md
  docs/data-cookbooks/choice-states.md
  docs/data-cookbooks/cnm-workflow.md
  docs/docs-how-to.md
  docs/features/logging-esdis-metrics.md
  docs/operator-docs/trigger-workflow.md
Labels: User Contribution

#2101 better examples for s3 credentials
  CHANGELOG.md
  example/lambdas/s3AccessTest/index.js
  packages/s3-credentials-endpoint/instructions/index.html
  packages/s3-credentials-endpoint/instructions/index.md
Labels: in review
