Repository nasa/cumulus, pull requests merged in 2021-06, with the labels that each got.

#2224 [CUMULUS-2471] Add /s3CredentialsReadme to distribution API
  CHANGELOG.md
  package.json
  packages/api/app/distribution-routes.js
  packages/api/endpoints/s3credentials-readme/index.js
  packages/api/endpoints/s3credentials-readme/instructions/index.html
  packages/api/endpoints/s3credentials-readme/instructions/index.md
  packages/api/tests/endpoints/test-s3credentials-readme.js
  packages/api/webpack.config.js
  packages/s3-credentials-endpoint/index.js
  packages/s3-credentials-endpoint/package.json
  packages/s3-credentials-endpoint/tests/test-index.js
  packages/s3-credentials-endpoint/webpack.config.js
Labels: in review

#2262 add unit test for index from database
  packages/api/app/routes.js
  packages/api/endpoints/elasticsearch.js
  packages/api/tests/endpoints/test-elasticsearch.js
  packages/async-operations/src/async_operations.ts
Labels: needs review

#2261 Cumulus-2470 Adds /s3credentials endpoint for cumulus distribution
  CHANGELOG.md
  example/cumulus-tf/cumulus_distribution.tf
  packages/api/app/distribution-routes.js
  packages/api/endpoints/s3credentials.js
  packages/api/lib/distribution.js
  packages/api/tests/endpoints/test-s3credentials.js
  packages/s3-credentials-endpoint/index.js
  packages/s3-credentials-endpoint/tests/test-handler-with-edl-token.js
  packages/s3-credentials-endpoint/tests/test-index.js
  tf-modules/cumulus_distribution/api.tf
  tf-modules/cumulus_distribution/iam.tf
  tf-modules/cumulus_distribution/variables.tf
  tf-modules/distribution/main.tf
Labels: in review

#2260 Jk/cumulus 2537
  example/spec/helpers/apiUtils.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestUMMGSuccessSpec.js
  example/spec/parallel/ingestGranule/ingestGranuleQueueSpec.js
Labels: pr feedback

#2285 add logging to sfEventSqsToDbRecords to improve traceability
  packages/api/lambdas/sf-event-sqs-to-db-records/write-execution.js
  packages/api/lambdas/sf-event-sqs-to-db-records/write-granules.js
  packages/api/lambdas/sf-event-sqs-to-db-records/write-pdr.js
  packages/api/models/executions.js
  packages/api/models/granules.js
  packages/api/models/pdrs.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-write-granules.js
Labels: pr feedback

#2254 [CUMULUS-2532] Delete granules before collections and providers
  CHANGELOG.md
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  example/spec/parallel/dbRecords/DbRecordsDLQSpec.js
  example/spec/parallel/dbRecords/DeadLetterArchiveProcessingSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesDuplicateHandlingErrorSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesDuplicateHandlingSkipSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesHttpsSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesS3FailureSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesS3SuccessSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesWithExecutionNamePrefixSpec.js
  example/spec/parallel/ingest/ingestFromPdrSpec.js
  example/spec/parallel/ingest/ingestFromPdrWithChildWorkflowMetaSpec.js
  example/spec/parallel/ingest/ingestFromPdrWithExecutionNamePrefixSpec.js
  example/spec/parallel/ingest/ingestPdrWithNodeNameSpec.js
  example/spec/parallel/ingestGranule/IngestElevenGiBFileSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleFailureSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleFtpSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleWithDuplicateHandlingErrorSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleWithDuplicateHandlingVersionSpec.js
  example/spec/parallel/ingestGranule/IngestUMMGSuccessSpec.js
  example/spec/parallel/ingestGranule/ingestGranuleQueueSpec.js
  example/spec/parallel/kinesisTests/KinesisTestTriggerSpec.js
  example/spec/parallel/orca/OrcaBackupAndRecoverySpec.js
  example/spec/parallel/syncGranule/SyncGranuleCopyTagsSpec.js
  example/spec/parallel/syncGranule/SyncGranuleDuplicateHandlingSpec.js
  example/spec/parallel/syncGranule/SyncGranuleSuccessSpec.js
  example/spec/parallel/testAPI/bulkOperationsSuccessSpec.js
  example/spec/parallel/testAPI/sqsRuleSpec.js
  example/spec/serial/DiscoverGranulesHttpSpec.js
  packages/api/endpoints/collections.js
  packages/api/endpoints/pdrs.js
  packages/api/endpoints/providers.js
  packages/api/src/lib/granule-delete.ts
  packages/api/tests/endpoints/providers/delete-provider.js
Labels: in review

#2277 Small typo
  docs/deployment/README.md#cumulus-instance-sizing
Labels: User Contribution

#2290 [User-Contribution] Small typo (#2277)
  docs/deployment/README.md#cumulus-instance-sizing
Labels: User Contribution

#2282 [CUMULUS-2475][CUMULUS-2476] GET and HEAD endpoints
  CHANGELOG.md
  packages/api/endpoints/distribution.js
  packages/api/lib/distribution.js
  packages/api/package.json
  packages/api/tests/endpoints/test-distribution.js
  packages/aws-client/src/S3ObjectStore.ts
  packages/aws-client/src/client.ts
  packages/aws-client/tests/test-S3ObjectStore.js
  packages/object-store/package.json
  tf-modules/cumulus_distribution/api.tf
  tf-modules/cumulus_distribution/iam.tf
Labels: in review

#2286 CUMULUS-2478: Implement bucket map and /locate
  CHANGELOG.md
  example/cumulus-tf/cumulus_distribution.tf
  example/cumulus-tf/cumulus_distribution/bucket_map.yaml.example
  example/cumulus-tf/cumulus_distribution/bucket_map.yaml.tmpl
  example/cumulus-tf/cumulus_distribution/bucket_map.yaml.tmpl.example
  example/deployments/cumulus/jl-tf.tfvars
  example/spec/parallel/ingestGranule/IngestGranuleWithDuplicateHandlingErrorSpec.js
  packages/api/app/distribution-routes.js
  packages/api/endpoints/distribution.js
  packages/api/lib/bucketMapUtils.js
  packages/api/lib/distribution.js
  packages/api/package.json
  packages/api/tests/endpoints/test-distribution-earthdata.js
  packages/api/tests/endpoints/test-distribution.js
  packages/api/tests/lib/test-bucketMapUtils.js
  packages/common/package.json
  packages/integration-tests/Executions.js
  packages/integration-tests/Granules.js
  packages/s3-credentials-endpoint/index.js
  tf-modules/cumulus_distribution/api.tf
  tf-modules/cumulus_distribution/iam.tf
  tf-modules/cumulus_distribution/main.tf
  tf-modules/cumulus_distribution/variables.tf
Labels: in review

#2306 CUMULUS-2487- cumulus_distribution api Integration testing
  CHANGELOG.md
  example/spec/parallel/distributionAPI/distributionApiSpec.js
  packages/integration-tests/api/EarthdataLogin.js
  packages/integration-tests/api/distribution.js
Labels: in review

#2318 Fix sqsRuleSpec/ IngestFailureSpec -- fix-API-error-test-failures
  example/spec/parallel/ingestGranule/IngestGranuleFailureSpec.js
  example/spec/parallel/testAPI/sqsRuleSpec.js
  packages/api-client/src/granules.ts
Labels: needs review

#2319 Update api-client test to include expected pRetryOptions
  packages/api-client/tests/test-granules.js
Labels: needs review
