Repository nasa/cumulus, pull requests merged in 2021-08, with the labels that each got.

#2383 [CUMULUS-2591] Increase Lambda/ECS execution failure visibility.
  CHANGELOG.md
  example/spec/parallel/ingestGranule/IngestGranuleFailureSpec.js
  packages/api/lambdas/sf-event-sqs-to-db-records/index.js
  packages/api/lib/cwSfExecutionEventUtils.js
  packages/api/lib/utils.js
  packages/api/tests/lib/test-cwSfExecutionEventUtils.js
Labels: pr feedback

#2399 CUMULUS-2304: Fix execution writes
  CHANGELOG.md
  example/spec/parallel/ingestGranule/ingestGranuleQueueSpec.js
  example/spec/parallel/testAPI/snsRuleSpec.js
  packages/api/lambdas/sf-event-sqs-to-db-records/write-execution.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-write-execution.js
  packages/es-client/indexer.js
  packages/message/src/workflows.ts
  packages/message/tests/test-workflows.js
Labels: needs review

#2397 Update deployment docs
  docs/deployment/README.md
Labels: needs review

#2355 remove db-migration-tf module
  bamboo/bootstrap-tf-deployment.sh
  example/db-migration-tf/main.tf
  example/db-migration-tf/terraform.tf.example
  example/db-migration-tf/terraform.tfvars.example
  example/db-migration-tf/variables.tf
  example/db-migration-tf/versions.tf
Labels: low priority

#2406 CUMULUS-2630 CORS failures on dashboard
  CHANGELOG.md
  example/cumulus-tf/variables.tf
  packages/api/lambdas/sf-event-sqs-to-db-records/index.js
Labels: low priority, Very Small

#2409 [CUMULUS-2592] Increase Queue Visibility
  CHANGELOG.md
  packages/api/lambdas/bulk-operation.js
  packages/api/lambdas/sqs-message-consumer.js
  packages/aws-client/src/Lambda.ts
  packages/aws-client/src/SQS.ts
  packages/aws-client/tests/test-SQS.js
Labels: pr feedback

#2421 fix CHANGELOG merge
  CHANGELOG.md
Labels: in review

#2371 Fix dead letter processing
  CHANGELOG.md
  example/cumulus-tf/variables.tf
  example/spec/parallel/dbRecords/DeadLetterArchiveProcessingSpec.js
  example/spec/parallel/testAPI/bulkDeleteFailureSpec.js
  example/spec/parallel/testAPI/bulkDeleteSuccessSpec.js
  example/spec/parallel/testAPI/bulkOperationsSuccessSpec.js
  packages/api-client/src/asyncOperations.ts
  packages/api-client/tests/test-asyncOperations.js
  packages/api/ecs/async-operation/index.js
  packages/api/ecs/async-operation/package.json
  packages/api/ecs/async-operation/tests/test-index.js
  packages/api/lambdas/process-s3-dead-letter-archive.js
  packages/api/tests/lambdas/test-process-s3-dead-letter-archive.js
  packages/db/package.json
  packages/db/tests/models/test-async-operation-model.js
  packages/integration-tests/index.js
  tf-modules/archive/process_dead_letter_archive.tf
  tf-modules/cumulus/variables.tf
Labels: pr feedback
