Repository nasa/cumulus, pull requests merged in 2021-12, with the labels that each got.

#2587 CUMULUS-2661: Update executions PUT endpoint to send SNS message
  CHANGELOG.md
  example/spec/parallel/testAPI/executionSpec.js
  packages/api/endpoints/executions.js
  packages/api/lib/publishSnsMessageUtils.js
  packages/api/tests/endpoints/test-executions.js
  packages/es-client/tests/test-execution-upsert.js
Labels: pr feedback

#2590 Jk/cumulus 2759
  CHANGELOG.md
  packages/api/endpoints/collections.js
  packages/api/endpoints/granules.js
  packages/api/endpoints/providers.js
  packages/api/endpoints/rules.js
  packages/api/tests/endpoints/collections/create-collection.js
  packages/api/tests/endpoints/providers/create-provider.js
  packages/api/tests/endpoints/test-granules.js
  packages/api/tests/endpoints/test-rules.js
  packages/db/src/index.ts
  packages/db/src/lib/errors.ts
  packages/db/tests/lib/test-errors.js
Labels: pr feedback

#2570 CUMULUS-2684:configure an optional collection level parameter s3MultipartChunksizeMb
  CHANGELOG.md
  example/cumulus-tf/cookbook_browse_example_workflow.asl.json
  example/cumulus-tf/ingest_and_publish_granule_with_orca_workflow.asl.json
  example/cumulus-tf/ingest_and_publish_granule_workflow.asl.json
  example/cumulus-tf/ingest_granule_with_queue_workflow.asl.json
  example/cumulus-tf/kinesis_trigger_test_workflow.asl.json
  example/cumulus-tf/main.tf
  example/cumulus-tf/python_processing_workflow.asl.json
  example/cumulus-tf/variables.tf
  example/data/collections/s3_MOD09GQ_006-umm/s3_MOD09GQ_006.json
  example/data/collections/s3_MOD09GQ_006/s3_MOD09GQ_006.json
  example/data/collections/s3_MOD09GQ_006_full_ingest/s3_MOD09GQ_006.json
  example/data/collections/s3_MOD09GQ_006_no_cmr/s3_MOD09GQ_006.json
  example/data/collections/s3_MOD09GQ_006_orca/s3_MOD09GQ_006.json
  example/deployments/cumulus/sandbox.tfvars
  packages/api/models/schemas.js
  tasks/move-granules/README.md
  tasks/move-granules/index.js
  tasks/move-granules/schemas/config.json
  tasks/move-granules/tests/test-index.js
Labels: pr feedback

#2604 [CUMULUS-2747] Add fields to provider config docs
  CHANGELOG.md
  docs/configuration/data-management-types.md
Labels: needs review

#2606 Remove api model code from queueGranuleSpec
  CHANGELOG.md
  example/spec/helpers/apiUtils.js
  example/spec/parallel/queueGranules/QueueGranulesSpec.js
Labels: in review

#2599 Example deployment updates/improvements
  CHANGELOG.md
  example/cumulus-tf/cumulus_distribution.tf
  example/cumulus-tf/main.tf
  example/cumulus-tf/thin_egress_app.tf
  example/cumulus-tf/variables.tf
  example/cumulus-tf/vpc.tf
  example/data-persistence-tf/main.tf
  example/data-persistence-tf/variables.tf
  example/data-persistence-tf/vpc.tf
  example/rds-cluster-tf/main.tf
  example/rds-cluster-tf/variables.tf
  example/rds-cluster-tf/vpc.tf
  lambdas/db-provision-user-database/main.tf
Labels: pr feedback, low priority

#2607 CUMULUS-2775: Fix api-client logs
  CHANGELOG.md
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  packages/api-client/src/cumulusApiClient.ts
  packages/api-client/src/deadLetterArchive.ts
  packages/api-client/src/executions.ts
  packages/api-client/src/granules.ts
  packages/api-client/src/migrationCounts.ts
  packages/api-client/src/reconciliationReports.ts
  packages/api-client/src/replays.ts
  packages/api-client/src/types.ts
  packages/api-client/tests/test-CumulusApiClient.js
  packages/api-client/tests/test-deadLetterArchive.js
  packages/api-client/tests/test-executions.js
  packages/api-client/tests/test-granules.js
  packages/api-client/tests/test-replays.js
Labels: needs review
