Repository nasa/cumulus, pull requests merged in 2021-07, with the labels that each got.

#2327 Misc lint/comment updates
  example/spec/helpers/Collections.js
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesHttpsSpec.js
Labels: low priority

#2328 Fix ingest granule success spec
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
Labels: in review

#2334 Integration tests fix
  example/spec/parallel/discoverGranules/DiscoverGranulesS3SuccessSpec.js
  example/spec/serial/DiscoverGranulesHttpSpec.js
Labels: pr feedback

#2341 Update buildAndExecuteWorkflow to use API, update spec to use new helper
  example/spec/helpers/workflowUtils.js
  example/spec/loadTest/runScaledTest.js
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesHttpsSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesS3FailureSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesS3SuccessSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesWithExecutionNamePrefixSpec.js
  example/spec/parallel/helloWorld/HelloWorldEcsSpec.js
  example/spec/parallel/ingest/ingestFromPdrSpec.js
  example/spec/parallel/ingest/ingestFromPdrWithChildWorkflowMetaSpec.js
  example/spec/parallel/ingest/ingestFromPdrWithExecutionNamePrefixSpec.js
  example/spec/parallel/ingest/ingestPdrWithNodeNameSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleFailureSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleFtpSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestGranulePythonProcessingSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestUMMGSuccessSpec.js
  example/spec/parallel/ingestGranule/ingestGranuleQueueSpec.js
  example/spec/parallel/orca/OrcaBackupAndRecoverySpec.js
  example/spec/parallel/pythonReferenceTests/PythonReferenceSpec.js
  example/spec/parallel/retryConfiguration/retryConfigurationSpec.js
  example/spec/parallel/syncGranule/SyncGranuleDuplicateHandlingSpec.js
  example/spec/parallel/syncGranule/SyncGranuleSuccessSpec.js
  example/spec/serial/DiscoverGranulesHttpSpec.js
  example/spec/standalone/redeployment/LambdaRedeploySpec.js
  example/spec/standalone/redeployment/WorkflowRedeploySpec.js
  packages/integration-tests/index.js
Labels: needs review

#2337 fix cleanup of sync granule tests & remove PDR from test fixtures
  example/spec/helpers/granuleUtils.js
  example/spec/parallel/syncGranule/SyncGranule.input.payload.json
  example/spec/parallel/syncGranule/SyncGranuleDuplicateHandling.input.payload.json
  example/spec/parallel/syncGranule/SyncGranuleDuplicateHandlingSpec.js
  example/spec/parallel/syncGranule/SyncGranuleSuccessSpec.js
Labels: needs review

#2344 Add username to archive_api_users
  example/cumulus-tf/main.tf
Labels: needs review

#2345 randomize granuleId for discover granule tests
  example/spec/helpers/discoverUtils.js
  example/spec/parallel/discoverGranules/DiscoverGranulesS3SuccessSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesWithExecutionNamePrefixSpec.js
  example/spec/parallel/ingest/ingestFromPdrSpec.js
Labels: needs review

#2346 ensure test uses a unique granule ID
  example/spec/helpers/testUtils.js
  example/spec/parallel/ingest/ingestPdrWithNodeNameSpec.js
Labels: needs review

#2348 Fix timeout and error log
  packages/api/models/granules.js
  tf-modules/archive/sf_event_sqs_to_db_records.tf
Labels: needs review

#2322 CUMULUS-2569: create bucket map cache for cumulus distribution api
  CHANGELOG.md
  example/cumulus-tf/cumulus_distribution/bucket_map.yaml.tmpl
  example/spec/parallel/distributionAPI/distributionApiSpec.js
  example/spec/parallel/distributionAPI/distributionTEASpec.js
  packages/api/app/distribution.js
  packages/api/endpoints/distribution.js
  packages/api/lib/bucketMapUtils.js
  packages/api/tests/endpoints/test-distribution.js
  tf-modules/cumulus_distribution/api.tf
  tf-modules/cumulus_distribution/iam.tf
  tf-modules/cumulus_distribution/main.tf
  tf-modules/cumulus_distribution/outputs.tf
Labels: pr feedback

#2369 Fix cmr_custom_host integration
  CHANGELOG.md
  example/cumulus-tf/main.tf
  example/cumulus-tf/variables.tf
  lambdas/sqs-message-remover/variables.tf
  tf-modules/archive/variables.tf
  tf-modules/cumulus/archive.tf
  tf-modules/cumulus/ingest.tf
  tf-modules/cumulus/variables.tf
  tf-modules/ingest/sqs-message-remover.tf
  tf-modules/ingest/variables.tf
Labels: User Contribution

#2368 Lpf/release doc update
  docs/development/release.md
Labels: pr feedback

#2268 Update the nightly cleanup job to cleanup S3
  tf-modules/internal/cumulus-test-cleanup/cleanups3.js
  tf-modules/internal/cumulus-test-cleanup/iam.tf
  tf-modules/internal/cumulus-test-cleanup/index.js
  tf-modules/internal/cumulus-test-cleanup/main.tf
Labels: pr feedback

#2377 Allow custom cmr protocol
  CHANGELOG.md
  example/cumulus-tf/variables.tf
  lambdas/sqs-message-remover/variables.tf
  packages/cmr-client/src/getUrl.ts
  packages/cmr-client/tests/test-getUrl.js
  tf-modules/archive/variables.tf
  tf-modules/cumulus/variables.tf
  tf-modules/ingest/variables.tf
Labels: User Contribution

#2353 Add documentation for deploying Cumulus Distribution
  CHANGELOG.md
  docs/deployment/README.md
  docs/deployment/components.md
  docs/deployment/cumulus-distribution.md
  docs/upgrade-notes/cumulus-distribution.md
  example/cumulus-tf/main.tf
  example/cumulus-tf/terraform.tfvars.example
  example/cumulus-tf/variables.tf
  tf-modules/cumulus/distribution.tf
  tf-modules/cumulus/outputs.tf
  tf-modules/cumulus/variables.tf
  tf-modules/cumulus_distribution/iam.tf
Labels: needs review

#2387 Integration test fixes
  example/spec/helpers/discoverUtils.js
  example/spec/parallel/dbRecords/DeadLetterArchiveProcessingSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesS3SuccessSpec.js
Labels: pr feedback

#2376 [CUMULUS-2460] /executions/workflows-by-granules
  CHANGELOG.md
  packages/api-client/src/executions.ts
  packages/api-client/tests/test-executions.js
  packages/api/endpoints/executions.js
  packages/api/tests/endpoints/test-executions.js
  packages/db/src/index.ts
  packages/db/src/lib/execution.ts
  packages/db/src/lib/granule.ts
  packages/db/src/lib/sort.ts
  packages/db/src/models/execution.ts
  packages/db/tests/lib/test-execution.js
  packages/db/tests/models/test-execution-model.js
Labels: in review
