Repository nasa/cumulus, pull requests merged in 2021-09, with the labels that each got.

#2437 CUMULUS-2644: Move migrations from db-migration-lambda to db
  bin/db-local-migrate.js
  bin/db-local-rollback.js
  lambdas/data-migration1/tests/test-async-operations.js
  lambdas/data-migration1/tests/test-collections.js
  lambdas/data-migration1/tests/test-index.js
  lambdas/data-migration1/tests/test-providers.js
  lambdas/data-migration1/tests/test-rules.js
  lambdas/data-migration2/tests/test-executions.js
  lambdas/data-migration2/tests/test-granulesAndFiles.js
  lambdas/data-migration2/tests/test-index.js
  lambdas/data-migration2/tests/test-pdrs.js
  lambdas/db-migration/package.json
  lambdas/db-migration/src/index.ts
  packages/api/ecs/async-operation/tests/test-index.js
  packages/api/tests/endpoints/collections/create-collection.js
  packages/api/tests/endpoints/collections/delete-collection.js
  packages/api/tests/endpoints/collections/update-collection.js
  packages/api/tests/endpoints/providers/create-provider.js
  packages/api/tests/endpoints/providers/delete-provider.js
  packages/api/tests/endpoints/providers/update-provider.js
  packages/api/tests/endpoints/test-elasticsearch.js
  packages/api/tests/endpoints/test-endpoints-async-operations.js
  packages/api/tests/endpoints/test-executions.js
  packages/api/tests/endpoints/test-granules.js
  packages/api/tests/endpoints/test-pdrs.js
  packages/api/tests/endpoints/test-rules.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-index.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-utils.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-write-granules.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-write-pdr.js
  packages/api/tests/lambdas/test-bulk-granule-delete.js
  packages/api/tests/lambdas/test-bulk-operation.js
  packages/api/tests/lib/test-granule-delete.js
  packages/api/tests/lib/test-granule-remove-from-cmr.js
  packages/api/tests/lib/writeRecords/test-write-execution.js
  packages/async-operations/tests/test-async_operations.js
  packages/db/src/index.ts
  packages/db/src/migrations/20201014104958_create_collections_table.ts
  packages/db/src/migrations/20201014105016_create_providers_table.ts
  packages/db/src/migrations/20201014105024_create_rules_table.ts
  packages/db/src/migrations/20201014105030_create_async_operations_table.ts
  packages/db/src/migrations/20201014105045_create_executions_table.ts
  packages/db/src/migrations/20201014105054_create_pdrs_table.ts
  packages/db/src/migrations/20201014105058_create_granules_table.ts
  packages/db/src/migrations/20201014105102_create_files_table.ts
  packages/db/src/migrations/20210211172119_create_granules_executions_table.ts
  packages/db/src/migrations/20210715171725_provider_add_allowed_redirects.ts
  packages/db/src/migrations/20210727104740_alter_async_operations_table_operation_type.ts
  packages/db/tests/lib/test-execution.js
  packages/db/tests/lib/test-granule.js
  packages/db/tests/models/test-async-operation-model.js
  packages/db/tests/models/test-collection-model.js
  packages/db/tests/models/test-execution-model.js
  packages/db/tests/models/test-file-model.js
  packages/db/tests/models/test-granule-model.js
  packages/db/tests/models/test-granules-executions-model.js
  packages/db/tests/models/test-pdr-model.js
  packages/db/tests/models/test-provider-model.js
  packages/db/tests/models/test-rule-model.js
  packages/ingest/test/test-granule.js
Labels: in review

#2447 CUMULUS-2606: associate an execution with a granule via API
  CHANGELOG.md
  example/spec/parallel/testAPI/granuleSpec.js
  packages/api-client/src/granules.ts
  packages/api-client/tests/test-granules.js
  packages/api/endpoints/granules.js
  packages/api/tests/endpoints/test-granules.js
Labels: in review

#2450 CUMULUS-2602-2: Update associateExecutionWithGranule path to PUT /granules/:granuleId/executions
  CHANGELOG.md
  packages/api-client/src/granules.ts
  packages/api-client/tests/test-granules.js
  packages/api/endpoints/granules.js
  packages/api/tests/endpoints/test-granules.js
Labels: needs review

#2442 CUMULUS-2582/2583
  .eslintrc.js
  CHANGELOG.md
  example/spec/helpers/granuleUtils.js
  example/spec/parallel/discoverGranules/DiscoverGranulesHttpsSpec.js
  packages/api-client/tests/test-granules.js
  packages/api/endpoints/granules.js
  packages/api/lib/writeRecords/write-granules.js
  packages/api/models/granules.js
  packages/api/models/schemas.js
  packages/api/tests/endpoints/test-granules.js
  packages/db/knexfile.js
  packages/db/src/migration-template.ts
  packages/db/src/migrations/20210909133428_queued_granule_status.ts
  packages/db/tsconfig.json
  packages/types/api/granules.d.ts
  tasks/queue-granules/index.js
  tasks/queue-granules/tests/index.js
Labels: needs review

#2453 CUMULUS-2000
  CHANGELOG.md
  docs/workflow_tasks/queue_granules.md
  example/cumulus-tf/discover_granules_workflow.asl.json
  example/cumulus-tf/parse_pdr_workflow.asl.json
  example/spec/helpers/Collections.js
  example/spec/helpers/Providers.js
  example/spec/helpers/granuleUtils.js
  example/spec/parallel/multiQueue/DiscoverGranulesMultiQueueSpec.js
  example/spec/parallel/testAPI/granuleSpec.js
  example/spec/serial/multiQueue/ParsePdrBatchQueueSpec.js
  lambdas/data-migration2/tests/test-granulesAndFiles.js
  lambdas/data-migration2/tests/test-storeErrors.js
  packages/db/src/test-utils.ts
  packages/ingest/src/queue.js
  packages/ingest/test/test-queue.js
  packages/integration-tests/Collections.js
  tasks/queue-granules/index.js
  tasks/queue-granules/schemas/config.json
  tasks/queue-granules/tests/index.js
  website/sidebars.json
Labels: pr feedback, current sprint, high priority

#2467 Update concurrency
  CHANGELOG.md
  example/cumulus-tf/variables.tf
  tf-modules/cumulus/variables.tf
Labels: low priority, Very Small

#2460 CUMULUS-2676: control concurrency for DiscoverGranules duplicate checking
  CHANGELOG.md
  docs/workflow_tasks/discover_granules.md
  docs/workflow_tasks/queue_granules.md
  tasks/discover-granules/index.js
  tasks/discover-granules/package.json
  tasks/discover-granules/schemas/config.json
  tasks/discover-granules/tests/index.js
Labels: pr feedback, Very Small

#2449 [CUMULUS-2510] Publish SNS messages for PDRs
  CHANGELOG.md
  packages/api/endpoints/collections.js
  packages/api/lambdas/sf-event-sqs-to-db-records/write-pdr.js
  packages/api/lib/publishSnsMessageUtils.js
  packages/api/lib/writeRecords/write-execution.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-index.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-write-pdr.js
  packages/api/tests/lib/test-publishSnsMessageUtils.js
  packages/api/tests/lib/writeRecords/test-write-execution.js
  packages/db/src/models/base.ts
  packages/db/src/models/pdr.ts
  tf-modules/archive/process_dead_letter_archive.tf
  tf-modules/archive/sf_event_sqs_to_db_records.tf
  tf-modules/cumulus/ecs_cluster.tf
Labels: pr feedback
