Repository nasa/cumulus, pull requests merged in 2022-01, with the labels that each got.

#2576 CUMULUS-2753:Update cumulus/example to install the latest ORCA release
  CHANGELOG.md
  bamboo/bootstrap-tf-deployment.sh
  bamboo/set-bamboo-env-variables.sh
  docs/workflows/workflow-configuration-how-to.md
  example/cumulus-tf/ingest_and_publish_granule_with_orca_workflow.asl.json
  example/cumulus-tf/orca.tf
  example/cumulus-tf/terraform.tfvars.example
  example/cumulus-tf/variables.tf
  example/data/collections/s3_MOD09GQ_006_full_ingest/s3_MOD09GQ_006.json
  example/data/collections/s3_MOD09GQ_006_orca/s3_MOD09GQ_006.json
  example/deployments/cumulus/cumulus-sit.tfvars
  example/deployments/cumulus/cumulus-source-tf.tfvars
  example/deployments/cumulus/jl-tf.tfvars
  example/deployments/cumulus/jtran-int-tf.tfvars
  example/deployments/cumulus/kk2-tf.tfvars
  example/deployments/cumulus/lf-test-tf.tfvars
  example/deployments/cumulus/mboyd-int-tf.tfvars
  example/deployments/cumulus/mvd-tf.tfvars
  example/deployments/cumulus/sandbox.tfvars
  example/deployments/cumulus/sit.tfvars
  example/spec/parallel/orca/OrcaBackupAndRecoverySpec.js
  packages/api/endpoints/orca.js
  packages/api/lib/orca.js
  packages/api/tests/lib/test-orca.js
Labels: in review

#2611 Eliminate deprecation warnings generated from Launchpad package
  CHANGELOG.md
  packages/aws-client/src/S3.ts
  packages/launchpad-auth/src/LaunchpadToken.ts
  packages/launchpad-auth/src/index.ts
  packages/launchpad-auth/tests/test-LaunchpadToken.js
Labels: User Contribution

#2638 Fixed the wrong link to the eslintrc
  docs/development/quality-and-coverage.md
Labels: pr feedback, needs review, User Contribution

#2614 CUMULUS-1985: creating rule with no name returns 400
  packages/api/tests/endpoints/test-rules.js
Labels: pr feedback

#2667 npm/audit -- Remove unneeded dependency
  package.json
Labels: in review

#2663 CUMULUS-2456: Connect to ORCA Private API
  CHANGELOG.md
  example/cumulus-tf/main.tf
  example/cumulus-tf/orca.tf
  example/spec/parallel/orca/OrcaBackupAndRecoverySpec.js
  packages/api-client/src/orca.ts
  packages/api/endpoints/orca.js
  packages/api/lib/orca.js
  packages/api/tests/lib/test-orca.js
  tf-modules/archive/api.tf
  tf-modules/archive/variables.tf
  tf-modules/cumulus/archive.tf
  tf-modules/cumulus/variables.tf
Labels: needs review

#2666 [CUMULUS-2835] hyrax-metadata-updates: better support for ECHO10 XML
  CHANGELOG.md
  tasks/hyrax-metadata-updates/index.js
  tasks/hyrax-metadata-updates/tests/data/echo10-dataset_id-in.xml
  tasks/hyrax-metadata-updates/tests/data/umm-g-entry-title-in.json
  tasks/hyrax-metadata-updates/tests/test-index.js
  tasks/hyrax-metadata-updates/tests/test-integration-index.js
  tasks/hyrax-metadata-updates/tests/test-search-failures.js
Labels: needs review, User Contribution

#2677 Fix Misspellings across Cumulus
  CHANGELOG.md
  docs/data-cookbooks/about-cookbooks.md
  docs/data-cookbooks/queue-post-to-cmr.md
  docs/features/reports.md
  docs/upgrade-notes/upgrading-tf-version-0.13.6.md
  docs/workflows/docker.md
  example/README.md
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  packages/api/lambdas/create-reconciliation-report.js
  packages/api/tests/lambdas/test-create-reconciliation-report.js
  packages/db/src/models/execution.ts
  packages/ingest/README.md
  packages/integration-tests/api/executions.js
  tf-modules/README.md
  website/versioned_docs/version-1.11.0/data-cookbooks/setup.md
  website/versioned_docs/version-1.11.0/upgrade/1.9.0.md
  website/versioned_docs/version-1.12.0/data-cookbooks/setup.md
  website/versioned_docs/version-1.15.0/data-cookbooks/hello-world.md
  website/versioned_docs/version-1.15.0/data-cookbooks/setup.md
  website/versioned_docs/version-1.15.0/deployment/config_descriptions.md
  website/versioned_docs/version-v1.10.1/data-cookbooks/hello-world.md
  website/versioned_docs/version-v1.10.1/data-cookbooks/setup.md
  website/versioned_docs/version-v1.10.1/data-cookbooks/sips-workflow.md
  website/versioned_docs/version-v1.10.1/data-cookbooks/sns.md
  website/versioned_docs/version-v1.10.1/upgrade/1.9.0.md
  website/versioned_docs/version-v1.10.1/workflows/docker.md
  website/versioned_docs/version-v1.10.3/data-cookbooks/hello-world.md
  website/versioned_docs/version-v1.10.3/data-cookbooks/sips-workflow.md
  website/versioned_docs/version-v1.10.3/workflows/docker.md
  website/versioned_docs/version-v1.13.0/data-cookbooks/setup.md
  website/versioned_docs/version-v1.13.0/data-cookbooks/sns.md
  website/versioned_docs/version-v1.14.0/data-cookbooks/setup.md
  website/versioned_docs/version-v1.14.0/data-cookbooks/sips-workflow.md
  website/versioned_docs/version-v1.14.0/data-cookbooks/sns.md
  website/versioned_docs/version-v1.14.0/deployment/config_descriptions.md
  website/versioned_docs/version-v1.14.2/data-cookbooks/hello-world.md
  website/versioned_docs/version-v1.14.2/data-cookbooks/sns.md
  website/versioned_docs/version-v1.16.0/data-cookbooks/hello-world.md
  website/versioned_docs/version-v1.16.0/data-cookbooks/setup.md
  website/versioned_docs/version-v1.16.0/data-cookbooks/sips-workflow.md
  website/versioned_docs/version-v1.16.0/workflows/docker.md
  website/versioned_docs/version-v1.16.1/data-cookbooks/setup.md
  website/versioned_docs/version-v1.16.1/workflows/docker.md
  website/versioned_docs/version-v1.21.0/data-cookbooks/setup.md
  website/versioned_docs/version-v1.22.0/data-cookbooks/setup.md
  website/versioned_docs/version-v1.24.0/data-cookbooks/setup.md
  website/versioned_docs/version-v2.0.0/data-cookbooks/setup.md
  website/versioned_docs/version-v3.0.0/features/inventory-reports.md
  website/versioned_docs/version-v3.0.0/workflows/docker.md
  website/versioned_docs/version-v5.0.0/data-cookbooks/about-cookbooks.md
  website/versioned_docs/version-v5.0.0/features/reports.md
  website/versioned_docs/version-v6.0.0/upgrade-notes/upgrading-tf-version-0.13.6.md
  website/versioned_docs/version-v8.0.0/data-cookbooks/queue-post-to-cmr.md
  website/versioned_docs/version-v8.1.0/data-cookbooks/queue-post-to-cmr.md
Labels: in review, User Contribution

#2678 From/nsidc/cumulus 2835
  CHANGELOG.md
  tasks/hyrax-metadata-updates/index.js
  tasks/hyrax-metadata-updates/tests/data/echo10-dataset_id-in.xml
  tasks/hyrax-metadata-updates/tests/data/umm-g-entry-title-in.json
  tasks/hyrax-metadata-updates/tests/test-index.js
  tasks/hyrax-metadata-updates/tests/test-integration-index.js
  tasks/hyrax-metadata-updates/tests/test-search-failures.js
Labels: pr feedback

#2653 Cumulus 2783
  CHANGELOG.md
  docs/data-cookbooks/run-tasks-in-lambda-or-docker.md
  example/cumulus-tf/ecs_hello_world_workflow.tf
  example/cumulus-tf/python_processing_workflow.tf
  example/cumulus-tf/python_reference_workflow.tf
  example/spec/helpers/ecsHelpers.js
  example/spec/serial/AsyncOperationRunnerFailingLambdaSpec.js
  example/spec/serial/AsyncOperationRunnerNonExistentLambdaSpec.js
  example/spec/serial/AsyncOperationRunnerNonExistentPayloadSpec.js
  example/spec/serial/AsyncOperationRunnerNonJsonPayloadSpec.js
  example/spec/serial/AsyncOperationRunnerSuccessfulLambdaSpec.js
  lambdas/postgres-migration-async-operation/src/index.ts
  lambdas/postgres-migration-async-operation/tests/test-index.js
  packages/api/app/routes.js
  packages/api/endpoints/dead-letter-archive.js
  packages/api/endpoints/elasticsearch.js
  packages/api/endpoints/granules.js
  packages/api/endpoints/migrationCounts.js
  packages/api/endpoints/reconciliation-reports.js
  packages/api/endpoints/replays.js
  packages/api/lib/request.js
  packages/api/tests/endpoints/granules/test-bulk-delete.js
  packages/api/tests/endpoints/granules/test-bulk-granules.js
  packages/api/tests/endpoints/granules/test-bulk-reingest.js
  packages/api/tests/endpoints/test-dead-letter-archive.js
  packages/api/tests/endpoints/test-elasticsearch.js
  packages/api/tests/endpoints/test-migration-counts.js
  packages/api/tests/endpoints/test-reconciliation-reports.js
  packages/api/tests/endpoints/test-replays.js
  packages/api/tests/endpoints/utils.js
  packages/api/tests/lib/test-request.js
  packages/async-operations/src/async_operations.ts
  packages/async-operations/src/index.ts
  packages/async-operations/tests/test-async_operations.js
  packages/errors/src/index.ts
  tf-modules/archive/async_operation.tf
  tf-modules/archive/iam.tf
  tf-modules/archive/main.tf
  tf-modules/cumulus/ecs_cluster.tf
Labels: pr feedback

#2681 Need a deep copy of repo to compare changelog against main's
  CHANGELOG.md
  bamboo/bootstrap-lint-audit.sh
Labels: needs review, low priority, Very Small
