Repository nasa/cumulus, pull requests merged in 2022-03, with the labels that each got.

#2726 Adds logs surrounding the preparation and launch of asynchronous operations
  CHANGELOG.md
  example/cumulus-tf/variables.tf
  packages/api/ecs/async-operation/index.js
  tf-modules/cumulus/variables.tf
Labels: low priority

#2878 2812: Fix rule disabling logic
  example/spec/parallel/testAPI/snsRuleSpec.js
  packages/api/lib/rulesHelpers.js
  packages/api/lib/testUtils.js
  packages/api/tests/endpoints/test-rules.js
  packages/api/tests/lib/rules/test-updateRuleResources.js
Labels: in review

#2872 PUT endpoints - Add unit tests to ensure fields can be deleted
  packages/api/tests/endpoints/collections/update-collection.js
  packages/api/tests/endpoints/providers/update-provider.js
Labels: low priority, Very Small

#2877 Fix local api and get execution response
  CHANGELOG.md
  packages/api/bin/serve.js
  packages/api/endpoints/execution-status.js
  packages/api/tests/endpoints/test-execution-status.js
Labels: in review

#2870 [CUMULUS-2841] forward port of : add integration test (#2729)
  CHANGELOG.md
  example/cumulus-tf/iam.tf
  example/cumulus-tf/lambdas.tf
  example/cumulus-tf/variables.tf
  example/lambdas/ftpPopulateTestLambda/granules/MOD09GQ.A2016358.h13v04.006.2016360104606.hdf
  example/lambdas/ftpPopulateTestLambda/granules/MOD09GQ.A2016358.h13v04.006.2016360104606.hdf.met
  example/lambdas/ftpPopulateTestLambda/granules/MOD09GQ.A2016358.h13v04.006.2016360104606_ndvi.jpg
  example/lambdas/ftpPopulateTestLambda/index.js
  example/lambdas/ftpPopulateTestLambda/package.json
  example/lambdas/ftpPopulateTestLambda/webpack.config.js
  example/spec/helpers/Providers.js
  example/spec/serial/ingestPdrWithNodeNameFtpSpec.js
  packages/common/package.json
  packages/common/src/fake-provider.ts
  packages/common/src/index.ts
Labels: pr feedback, needs review

#2887 Update postgres migration lambda timeout/make timeout configurable
  CHANGELOG.md
  lambdas/db-migration/main.tf
  lambdas/db-migration/variables.tf
  tf-modules/data-persistence/postgres_migration.tf
  tf-modules/data-persistence/variables.tf
Labels: in review

#2898 Mhs/cumulus 2877/granule timestamps bugfix
  .markdownlint.json
  CHANGELOG.md
  audit-ci.json
  docs/configuration/data-management-types.md
  docs/deployment/README.md
  docs/development/release.md
  example/cumulus-tf/main.tf
  package.json
  packages/api/lib/writeRecords/write-granules.js
  packages/api/tests/endpoints/collections/update-collection.js
  packages/api/tests/endpoints/test-granules.js
  packages/api/tests/lib/writeRecords/test-write-granules.js
  packages/message/src/Granules.ts
Labels: release-critical

#2896 CUMULUS-2875 - Update p2 branch config/versions & release fixes
  CHANGELOG.md
  audit-ci.json
  bamboo/set-bamboo-env-variables.sh
  example/spec/parallel/ingestGranule/ingestGranuleQueueSpec.js
  example/spec/parallel/queueGranules/queueGranulesPostProcessingSpec.js
  lambdas/data-migration2/tests/test-granulesAndFiles.js
  packages/api-client/src/executions.ts
  packages/api-client/tests/test-executions.js
  packages/api/ecs/async-operation/package.json
  packages/api/lib/request.js
  packages/api/lib/writeRecords/write-granules.js
  packages/api/models/granules.js
  packages/api/package.json
  packages/api/tests/lib/writeRecords/test-write-granules.js
  packages/common/package.json
  packages/db/src/models/base.ts
  packages/db/src/models/execution.ts
  packages/db/src/models/granule.ts
  packages/db/tests/lib/test-granule.js
  packages/db/tests/models/test-base-model.js
  packages/db/tests/models/test-granule-model.js
Labels: needs review, release-critical

#2892 CUMULUS-2860:Add optional config skipMetadataValidation to hyrax-metadata-updates task
  CHANGELOG.md
  example/cumulus-tf/ingest_and_publish_granule_with_orca_workflow.asl.json
  tasks/hyrax-metadata-updates/README.md
  tasks/hyrax-metadata-updates/index.js
  tasks/hyrax-metadata-updates/schemas/config.json
  tasks/hyrax-metadata-updates/tests/test-integration-index.js
Labels: pr feedback

#2881 CUMULUS-1 Updates from snyk #2868 #2867 #2866 #2865 #2864
  packages/api/package.json
  packages/db/package.json
  tf-modules/internal/cumulus-test-cleanup/package.json
Labels: low priority
