Repository nasa/cumulus, pull requests merged in 2022-06, with the labels that each got.

#2968 CUMULUS-2929: add collection configuration to specify metadata file extension for move-granule
  CHANGELOG.md
  packages/api/models/schemas.js
  packages/message/src/utils.ts
  packages/message/tests/test-utils.js
  tasks/move-granules/index.js
  tasks/move-granules/package.json
  tasks/move-granules/schemas/config.json
  tasks/move-granules/tests/data/payload_echo10_metadata.json
  tasks/move-granules/tests/data/payload_iso_metadata.json
  tasks/move-granules/tests/test-index.js
Labels: pr feedback, in review

#2982 CUMULUS-2955 -- Modify migrations to remove update to add files index
  CHANGELOG.md
  packages/db/src/migrations/20220126172008_files_granule_id_index.ts
  packages/db/src/migrations/20220609024044_remove_files_granule_id_index.ts
Labels: high priority

#2989 CUMULUS-2967 -- Update spec helper to *not* fail if the deletion 404s
  CHANGELOG.md
  example/spec/helpers/Providers.js
  packages/api-client/src/cumulusApiClient.ts
  packages/api-client/src/providers.ts
  packages/api-client/tests/test-providers.js
Labels: needs review

#2983 CUMULUS-2959:Convert numeric granule.productVolume to string
  CHANGELOG.md
  example/spec/serial/ingestPdrWithNodeNameFtpSpec.js
  packages/api/lib/granules.js
  packages/api/tests/endpoints/granules/test-bulk-granules.js
  packages/api/tests/lib/test-granules.js
  packages/api/tests/models/granules/test-granules-model.js
  packages/es-client/tests/test-execution-upsert.js
Labels: pr feedback

#3019 Upgrade moment and node-forge packages
  example/lambdas/ftpPopulateTestLambda/package.json
  package.json
  packages/api/package.json
  packages/common/package.json
  packages/es-client/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  tf-modules/internal/cumulus-test-cleanup/package.json
Labels: needs review

#2985 [CUMULUS-2965] Tell terraform to ignore when AWS performs upgrades to the rds engine…
  CHANGELOG.md
  tf-modules/cumulus-rds-tf/main.tf
Labels: User Contribution
