Repository nasa/cumulus, pull requests merged in 2022-11, with the labels that each got.

#3142 CUMULUS-3104-2: Fixed TS compilation error caused by @aws-sdk/client-s3 3.202.0 upgrade
  CHANGELOG.md
  example/spec/parallel/discoverGranules/DiscoverGranulesDuplicateHandlingErrorSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleFailureSpec.js
  packages/aws-client/src/SQS.ts
  packages/message/src/StepFunctions.ts
Labels: pr feedback, high priority

#3123 CUMULUS-2915: Update /executions/status/executionArn endpoint to include presigned s3 URL
  CHANGELOG.md
  example/spec/parallel/ingest/ingestFromPdrSpec.js
  example/spec/parallel/ingest/ingestPdrWithNodeNameSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleFailureSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/standalone/redeployment/WorkflowRedeploySpec.js
  packages/api/endpoints/execution-status.js
  packages/api/package.json
  packages/api/tests/endpoints/test-execution-status.js
  packages/cmrjs/package.json
  packages/lzards-api-client/package.json
  packages/oauth-client/package.json
  tasks/lzards-backup/package.json
  tf-modules/archive/main.tf
  tf-modules/archive/s3_bucket_lifecycle_config.tf
Labels: pr feedback

#3134 CUMULUS-3077 Update data-migration2 to remove excess files
  CHANGELOG.md
  lambdas/data-migration2/src/granulesAndFiles.ts
  lambdas/data-migration2/tests/test-granulesAndFiles.js
  packages/api/lib/writeRecords/write-granules.js
Labels: high priority

#3150 CUMULUS-3098: Add task configuration to lzards-backup task to fail task
  CHANGELOG.md
  example/cumulus-tf/lzards_backup_fail_workflow.asl.json
  example/cumulus-tf/lzards_backup_fail_workflow.tf
  example/spec/parallel/lzardsBackup/LzardsBackupWorkflowSpec.js
  tasks/lzards-backup/README.md
  tasks/lzards-backup/schemas/config.json
  tasks/lzards-backup/src/index.ts
  tasks/lzards-backup/src/types.ts
  tasks/lzards-backup/tests/test-index.js
Labels: pr feedback

#3161 [CUMULUS-3116] Revert ElasticSearch Default Sort
  CHANGELOG.md
  packages/es-client/README.md
  packages/es-client/esDefaults.js
  packages/es-client/tests/test-queries-package.js
Labels: needs review
