Repository nasa/cumulus, pull requests merged in 2022-08, with the labels that each got.

#3056 CUMULUS-2645 - Remove dynamodb files table/associated logic
  CHANGELOG.md
  packages/api/bin/cli.js
  packages/api/bin/serve.js
  packages/api/lambdas/db-indexer.js
  packages/api/lambdas/executeMigrations.js
  packages/api/lambdas/granuleFilesCacheUpdater.js
  packages/api/lib/GranuleFilesCache.js
  packages/api/migrations/index.js
  packages/api/migrations/migration_0.js
  packages/api/migrations/migration_1.js
  packages/api/migrations/migration_2.js
  packages/api/migrations/migration_3.js
  packages/api/migrations/migration_4.js
  packages/api/migrations/migration_5.js
  packages/api/tests/lambdas/test-create-reconciliation-report.js
  packages/api/tests/lambdas/test-db-indexer.js
  packages/api/tests/lambdas/test-granuleFilesCacheUpdater.js
  packages/api/tests/lib/GranuleFilesCache/test-batchUpdate.js
  packages/api/tests/lib/GranuleFilesCache/test-cacheTableName.js
  packages/api/tests/lib/GranuleFilesCache/test-getGranuleId.js
  packages/api/tests/lib/GranuleFilesCache/test-put.js
  packages/api/tests/migrations/migration_5.js
  packages/api/tests/migrations/test_migrations.js
  packages/api/webpack.config.js
  tf-modules/archive/db_indexer.tf
  tf-modules/archive/execute_migrations.tf
  tf-modules/archive/granule_files_cache_updater.tf
  tf-modules/archive/reconciliation_report.tf
  tf-modules/data-persistence/dynamo.tf
  tf-modules/data-persistence/outputs.tf
  tf-modules/data-persistence/variables.tf
Labels: pr feedback

#3063 fix: await should not be used redundantly
  example/lambdas/ftpPopulateTestLambda/index.js
Labels: needs review, User Contribution

#3074 CUMULUS-3019: Fix file deletion bug
  CHANGELOG.md
  packages/api/lib/writeRecords/write-granules.js
  packages/api/tests/lib/writeRecords/test-write-granules.js
Labels: in review

#3078 CUMULUS-2631: Add Bearer token support to s3credentials endpoint
  CHANGELOG.md
  example/cumulus-tf/tea_s3_credentials_endpoint_test.tf
  example/spec/parallel/s3Access/teaS3CredentialsSpec.js
  packages/api/lib/distribution.js
  packages/integration-tests/api/distribution.js
  packages/s3-credentials-endpoint/index.js
  packages/s3-credentials-endpoint/tests/test-handler-with-edl-token.js
  packages/s3-credentials-endpoint/tests/test-index.js
  tf-modules/distribution/main.tf
  tf-modules/distribution/outputs.tf
Labels: pr feedback

#3095 CUMULUS-3027 -- Tightly constrain typescript version due to knex typing
  CHANGELOG.md
  bamboo/generate-ts-build-cache.sh
  package.json
Labels: needs review
