Repository nasa/cumulus, pull requests merged in 2022-02, with the labels that each got.

#2664 Jk/cumulus 2782 update movegranules to write to es
  CHANGELOG.md
  packages/api/lib/granules.js
  packages/api/tests/endpoints/test-granules.js
  packages/ingest/src/granule.ts
  packages/ingest/test/test-granule.js
  tasks/move-granules/webpack.config.js
  tasks/sync-granule/webpack.config.js
Labels: in review

#2643 CUMULUS-2538: improve waitForObjectExists logging
  packages/aws-client/package.json
  packages/aws-client/src/S3.ts
Labels: in review

#2682 Mhs/increase timeout integration test failure
  CHANGELOG.md
  example/spec/parallel/ingestGranule/IngestUMMGSuccessSpec.js
Labels: in review, low priority, Very Small

#2693 Add events actions to step_policy for the step aws_am_role
  CHANGELOG.md
  tf-modules/ingest/iam.tf
Labels: User Contribution

#2700 Merge in user contribution #2693: "ab/add events permissions to steprole policy"
  CHANGELOG.md
  tf-modules/ingest/iam.tf
Labels: User Contribution

#2709 cumulus 2833/update schema with correct titles
  CHANGELOG.md
  packages/api/models/schemas.js
Labels: Very Small

#2708 CUMULUS-2847: Backport vuln/security fixes to 9.4.x
  CHANGELOG.md
  audit-ci.json
  bamboo/docker-compose.yml
  example/cumulus-tf/cnm_response_task.tf
  example/cumulus-tf/cnm_to_cma_task.tf
  lambdas/data-migration1/webpack.config.js
  lambdas/data-migration2/webpack.config.js
  lambdas/db-migration/webpack.config.js
  lambdas/db-provision-user-database/webpack.config.js
  lambdas/postgres-migration-async-operation/webpack.config.js
  lambdas/postgres-migration-count-tool/webpack.config.js
  package.json
  packages/api/webpack.config.js
  packages/common/package.json
  packages/integration-tests/webpack.config.js
  packages/s3-credentials-endpoint/webpack.config.js
  packages/sftp-client/package.json
  tasks/discover-granules/webpack.config.js
  tasks/discover-pdrs/webpack.config.js
  tasks/hyrax-metadata-updates/package.json
  tasks/parse-pdr/webpack.config.js
  tasks/sync-granule/webpack.config.js
  tasks/test-processing/webpack.config.js
  tf-modules/internal/cumulus-test-cleanup/package.json
Labels: needs review

#2704 Mhs/cumulus 2833/build bug fix
  example/lambdas/python-reference-task/package.sh
  packages/async-operations/package.json
  packages/errors/package.json
  packages/tea-map-cache/package.json
Labels: low priority, Very Small

#2706 CUMULUS-2847 -- Update API to pull dynamo config from s3/move configuration setup outside of handler
  packages/api/app/index.js
  packages/api/tests/app/test-app.js
  packages/api/tests/app/test-dynamo-table-names.js
  packages/api/tests/app/test-missing-dynamo-env-var.js
  tf-modules/archive/api.tf
  tf-modules/archive/iam.tf
Labels: pr feedback

#2711 CUMULUS-2848 -- Move database table names into API secret (forward port CUMULUS-2847)
  CHANGELOG.md
  packages/api/app/index.js
  packages/api/endpoints/collections.js
  packages/api/tests/app/test-app-env-vars-throws-on-missing-secret.js
  packages/api/tests/app/test-app-env-vars.js
  packages/api/tests/app/test-app.js
  tf-modules/archive/api.tf
  tf-modules/archive/iam.tf
Labels: pr feedback

#2713 Update bootstrap/clean commands to drop/cleanup a .bootstrapSha file
  .gitignore
  package.json
Labels: :turkey:
