Repository nasa/cumulus, pull requests merged in 2022-10, with the labels that each got.

#3116 merge release-11.1.7 changelog to master
  CHANGELOG.md
Labels: pr feedback

#3130 CUMULUS-3104:Update async operation image Dockerfile
  CHANGELOG.md
  audit-ci.json
  example/cumulus-tf/variables.tf
  package.json
  packages/api/ecs/async-operation/Dockerfile
  packages/api/package.json
  tf-modules/cumulus/variables.tf
Labels: pr feedback

#3125 CUMULUS-3102: Update broken link
  docs/deployment/README.md
Labels: in review

#3132 CUMULUS-3104: Fixed TS compilation error caused by @aws-sdk/client-s3 upgrade
  CHANGELOG.md
  bamboo/cleanup-integration-tests.sh
  example/lambdas/lzardsClientTest/package.json
  lambdas/postgres-migration-count-tool/package.json
  package.json
  packages/api/tests/lambdas/test-process-s3-dead-letter-archive.js
  packages/async-operations/package.json
  packages/aws-client/src/S3.ts
  packages/aws-client/tests/test-S3.js
  packages/lzards-api-client/package.json
  tasks/lzards-backup/package.json
Labels: pr feedback, high priority
