Repository nasa/cumulus, pull requests merged in 2023-02, with the labels that each got.

#3235 Jk/cumulus 3148 update tf module
  CHANGELOG.md
  docs/deployment/postgres-database-deployment.md
  example/rds-cluster-tf/variables.tf
  tf-modules/cumulus-rds-tf/variables.tf
Labels: pr feedback

#3237 CUMULUS-3181:Fixed sqsMessageRemover to correctly retrieve ENABLE sqs rules
  CHANGELOG.md
  packages/api/lambdas/sqs-message-consumer.js
  packages/api/tests/endpoints/test-granules.js
  packages/api/tests/endpoints/test-rules.js
  packages/api/tests/lambdas/test-sqs-message-consumer.js
Labels: pr feedback

#3226 CUMULUS-3149 -- Update bulk deletion lambda to allow for concurrent deletion when CMR deletion option is selected
  CHANGELOG.md
  packages/api/endpoints/granules.js
  packages/api/lambdas/bulk-operation.js
  packages/api/lib/granule-remove-from-cmr.js
  packages/api/package.json
  packages/api/src/zod-utils/better-zod-error.ts
  packages/api/src/zod-utils/index.ts
  packages/api/src/zod-utils/parser.ts
  packages/api/src/zod-utils/type-guard.ts
  packages/api/tests/endpoints/granules/test-bulk-delete.js
  packages/api/tests/endpoints/granules/test-bulk-granules.js
  packages/api/tests/endpoints/granules/test-bulk-reingest.js
  packages/api/tests/helpers/bulkTestHelpers.js
  packages/api/tests/lambdas/test-bulk-granule-delete.js
  packages/db/src/lib/granule.ts
Labels: needs review

#3259 CUMULUS-3189: update CMA python versions to support pip 23.0
  CHANGELOG.md
  audit-ci.json
  example/lambdas/python-processing/Pipfile
  example/lambdas/python-processing/Pipfile.lock
  example/lambdas/python-reference-activity/Pipfile
  example/lambdas/python-reference-activity/Pipfile.lock
  example/lambdas/python-reference-task/Pipfile
  example/lambdas/python-reference-task/Pipfile.lock
Labels: in review

#3270 Jk/cumulus 1/fix integration test bucket
  example/spec/parallel/ingestGranule/IngestGranuleFailureSpec.js
Labels: high priority

#3242 CUMULUS-3111: dropped writes for granules should also drop granule file writes
  CHANGELOG.md
  packages/api/lib/writeRecords/utils.js
  packages/api/lib/writeRecords/write-granules.js
  packages/api/tests/lib/writeRecords/test-write-granules.js
  packages/db/src/lib/granule.ts
  packages/es-client/indexer.js
Labels: pr feedback

#3269 CUMULUS-3006 - removing executions terraform code
  example/spec/parallel/ingestGranule/IngestGranulePythonProcessingSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestUMMGSuccessSpec.js
  example/spec/parallel/pythonReferenceTests/PythonReferenceSpec.js
  example/spec/parallel/queueGranules/QueueGranulesSpec.js
  example/spec/parallel/queueGranules/queueGranulesPostProcessingSpec.js
  example/spec/parallel/retryConfiguration/retryConfigurationSpec.js
  example/spec/serial/ingestPdrWithNodeNameFtpSpec.js
  tf-modules/archive/api.tf
  tf-modules/archive/clean_executions.tf
  tf-modules/archive/db_indexer.tf
  tf-modules/archive/ingest-reporting.tf
  tf-modules/archive/process_dead_letter_archive.tf
  tf-modules/data-persistence/dynamo.tf
  tf-modules/data-persistence/outputs.tf
  tf-modules/data-persistence/terraform.tfvars.example
  tf-modules/data-persistence/variables.tf
  tf-modules/ingest/lambda-functions.tf
Labels: pr feedback
