Repository nasa/cumulus, pull requests merged in 2023-10, with the labels that each got.

#3200 Introducing allFilesPresent metadata field for Cumulus Collections. Fixes Issue #3193
  tasks/discover-granules/index.js
  tasks/discover-granules/tests/index.js
Labels: in review, User Contribution

#3493 CUMULUS-3434:Update orca-recovery-adapter and orca v9
  CHANGELOG.md
  example/cumulus-tf/orca.tf
  example/cumulus-tf/orca_recovery_adapter_workflow.asl.json
  packages/api/lib/orca.js
  tasks/orca-recovery-adapter/schemas/output.json
  tasks/orca-recovery-adapter/schemas/output.json.template
  tasks/orca-recovery-adapter/src/index.ts
  tasks/orca-recovery-adapter/src/types.ts
  tasks/orca-recovery-adapter/tests/test-index.js
Labels: needs review, in review

#3505 CUMULUS-3467:Add childWorkflowMeta to QueueWorkflow task config
  CHANGELOG.md
  docs/data-cookbooks/queue-post-to-cmr.md
  example/cumulus-tf/ingest_granule_with_queue_workflow.asl.json
  example/cumulus-tf/publish_granule_with_requeue_workflow.asl.json
  example/spec/parallel/ingestGranule/ingestGranuleQueueSpec.js
  tasks/queue-workflow/schemas/config.json
  tasks/queue-workflow/tests/index.js
Labels: in review
