Repository nasa/cumulus, pull requests merged in 2023-06, with the labels that each got.

#3397 addition of ecarton.tfvars files in deployments
  bamboo/select-stack.js
  example/config.yml
  example/deployments/cumulus/ecarton-ci-tf.tfvars
  example/deployments/data-persistence/ecarton-ci-tf.tfvars
  example/deployments/db-migration/ecarton-ci-tf.tfvars
Labels: needs review

#3391 CUMULUS-3252:Add orca copy_to_archive_adapter lambda to cumulus
  CHANGELOG.md
  example/cumulus-tf/ingest_and_publish_granule_with_orca_workflow.asl.json
  example/cumulus-tf/ingest_and_publish_granule_with_orca_workflow.tf
  example/cumulus-tf/main.tf
  example/cumulus-tf/orca.tf
  example/spec/parallel/orca/OrcaBackupAndRecoverySpec.js
  packages/oauth-client/src/EarthdataLoginClient.ts
  packages/oauth-client/tests/test-EarthdataLoginClient.js
  tasks/orca-copy-to-archive-adapter/.npmignore
  tasks/orca-copy-to-archive-adapter/.nycrc.json
  tasks/orca-copy-to-archive-adapter/README.md
  tasks/orca-copy-to-archive-adapter/bin/package.sh
  tasks/orca-copy-to-archive-adapter/package.json
  tasks/orca-copy-to-archive-adapter/schemas/config.json
  tasks/orca-copy-to-archive-adapter/schemas/input.json
  tasks/orca-copy-to-archive-adapter/schemas/input.json.template
  tasks/orca-copy-to-archive-adapter/schemas/output.json
  tasks/orca-copy-to-archive-adapter/schemas/output.json.template
  tasks/orca-copy-to-archive-adapter/src/index.ts
  tasks/orca-copy-to-archive-adapter/src/types.ts
  tasks/orca-copy-to-archive-adapter/tests/test-index.js
  tasks/orca-copy-to-archive-adapter/tsconfig.json
  tasks/orca-copy-to-archive-adapter/webpack.config.js
  tf-modules/cumulus/ingest.tf
  tf-modules/cumulus/outputs.tf
  tf-modules/cumulus/variables.tf
  tf-modules/ingest/orca-copy-to-archive-adapter.tf
  tf-modules/ingest/outputs.tf
  tf-modules/ingest/variables.tf
Labels: needs review

#3408 Update serve to create recon report table
  packages/api/bin/serve.js
Labels: work in progress

#3389 [CUMULUS-3245]: Remove messages from queue if execution exists
  CHANGELOG.md
  packages/api/lambdas/sf-starter.js
  packages/api/tests/lambdas/test-sf-starter.js
  packages/ingest/src/consumer.ts
  tf-modules/ingest/event-sources.tf
Labels: pr feedback

#3312 Add name to event_rule resource in throttle example
  example/cumulus-tf/throttled-queue.tf
Labels: needs review, User Contribution
