Repository nasa/cumulus, pull requests merged in 2024-05, with the labels that each got.

#3641 Jk/cumulus 3701 fix null rules
  CHANGELOG.md
  packages/api/endpoints/rules.js
  packages/api/lib/rulesHelpers.js
  packages/api/tests/lib/rules/test-rulesHelpers.js
Labels: in review

#3645 Jk/cumulus 3701 fix null rules (#3641)
  CHANGELOG.md
  packages/api/endpoints/rules.js
  packages/api/lib/rulesHelpers.js
  packages/api/tests/lib/rules/test-rulesHelpers.js
Labels: pr feedback

#3651 CUMULUS-3712 - Release 18.2.1 CHANGELOG updates
  CHANGELOG.md
Labels: needs review

#3656 CUMULUS-3694: Update granules List endpoints to query postgres - filter by field value
  CHANGELOG.md
  example/spec/helpers/granuleUtils.js
  example/spec/parallel/testAPI/granuleSpec.js
  packages/api/endpoints/granules.js
  packages/api/tests/endpoints/test-granules.js
  packages/db/src/search/BaseSearch.ts
  packages/db/src/search/GranuleSearch.ts
  packages/db/src/search/field-mapping.ts
  packages/db/src/search/queries.ts
  packages/db/src/types/search.ts
  packages/db/tests/search/test-GranuleSearch.js
  packages/db/tests/search/test-field-mapping.js
  packages/db/tests/search/test-queries.js
Labels: in review

#3666 [CUMULUS-3671]: Update docs for Serverless V2
  docs/deployment/README.md
  docs/deployment/choosing_configuring_rds.md
  docs/deployment/postgres-database-deployment.md
  docs/upgrade-notes/serverless-v2-upgrade.md
Labels: needs review
