Repository nasa/cumulus, pull requests merged in 2024-08, with the labels that each got.

#3777 CUMULUS-3840:Fixed @cumulus/api/bin/serve to correctly use EsClient
  CHANGELOG.md
  packages/api/bin/local-test-defaults.js
  packages/api/bin/serve.js
Labels: needs review

#3779 CUMULUS-3841: Increase fetchRules page size to improve performance.
  CHANGELOG.md
  packages/api/lib/rulesHelpers.js
  packages/api/tests/lib/rules/test-rulesHelpers.js
Labels: needs review

#3760 [CUMULUS-3229] - Remove ElasticSearch from Rules Endpoints and Update LIST Query
  CHANGELOG.md
  packages/api/endpoints/rules.js
  packages/api/lib/testUtils.js
  packages/api/tests/endpoints/test-rules.js
  packages/api/tests/lambdas/test-index-from-database.js
  packages/db/src/index.ts
  packages/db/src/search/RuleSearch.ts
  packages/db/src/search/field-mapping.ts
  packages/db/src/search/queries.ts
  packages/db/src/translate/rules.ts
  packages/db/tests/search/test-RuleSearch.js
  packages/db/tests/translate/test-rules.js
  packages/es-client/indexer.js
  packages/es-client/tests/test-es-indexer.js
Labels: needs review, in review

#3790 CUMULUS-3756
  CHANGELOG.md
  tasks/update-granules-cmr-metadata-file-links/index.js
  tasks/update-granules-cmr-metadata-file-links/schemas/config.json
  tasks/update-granules-cmr-metadata-file-links/tests/test-index.js
Labels: needs review, User Contribution
