Repository nasa/cumulus, pull requests merged in 2024-11, with the labels that each got.

#3854 CUMULUS-3859: Update @cumulus/api/bin/serveUtils to no longer add records to ES
  CHANGELOG.md
  lambdas/reconciliation-report-migration/package.json
  packages/api/bin/serveUtils.js
Labels: Very Small

#3861 CUMULUS-3859-1: Remove es from local api code and update active collection search
  CHANGELOG.md
  package.json
  packages/api/bin/cli.js
  packages/api/bin/serve.js
  packages/api/bin/serveUtils.js
  packages/db/src/search/CollectionSearch.ts
  packages/db/src/search/GranuleSearch.ts
  packages/db/src/search/StatsSearch.ts
  packages/db/src/translate/async_operations.ts
  packages/db/tests/lib/test-granule.js
  packages/db/tests/search/test-CollectionSearch.js
Labels: pr feedback, needs review, in review

#3866 Address audit issue and update integration test bucket
  CHANGELOG.md
  example/spec/parallel/cnmWorkflow/KinesisTestTriggerSpec.js
  package.json
Labels: needs review, Very Small

#3862 CUMULUS-3941: Adds Failed disposition for short pan
  packages/api/lib/pdrHelpers.js
  packages/api/tests/lib/test-pdrHelpers.js
  tasks/send-pan/schemas/input.json
  tasks/send-pan/src/index.ts
  tasks/send-pan/src/types.ts
  tasks/send-pan/tests/index.js
Labels: User Contribution

#3869 Updated user-data for compatibility with Amazon Linux 2023 AMI
  CHANGELOG.md
  tf-modules/cumulus/ecs_cluster_instance_autoscaling_cf_template.yml.tmpl
Labels: User Contribution
