Repository nasa/cumulus, pull requests merged in 2024-10, with the labels that each got.

#3807 [CUMULUS-3902]: Update AWS-SDK errors to use the V3 error classes
  CHANGELOG.md
  example/spec/helpers/kinesisHelpers.js
  example/spec/helpers/workflowUtils.js
  packages/api/lambdas/sf-starter.js
  packages/api/tests/endpoints/test-execution-status.js
  packages/api/tests/lambdas/test-sf-starter.js
  packages/api/tests/lib/FileUtils/test-setS3FileSize.js
  packages/aws-client/src/Kinesis.ts
  packages/aws-client/src/StepFunctions.ts
  packages/aws-client/tests/S3/test-waitForObjectToExist.js
  packages/aws-client/tests/test-StepFunctions.js
  packages/errors/src/index.ts
  packages/ingest/src/consumer.ts
  packages/integration-tests/index.js
  tasks/files-to-granules/index.js
  tasks/pdr-status-check/index.js
  tasks/pdr-status-check/tests/index.js
  tf-modules/internal/cumulus-test-cleanup/reap-kinesis.js
Labels: in review

#3821 Reverts ORCA v10.0.0 update
  CHANGELOG.md
  bamboo/bootstrap-tf-deployment.sh
  example/cumulus-tf/orca.tf
  example/cumulus-tf/variables.tf
Labels: needs review

#3791 CUMULUS-3756 NDCUM-1264 Added excludeFileRegex configuration to update-granules-cmr-metadata-…
  CHANGELOG.md
  packages/api/package.json
  packages/aws-client/package.json
  packages/aws-client/tests/test-services.js
  packages/common/package.json
  packages/message/package.json
  tasks/update-granules-cmr-metadata-file-links/.nycrc.json
  tasks/update-granules-cmr-metadata-file-links/index.js
  tasks/update-granules-cmr-metadata-file-links/package.json
  tasks/update-granules-cmr-metadata-file-links/schemas/config.json
  tasks/update-granules-cmr-metadata-file-links/tests/test-index.js
Labels: User Contribution

#3830 [CUMULUS-3921] Test new Orca version and update example deployment
  CHANGELOG.md
  bamboo/bootstrap-tf-deployment.sh
  example/cumulus-tf/orca.tf
  example/cumulus-tf/variables.tf
Labels: needs review

#3822 CUMULUS-3806-3 -- Remove internal rec report references/cleanup
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  packages/api/lambdas/create-reconciliation-report.js
  packages/api/lambdas/internal-reconciliation-report.js
  packages/api/lib/reconciliationReport.js
  packages/api/tests/lambdas/test-internal-reconciliation-report.js
  packages/api/tests/lib/test-reconciliationReport.js
  tf-modules/archive/reconciliation_report.tf
Labels: blocked

#3838 CUMULUS-3931: Allowing force_new_deployment to be configurable for ecs services.
  CHANGELOG.md
  tf-modules/cumulus_ecs_service/main.tf
  tf-modules/cumulus_ecs_service/variables.tf
Labels: User Contribution, Very Small

#3844 19.1.0 Release Fix: fix no top level await (#3843)
  bamboo/npm-tag.js
Labels: needs review

#3837 Cumulus 3904
  CHANGELOG.md
  tf-modules/cumulus/ingest.tf
  tf-modules/cumulus/variables.tf
Labels: User Contribution, Very Small
