Repository nasa/cumulus, pull requests merged in 2024-01, with the labels that each got.

#3544 dummy out conceptExists and xit postToCMRTasks
  CHANGELOG.md
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestUMMGSuccessSpec.js
  example/spec/parallel/ingestGranule/ingestGranuleQueueSpec.js
  packages/integration-tests/cmr.js
Labels: needs review, high priority

#3516 CUMULUS-3432/CUMULUS-3506 - Upgrade to Aurora PG v13
  CHANGELOG.md
  bamboo/docker-compose.yml
  docs/deployment/postgres-database-deployment.md
  example/rds-cluster-tf/variables.tf
  example/spec/parallel/ingestGranule/IngestGranuleFailureSpec.js
  scripts/run_ci_unit_coverage.sh
  tf-modules/cumulus-rds-tf/variables.tf
Labels: pr feedback

#3553 CUMULUS-3432/CUMULUS-3506 - Upgrade to Aurora PG v13 (#3516)
  CHANGELOG.md
  bamboo/docker-compose.yml
  docs/deployment/postgres-database-deployment.md
  example/rds-cluster-tf/variables.tf
  example/spec/parallel/ingestGranule/IngestGranuleFailureSpec.js
  tf-modules/cumulus-rds-tf/variables.tf
Labels: needs review

#3565 Jk/bugfix/cumulus 3564
  CHANGELOG.md
  audit-ci.json
  example/lambdas/ftpPopulateTestLambda/webpack.config.js
  example/lambdas/lzardsClientTest/webpack.config.js
  lambdas/db-migration/webpack.config.js
  lambdas/db-provision-user-database/webpack.config.js
  lambdas/sqs-message-remover/webpack.config.js
  packages/api/webpack.config.js
  packages/integration-tests/webpack.config.js
  packages/s3-credentials-endpoint/webpack.config.js
  packages/tea-map-cache/webpack.config.js
  tasks/add-missing-file-checksums/webpack.config.js
  tasks/discover-granules/webpack.config.js
  tasks/discover-pdrs/webpack.config.js
  tasks/files-to-granules/webpack.config.js
  tasks/hello-world/webpack.config.js
  tasks/hyrax-metadata-updates/webpack.config.js
  tasks/lzards-backup/webpack.config.js
  tasks/move-granules/webpack.config.js
  tasks/orca-copy-to-archive-adapter/webpack.config.js
  tasks/orca-recovery-adapter/webpack.config.js
  tasks/parse-pdr/webpack.config.js
  tasks/pdr-status-check/webpack.config.js
  tasks/post-to-cmr/webpack.config.js
  tasks/queue-granules/webpack.config.js
  tasks/queue-pdrs/webpack.config.js
  tasks/queue-workflow/webpack.config.js
  tasks/send-pan/webpack.config.js
  tasks/sf-sqs-report/webpack.config.js
  tasks/sync-granule/webpack.config.js
  tasks/test-processing/webpack.config.js
  tasks/update-cmr-access-constraints/webpack.config.js
  tasks/update-granules-cmr-metadata-file-links/webpack.config.js
  tf-modules/internal/cumulus-test-cleanup/webpack.config.js
Labels: needs review, high priority

#3552 [CUMULUS-3560] Address intermittent unit tests
  package.json
  scripts/run_ci_unit_coverage.sh
Labels: needs review

#3546 revert CUMULUS-3540
  CHANGELOG.md
  example/cumulus-tf/lambdas.tf
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestUMMGSuccessSpec.js
  example/spec/parallel/ingestGranule/ingestGranuleQueueSpec.js
  packages/integration-tests/cmr.js
Labels: in review

#3562 Adds ppilone to Bamboo select stack
  bamboo/select-stack.js
  example/deployments/cumulus/ppilone-ci-tf.tfvars
  example/deployments/data-persistence/ppilone-ci-tf.tfvars
  example/deployments/db-migration/ppilone-ci-tf.tfvars
Labels: pr feedback
