Repository nasa/cumulus, pull requests merged in 2024-07, with the labels that each got.

#3693 CUMULUS-3639: Add support to db/CollectionSearch to retrieve active collections
  CHANGELOG.md
  example/config.yml
  example/deployments/cumulus/cumulus-lp.tfvars
  example/deployments/data-persistence/cumulus-lp.tfvars
  example/deployments/db-migration/cumulus-lp.tfvars
  packages/api/endpoints/collections.js
  packages/api/endpoints/granules.js
  packages/api/endpoints/stats.js
  packages/api/tests/endpoints/collections/active-collections.js
  packages/db/src/search/BaseSearch.ts
  packages/db/src/search/CollectionSearch.ts
  packages/db/src/search/field-mapping.ts
  packages/db/tests/search/test-CollectionSearch.js
  packages/db/tests/search/test-field-mapping.js
Labels: in review

#3692 Jk/cumulus 3320
  CHANGELOG.md
  example/spec/parallel/testAPI/bulkDeleteExecutionByCollectionSpec.js
  example/spec/parallel/testAPI/sqsRuleSpec.js
  packages/api-client/.nycrc.json
  packages/api-client/src/executions.ts
  packages/api-client/tests/test-executions.js
  packages/api/endpoints/executions.js
  packages/api/endpoints/granules.js
  packages/api/lambdas/bulk-operation.js
  packages/api/lib/endpoints.js
  packages/api/lib/executions.js
  packages/api/lib/schemas.js
  packages/api/lib/utils.js
  packages/api/lib/writeRecords/utils.js
  packages/api/tests/endpoints/test-executions.js
  packages/api/tests/helpers/create-test-data.js
  packages/api/tests/lib/test-executions.js
  packages/api/tests/lib/test-utils.js
  packages/db/src/index.ts
  packages/db/src/lib/execution.ts
  packages/db/src/migrations/20240606060726_alter_async_operations_add_operation_type_bulk_execution_delete.ts
  packages/db/src/migrations/20240613174614_add_execution_parent_and_collection_indexes.ts
  packages/db/src/migrations/20240617204826_update_executions_deletion_constraint.ts
  packages/db/tests/lib/test-execution.js
  packages/es-client/executions.js
  packages/es-client/indexer.js
  packages/es-client/search.js
  packages/es-client/tests/test-executions.js
  packages/message/src/Collections.ts
  packages/types/api/async_operations.d.ts
Labels: pr feedback

#3701 CUMULUS-3737: Prepare release 18.3.1
  CHANGELOG.md
  docs/upgrade-notes/update-cumulus_id-type-indexes-CUMULUS-3449.md
  example/cumulus-tf/variables.tf
  lambdas/db-migration/webpack.config.js
  lambdas/db-provision-user-database/webpack.config.js
  lambdas/dla-migration/webpack.config.js
  lambdas/migration-helper-async-operation/webpack.config.js
  lambdas/sqs-message-remover/webpack.config.js
  packages/api/ecs/async-operation/Dockerfile
  packages/api/ecs/async-operation/package.json
  packages/api/webpack.config.js
  packages/db/README.md
  packages/db/src/config.ts
  packages/db/src/migrations/20240124101001_update_cumulus_id_add_indexes.sql
  packages/db/src/migrations/20240125171703_update_granule_execution_cumulus_id_type.ts
  packages/db/src/migrations/20240126135619_granules_add_indexes.ts
  packages/db/src/migrations/20240126165019_granules_update_constraints.ts
  packages/db/tests/lib/test-QuerySearchClient.js
  packages/db/tests/lib/test-execution.js
  packages/db/tests/lib/test-file.js
  packages/db/tests/lib/test-granule.js
  packages/db/tests/models/test-base-model.js
  packages/db/tests/models/test-file-model.js
  packages/db/tests/models/test-granules-executions-model.js
  packages/db/tests/test-config.js
  packages/integration-tests/webpack.config.js
  packages/s3-credentials-endpoint/webpack.config.js
  packages/tea-map-cache/webpack.config.js
  tasks/add-missing-file-checksums/webpack.config.js
  tasks/discover-granules/webpack.config.js
  tasks/discover-pdrs/webpack.config.js
  tasks/files-to-granules/webpack.config.js
  tasks/hello-world/webpack.config.js
  tasks/hyrax-metadata-updates/webpack.config.js
  tasks/lzards-backup/webpack.config.js
  tasks/move-granules/webpack.config.js
  tasks/orca-copy-to-archive-adapter/webpack.config.js
  tasks/orca-recovery-adapter/webpack.config.js
  tasks/parse-pdr/webpack.config.js
  tasks/pdr-status-check/webpack.config.js
  tasks/post-to-cmr/webpack.config.js
  tasks/queue-granules/webpack.config.js
  tasks/queue-pdrs/webpack.config.js
  tasks/queue-workflow/webpack.config.js
  tasks/send-pan/webpack.config.js
  tasks/sf-sqs-report/webpack.config.js
  tasks/sync-granule/webpack.config.js
  tasks/test-processing/webpack.config.js
  tasks/update-cmr-access-constraints/webpack.config.js
  tasks/update-granules-cmr-metadata-file-links/webpack.config.js
  tf-modules/internal/cumulus-test-cleanup/webpack.config.js
  website/sidebars.js
Labels: needs review

#3714 Ecarton/investigation build ts failures
  CHANGELOG.md
  bamboo/generate-ts-build-cache.sh
Labels: needs review

#3702 Jk/cumulus 3785 2
  CHANGELOG.md
  docs/development/forked-pr.md
  example/data-persistence-tf/variables.tf
  packages/api/endpoints/dashboard.js
  packages/common/src/sleep.ts
  packages/common/src/test-utils.ts
  packages/ingest/src/SftpProviderClient.js
  packages/ingest/src/recursion.ts
  packages/sftp-client/src/index.ts
  tf-modules/cumulus-rds-tf/main.tf
  tf-modules/cumulus-rds-tf/variables.tf
  tf-modules/data-persistence/elasticsearch.tf
  tf-modules/data-persistence/variables.tf
Labels: pr feedback

#3590 Adjust code documentation
  docs/development/forked-pr.md
  packages/common/src/sleep.ts
  packages/common/src/test-utils.ts
Labels: User Contribution

#3628 Add support for configuring EBS volume type for Elasticsearch
  CHANGELOG.md
  tf-modules/data-persistence/elasticsearch.tf
  tf-modules/data-persistence/variables.tf
Labels: needs review, User Contribution

#3592 Don't allow duplicate URLs in Hyrax metadata updates
  CHANGELOG.md
  tasks/hyrax-metadata-updates/index.js
  tasks/hyrax-metadata-updates/tests/test-index.js
Labels: pr feedback, User Contribution

#3703 NDCUM-1096
  CHANGELOG.md
  tasks/update-granules-cmr-metadata-file-links/index.js
  tasks/update-granules-cmr-metadata-file-links/package.json
  tasks/update-granules-cmr-metadata-file-links/tests/data/payload.json
  tasks/update-granules-cmr-metadata-file-links/tests/test-index.js
Labels: needs review, User Contribution

#3728 CUMULUS-3608: Adds variable for sqs message consumer watcher message and time limits
  CHANGELOG.md
  tf-modules/ingest/cloudwatch-events.tf
  tf-modules/ingest/variables.tf
Labels: needs review

#3739 Pin @aws-sdk/client-s3 to 3.614
  CHANGELOG.md
  packages/aws-client/package.json
Labels: needs review, high priority

#3721 CUMULUS-3385 cleanExecutions fix
  CHANGELOG.md
  docs/features/execution_payload_retention.md
  packages/api/lambdas/cleanExecutions.js
  packages/api/tests/lambdas/test-cleanExecutions.js
  packages/db/src/models/execution.ts
  packages/es-client/search.js
  scripts/generate_records/README.md
  scripts/generate_records/db_record_loaders.js
  scripts/generate_records/generate_db_executions.js
  scripts/generate_records/tests/test-db_record_loaders.js
  scripts/generate_records/tests/test-end_to_end.js
  tf-modules/archive/clean_executions.tf
  tf-modules/archive/variables.tf
  tf-modules/cumulus/archive.tf
  tf-modules/cumulus/variables.tf
Labels: pr feedback

#3742 Back port CUMULUS-3807 to 18.3.x
  CHANGELOG.md
  packages/aws-client/package.json
Labels: needs review

#3743 [CUMULUS-3789] - Backport 3385, 3760, 3742
  CHANGELOG.md
  docs/features/execution_payload_retention.md
  packages/api/lambdas/cleanExecutions.js
  packages/api/tests/lambdas/test-cleanExecutions.js
  packages/db/src/index.ts
  packages/db/src/models/execution.ts
  packages/db/src/models/granules-executions.ts
  packages/db/src/test-utils.ts
  packages/es-client/search.js
  scripts/generate_records/.nycrc.json
  scripts/generate_records/README.md
  scripts/generate_records/db_record_loaders.js
  scripts/generate_records/generate_db_executions.js
  scripts/generate_records/generate_db_records.js
  scripts/generate_records/package.json
  scripts/generate_records/tests/test-db_record_loaders.js
  scripts/generate_records/tests/test-end_to_end.js
  scripts/generate_records/tests/test-generate_db_records.js
  tf-modules/archive/clean_executions.tf
  tf-modules/archive/variables.tf
  tf-modules/cumulus/archive.tf
  tf-modules/cumulus/variables.tf
Labels: needs review

#3749 CUMULUS-3798: Adds missing version to website docs 18.3.2
  website/versions.json
Labels: needs review
