Repository nasa/cumulus, pull requests merged in 2024-09, with the labels that each got.

#3780 Ecarton/cicd/unit test errors 08 24
  CHANGELOG.md
  bamboo/unit-tests.sh
  packages/api/tests/endpoints/test-granules-get.js
  packages/api/tests/endpoints/test-granules.js
  packages/aws-client/package.json
  packages/db/src/lib/execution.ts
  packages/db/tests/lib/test-execution.js
Labels: needs review

#3798 Fix isThrottlingException function to check error name
  packages/errors/src/index.ts
Labels: high priority, User Contribution

#3788 CUMULUS-3837: Create ReconciliationReportsTable in RDS and add indexes
  CHANGELOG.md
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  packages/api/endpoints/reconciliation-reports.js
  packages/api/lambdas/create-reconciliation-report.js
  packages/api/tests/endpoints/test-executions.js
  packages/api/tests/endpoints/test-reconciliation-reports.js
  packages/api/tests/lambdas/test-create-reconciliation-report.js
  packages/api/tests/lambdas/test-internal-reconciliation-report.js
  packages/db/src/index.ts
  packages/db/src/migrations/20240814185217_create_reconciliation_reports_table.ts
  packages/db/src/models/reconciliation_report.ts
  packages/db/src/tables.ts
  packages/db/src/test-utils.ts
  packages/db/src/translate/reconciliation_reports.ts
  packages/db/src/types/reconciliation_report.ts
  packages/db/tests/models/test-reconciliation-report-model.js
  packages/db/tests/translate/test-reconciliation-reports.js
  packages/types/api/reconciliation_reports.d.ts
Labels: needs review, high priority

#3632 CUMULUS-3536 Update Cumulus Core from Aurora Serverless V1 to V2
  CHANGELOG.md
  docs/deployment/README.md
  docs/deployment/choosing_configuring_rds.md
  docs/deployment/postgres-database-deployment.md
  docs/upgrade-notes/serverless-v2-upgrade.md
  example/rds-cluster-tf/main.tf
  example/rds-cluster-tf/outputs.tf
  example/rds-cluster-tf/terraform.tfvars.example
  example/rds-cluster-tf/variables.tf
  lambdas/db-provision-user-database/src/index.ts
  tf-modules/cumulus-rds-tf/main.tf
  tf-modules/cumulus-rds-tf/outputs.tf
  tf-modules/cumulus-rds-tf/variables.tf
  website/sidebars.js
Labels: pr feedback
