Repository nasa/cumulus, pull requests merged in 2024-02, with the labels that each got.

#3581 CUMULUS-3587 - allow update
  audit-ci.json
Labels: high priority

#3535 CUMULUS-2891: Update files with ecs-client
  CHANGELOG.md
  example/package.json
  example/spec/helpers/ecsHelpers.js
  example/spec/parallel/testAPI/bulkDeleteFailureSpec.js
  example/spec/parallel/testAPI/bulkDeleteSuccessSpec.js
  example/spec/parallel/testAPI/bulkOperationsSuccessSpec.js
  example/spec/serial/AsyncOperationRunnerFailingLambdaSpec.js
  example/spec/serial/AsyncOperationRunnerNonExistentLambdaSpec.js
  example/spec/serial/AsyncOperationRunnerNonExistentPayloadSpec.js
  example/spec/serial/AsyncOperationRunnerNonJsonPayloadSpec.js
  example/spec/serial/AsyncOperationRunnerSuccessfulLambdaSpec.js
  packages/async-operations/package.json
  packages/async-operations/src/async_operations.ts
  packages/async-operations/tests/test-async_operations.js
  packages/aws-client/package.json
  packages/aws-client/src/services.ts
  packages/aws-client/src/test-utils.ts
  packages/aws-client/src/types.ts
  packages/aws-client/tests/test-services.js
  packages/integration-tests/index.js
  packages/tf-inventory/src/inventory.js
  packages/tf-inventory/src/stateFile.js
  packages/tf-inventory/tests/inventory.js
  packages/tf-inventory/tests/stateFile.js
Labels: needs review

#3583 Jk/bugfix/cumulus 3587 pull in express boom
  CHANGELOG.md
  bamboo/bootstrap-unit-tests.sh
  bamboo/cleanup-unit-tests.sh
  packages/api/app/distribution.js
  packages/api/app/index.js
  packages/api/lib/expressBoom.js
  packages/api/package.json
  packages/s3-credentials-endpoint/index.js
  packages/s3-credentials-endpoint/package.json
Labels: pr feedback, blocked
