Repository nasa/cumulus, pull requests merged in 2024-04, with the labels that each got.

#3612 Cumulus 3609 dla format retro script
  CHANGELOG.md
  lambdas/dla-migration/.nycrc.json
  lambdas/dla-migration/package.json
  lambdas/dla-migration/src/index.ts
  lambdas/dla-migration/tests/test-handler.js
  lambdas/dla-migration/tests/test-index.js
  packages/api/endpoints/dead-letter-archive.js
  packages/api/lambdas/write-db-dlq-records-to-s3.js
  packages/api/tests/lambdas/test-write-db-dlq-records-to-s3.js
  packages/aws-client/src/S3.ts
  packages/message/package.json
  packages/message/src/DeadLetterMessage.ts
  packages/message/tests/test-DeadLetterMessage.js
Labels: needs review

#3606 [CUMULUS-3519]: Update SQS and SNS to AWS SDK V3 Syntax
  CHANGELOG.md
  example/package.json
  example/spec/parallel/cnmWorkflow/CnmWorkflowFromSqsSpec.js
  example/spec/parallel/testAPI/snsRuleSpec.js
  packages/api/bin/serve.js
  packages/api/lambdas/message-consumer.js
  packages/api/lib/publishSnsMessageUtils.js
  packages/api/lib/rulesHelpers.js
  packages/api/package.json
  packages/api/tests/endpoints/collections/create-collection.js
  packages/api/tests/endpoints/collections/delete-collection.js
  packages/api/tests/endpoints/collections/update-collection.js
  packages/api/tests/endpoints/test-executions.js
  packages/api/tests/endpoints/test-granules.js
  packages/api/tests/endpoints/test-rules.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-index.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-write-pdr.js
  packages/api/tests/lambdas/test-bulk-granule-delete.js
  packages/api/tests/lambdas/test-bulk-operation.js
  packages/api/tests/lambdas/test-kinesis-consumer.js
  packages/api/tests/lambdas/test-message-consumer.js
  packages/api/tests/lib/rules/test-rulesHelpers.js
  packages/api/tests/lib/test-granule-delete.js
  packages/api/tests/lib/test-ingest.js
  packages/api/tests/lib/test-publishSnsMessageUtils.js
  packages/api/tests/lib/writeRecords/test-write-execution.js
  packages/api/tests/lib/writeRecords/test-write-granules.js
  packages/aws-client/src/SNS.ts
  packages/aws-client/src/SQS.ts
  packages/tf-inventory/src/inventory.js
Labels: in review

#3616 CUMULUS-2902: Removes aws-sdk from es-client. Updates usage to AWS SDK v3.
  CHANGELOG.md
  packages/es-client/esAmazonConnection.js
  packages/es-client/package.json
  packages/es-client/search.js
  packages/es-client/tests/search.js
Labels: pr feedback

#3626 [CUMULUS-3570] - Update Kinesis docs for DAR and refreshed AWS UI
  CHANGELOG.md
  docs/assets/cnm_create_kinesis_stream_V2.jpg
  docs/data-cookbooks/cnm-workflow.md
  docs/operator-docs/kinesis-stream-for-ingest.md
Labels: needs review

#3618 CUMULUS-2902: Removes dependency of aws-sdk from all packages
  CHANGELOG.md
  docs/configuration/monitoring.md
  example/lambdas/ftpPopulateTestLambda/package.json
  example/lambdas/ftpPopulateTestLambda/webpack.config.js
  example/package.json
  example/spec/parallel/s3Access/teaS3CredentialsSpec.js
  lambdas/sqs-message-remover/webpack.config.js
  package.json
  packages/api/package.json
  packages/api/webpack.config.js
  packages/aws-client/package.json
  packages/aws-client/src/CloudFormationGateway.ts
  packages/aws-client/src/SQS.ts
  packages/aws-client/src/client.ts
  packages/aws-client/src/lib/S3MultipartUploads.ts
  packages/aws-client/src/types.ts
  packages/aws-client/tests/test-CloudFormationGateway.js
  packages/aws-client/tests/test-client.js
  packages/common/package.json
  packages/ingest/package.json
  packages/integration-tests/package.json
  packages/integration-tests/webpack.config.js
  packages/s3-credentials-endpoint/webpack.config.js
  packages/tea-map-cache/webpack.config.js
  tasks/add-missing-file-checksums/webpack.config.js
  tasks/discover-granules/webpack.config.js
  tasks/discover-pdrs/webpack.config.js
  tasks/files-to-granules/webpack.config.js
  tasks/hello-world/webpack.config.js
  tasks/hyrax-metadata-updates/webpack.config.js
  tasks/lzards-backup/webpack.config.js
  tasks/move-granules/webpack.config.js
  tasks/orca-copy-to-archive-adapter/webpack.config.js
  tasks/orca-recovery-adapter/webpack.config.js
  tasks/parse-pdr/webpack.config.js
  tasks/pdr-status-check/webpack.config.js
  tasks/post-to-cmr/webpack.config.js
  tasks/queue-granules/webpack.config.js
  tasks/queue-pdrs/webpack.config.js
  tasks/queue-workflow/webpack.config.js
  tasks/send-pan/webpack.config.js
  tasks/sf-sqs-report/webpack.config.js
  tasks/sync-granule/webpack.config.js
  tasks/test-processing/webpack.config.js
  tasks/update-cmr-access-constraints/webpack.config.js
  tasks/update-granules-cmr-metadata-file-links/webpack.config.js
  tf-modules/internal/cumulus-test-cleanup/package.json
  tf-modules/internal/cumulus-test-cleanup/webpack.config.js
  tf-modules/s3-replicator/index.js
  tf-modules/s3-replicator/package.json
Labels: pr feedback

#3631 CUMULUS-3425 - fix CHANGELOG
  CHANGELOG.md
Labels: needs review, Very Small

#3623 Update deployment templates for Aurora Serverless v2
  CHANGELOG.md
  example/rds-cluster-tf/main.tf
  example/rds-cluster-tf/outputs.tf
  example/rds-cluster-tf/terraform.tfvars.example
  example/rds-cluster-tf/variables.tf
  tf-modules/cumulus-rds-tf/main.tf
  tf-modules/cumulus-rds-tf/outputs.tf
  tf-modules/cumulus-rds-tf/variables.tf
Labels: pr feedback

#3629 CUMULUS-3673: Fixes Granules API URI encoding by escaping path components.
  CHANGELOG.md
  example/spec/helpers/Collections.js
  example/spec/parallel/cnmWorkflow/CnmWorkflowFromSqsSpec.js
  example/spec/parallel/cnmWorkflow/KinesisTestTriggerSpec.js
  example/spec/parallel/createReconciliationReport/CreateReconciliationReportSpec.js
  example/spec/parallel/dbRecords/DeadLetterArchiveProcessingSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesDuplicateHandlingSkipSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesHttpsSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesS3SuccessSpec.js
  example/spec/parallel/discoverGranules/DiscoverGranulesWithExecutionNamePrefixSpec.js
  example/spec/parallel/ingest/ingestFromPdrSpec.js
  example/spec/parallel/ingest/ingestFromPdrWithChildWorkflowMetaSpec.js
  example/spec/parallel/ingest/ingestFromPdrWithExecutionNamePrefixSpec.js
  example/spec/parallel/ingest/ingestPdrWithNodeNameSpec.js
  example/spec/parallel/ingestGranule/IngestElevenGiBFileSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleFailureSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleFtpSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestGranulePythonProcessingSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleSuccessSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleWithDuplicateHandlingErrorSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleWithDuplicateHandlingVersionSpec.js
  example/spec/parallel/ingestGranule/IngestGranuleWithModificationSpec.js
  example/spec/parallel/ingestGranule/IngestUMMGSuccessSpec.js
  example/spec/parallel/ingestGranule/ingestGranuleQueueSpec.js
  example/spec/parallel/lzardsBackup/LzardsBackupFromDistributionSpec.js
  example/spec/parallel/lzardsBackup/LzardsBackupSpec.js
  example/spec/parallel/multiQueue/DiscoverGranulesMultiQueueSpec.js
  example/spec/parallel/orca/OrcaBackupAndRecoverySpec.js
  example/spec/parallel/queueGranules/QueueGranulesSpec.js
  example/spec/parallel/queueGranules/queueGranulesPostProcessingSpec.js
  example/spec/parallel/syncGranule/SyncGranuleDuplicateHandlingSpec.js
  example/spec/parallel/syncGranule/SyncGranuleSuccessSpec.js
  example/spec/parallel/testAPI/bulkDeleteFailureSpec.js
  example/spec/parallel/testAPI/bulkDeleteSuccessSpec.js
  example/spec/parallel/testAPI/bulkOperationsSuccessSpec.js
  example/spec/parallel/testAPI/executionSpec.js
  example/spec/parallel/testAPI/granuleSpec.js
  example/spec/parallel/testAPI/sqsRuleSpec.js
  example/spec/serial/DiscoverGranulesHttpSpec.js
  example/spec/serial/ingestPdrWithNodeNameFtpSpec.js
  example/spec/serial/multiQueue/ParsePdrBatchQueueSpec.js
  packages/api-client/src/granules.ts
  packages/api-client/tests/test-granules.js
Labels: pr feedback

#3635 Updates supertest to fix critical vulnerability
  package.json
Labels: needs review
