Repository nasa/cumulus, pull requests merged in 2025-03, with the labels that each got.

#3923 CUMULUS-4006: update changelog and release instructions
  CHANGELOG.md
  docs/development/release.md
  packages/api/ecs/async-operation/README.md
  tf-modules/cumulus/variables.tf
Labels: needs review

#3926 CUMULUS-3993: Fix integration test ingestFromPdrSpec.js
  example/spec/parallel/ingest/ingestFromPdrSpec.js
Labels: Very Small

#3928 Add release 18.5.5 18.5.3 changelog to master and remove duplicate entry from package.json
  CHANGELOG.md
  tasks/update-granules-cmr-metadata-file-links/package.json
Labels: needs review, Very Small

#3935 CUMULUS-4018: Fix Postgres pagination missing records issue by sorting on cumulus_id
  CHANGELOG.md
  packages/db/src/search/StatsSearch.ts
  packages/db/src/search/queries.ts
  packages/db/tests/search/test-PdrSearch.js
  packages/db/tests/search/test-queries.js
Labels: needs review

#3932 Cumulus 3960 merge to 18.5 release
  CHANGELOG.md
  example/data/collections/s3_MOD09GQ-AZ_006_full_ingest_move/s3_MOD09GQ-AZ_006.json
  example/spec/helpers/Collections.js
  example/spec/parallel/changeGranuleCollections/ChangeGranuleCollectionPG.js
  example/spec/parallel/changeGranuleCollections/ChangeGranuleCollectionS3.js
  example/spec/parallel/changeGranuleCollections/ChangeGranuleCollectionWorkflowSpec.js
  packages/cmrjs/src/cmr-utils.js
  packages/cmrjs/src/index.js
  tasks/change-granule-collection-pg/schemas/config.json
  tasks/change-granule-collection-pg/schemas/input.json
  tasks/change-granule-collection-pg/src/index.ts
  tasks/change-granule-collection-pg/tests/data/payload_base.json
  tasks/change-granule-collection-pg/tests/test-index.js
  tasks/change-granule-collection-s3/src/index.ts
  tasks/change-granule-collection-s3/src/update_cmr_file_collection.ts
  tasks/post-to-cmr/.nycrc.json
  tasks/post-to-cmr/README.md
  tasks/post-to-cmr/index.js
  tasks/post-to-cmr/package.json
  tasks/post-to-cmr/schemas/config.json
  tasks/post-to-cmr/tests/cmr-test.js
  tf-modules/cumulus/workflows.tf
  tf-modules/workflows/change_granule_collections_workflow.asl.json
  tf-modules/workflows/main.tf
  tf-modules/workflows/variables.tf
Labels: needs review, in review

#3911 CUMULUS-3842: Delete DynamoDB ReconciliationReportsTable
  CHANGELOG.md
  lambdas/reconciliation-report-migration/.nycrc.json
  lambdas/reconciliation-report-migration/README.md
  lambdas/reconciliation-report-migration/iam.tf
  lambdas/reconciliation-report-migration/main.tf
  lambdas/reconciliation-report-migration/outputs.tf
  lambdas/reconciliation-report-migration/package.json
  lambdas/reconciliation-report-migration/src/index.ts
  lambdas/reconciliation-report-migration/src/reconciliation-reports.ts
  lambdas/reconciliation-report-migration/src/types.ts
  lambdas/reconciliation-report-migration/tests/test-index.js
  lambdas/reconciliation-report-migration/tests/test-reconciliation-reports.js
  lambdas/reconciliation-report-migration/tsconfig.json
  lambdas/reconciliation-report-migration/variables.tf
  lambdas/reconciliation-report-migration/versions.tf
  lambdas/reconciliation-report-migration/webpack.config.js
  packages/api/bin/serve.js
  packages/api/models/index.js
  packages/api/tests/models/test-reconciliation-reports-model.js
  tf-modules/archive/api.tf
  tf-modules/cumulus/reconciliation_report_migration.tf
  tf-modules/data-persistence/dynamo.tf
  tf-modules/data-persistence/outputs.tf
Labels: pr feedback

#3939 Merge release v20.0.1 notes to master
  CHANGELOG.md
  example/spec/parallel/lzardsBackup/LzardsBackupFromDistributionSpec.js
  scripts/generate_records/package.json
Labels: Very Small

#3934 CUMULUS-4019: Support case-insensitive comparison in lzards-backup
  CHANGELOG.md
  tasks/lzards-backup/src/index.ts
  tasks/lzards-backup/tests/test-index.js
Labels: needs review, User Contribution

#3944 CUMULUS-4019: Support case-insensitive comparison in lzards-backup (#3934)
  CHANGELOG.md
  example/spec/parallel/lzardsBackup/LzardsBackupFromDistributionSpec.js
  tasks/lzards-backup/src/index.ts
  tasks/lzards-backup/tests/test-index.js
Labels: needs review, Very Small
