Repository nasa/cumulus, pull requests merged in 2025-05, with the labels that each got.

#3977 Jk/cumulus 4061
  CHANGELOG.md
  packages/ingest/src/granule.ts
  packages/ingest/test/test-granule.js
Labels: needs review

#3990 [CUMULUS-4085]: Add config value for unique Granule IDs
  CHANGELOG.md
  tasks/files-to-granules/index.js
  tasks/files-to-granules/package.json
  tasks/files-to-granules/schemas/config.json
  tasks/files-to-granules/tests/data/output.json
  tasks/files-to-granules/tests/data/payload.json
  tasks/files-to-granules/tests/test-index.js
Labels: pr feedback

#3936 fix sftp-client usage docs
  packages/sftp-client/README.md
Labels: needs review, User Contribution
