Repository nasa/cumulus, pull requests merged in 2025-01, with the labels that each got.

#3890 Jk/cumulus 3940 to main from #3877 (#3877)
  CHANGELOG.md
  docs/features/dead_letter_archive.md
  example/cumulus-tf/main.tf
  example/cumulus-tf/variables.tf
  package.json
  packages/api/endpoints/dead-letter-archive.js
  packages/api/lambdas/process-s3-dead-letter-archive.js
  packages/api/lambdas/sf-event-sqs-to-db-records/index.js
  packages/api/lib/writeRecords/write-granules.js
  packages/api/package.json
  packages/api/performance_tests.sh
  packages/api/tests/endpoints/test-dead-letter-archive.js
  packages/api/tests/performance/lib/test-write-granules.js
  packages/async-operations/.nycrc.json
  packages/async-operations/src/async_operations.ts
  packages/async-operations/tests/test-async_operations.js
  tf-modules/archive/api.tf
  tf-modules/archive/async_operation.tf
  tf-modules/archive/iam.tf
  tf-modules/archive/variables.tf
  tf-modules/cumulus/archive.tf
  tf-modules/cumulus/variables.tf
Labels: needs review

#3894 CUMULUS-3965:Update launch templates to require IMDSv2
  CHANGELOG.md
  example/fake-provider-cf.yml
  tf-modules/cumulus/ecs_cluster.tf
Labels: needs review

#3902 CUMULUS-3981: AWS ServiceException has required $metadata field
  CHANGELOG.md
  packages/api/tests/endpoints/test-execution-status.js
  packages/api/tests/lambdas/test-sf-starter.js
  packages/aws-client/tests/test-Kinesis.js
  packages/aws-client/tests/test-StepFunctions.js
  tasks/pdr-status-check/tests/index.js
Labels: needs review

#3905 CUMULUS-3967 -- Forward port of release fix -- Pin @aws-sdk/client-s3 to 3.726 due to unit failure in > 3.729.0
  CHANGELOG.md
  example/lambdas/s3AccessTest/package.json
  example/lambdas/snsS3Test/package.json
  packages/aws-client/package.json
  packages/common/package.json
  tf-modules/internal/cumulus-test-cleanup/package.json
Labels: high priority

#3897 CUMULUS-3847: Remove any remaining ES indexing functions and tests
  CHANGELOG.md
  example/deployments/cumulus/sandbox.tfvars
  example/spec/serial/AsyncOperationRunnerFailingLambdaSpec.js
  example/spec/serial/AsyncOperationRunnerNonExistentLambdaSpec.js
  example/spec/serial/AsyncOperationRunnerNonExistentPayloadSpec.js
  example/spec/serial/AsyncOperationRunnerNonJsonPayloadSpec.js
  example/spec/serial/AsyncOperationRunnerSuccessfulLambdaSpec.js
  packages/api/app/routes.js
  packages/api/ecs/async-operation/tests/test-index.js
  packages/api/endpoints/elasticsearch.js
  packages/api/lambdas/bootstrap.js
  packages/api/lambdas/bulk-operation.js
  packages/api/lambdas/cleanExecutions.js
  packages/api/lambdas/create-reconciliation-report-types.js
  packages/api/lambdas/create-reconciliation-report.js
  packages/api/lambdas/index-from-database.js
  packages/api/lambdas/process-s3-dead-letter-archive.js
  packages/api/lambdas/sf-event-sqs-to-db-records/index.js
  packages/api/lambdas/sf-event-sqs-to-db-records/write-pdr.js
  packages/api/lib/granules.js
  packages/api/lib/mmt.js
  packages/api/lib/orca.js
  packages/api/lib/reconciliationReport.js
  packages/api/lib/testUtils.js
  packages/api/tests/endpoints/providers/delete-provider.js
  packages/api/tests/endpoints/test-elasticsearch.js
  packages/api/tests/endpoints/test-executions.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-index.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-write-pdr.js
  packages/api/tests/lambdas/test-bootstrap.js
  packages/api/tests/lambdas/test-bulk-granule-delete.js
  packages/api/tests/lambdas/test-bulk-operation.js
  packages/api/tests/lambdas/test-cleanExecutions.js
  packages/api/tests/lambdas/test-create-reconciliation-report.js
  packages/api/tests/lambdas/test-index-from-database.js
  packages/api/tests/lib/test-ingest.js
  packages/api/tests/lib/test-reconciliationReport.js
  packages/api/tests/performance/lib/test-write-granules.js
  packages/api/webpack.config.js
  packages/async-operations/tests/test-async_operations.js
  packages/aws-client/src/services.ts
  packages/aws-client/tests/test-services.js
  packages/db/src/models/reconciliation_report.ts
  packages/db/src/test-utils.ts
  packages/db/tests/translate/test-async-operations.js
  packages/tf-inventory/src/inventory.js
  packages/tf-inventory/tests/inventory.js
  tf-modules/archive/api.tf
  tf-modules/archive/bootstrap.tf
  tf-modules/archive/index_from_database.tf
  tf-modules/archive/reconciliation_report.tf
Labels: pr feedback, high priority, release-critical

#3907 CUMULUS-3990: Upgrade localstack from 3.0.0 to 4.0.3
  CHANGELOG.md
  bamboo/docker-compose-local.yml
  bamboo/docker-compose.yml
  example/lambdas/s3AccessTest/package.json
  example/lambdas/snsS3Test/package.json
  packages/api/tests/endpoints/collections/create-collection.js
  packages/api/tests/endpoints/collections/delete-collection.js
  packages/api/tests/endpoints/collections/update-collection.js
  packages/api/tests/endpoints/test-granules.js
  packages/api/tests/lambdas/sf-event-sqs-to-db-records/test-write-pdr.js
  packages/api/tests/lib/rules/test-rulesHelpers.js
  packages/api/tests/lib/test-publishSnsMessageUtils.js
  packages/api/tests/lib/writeRecords/test-write-execution.js
  packages/api/tests/lib/writeRecords/test-write-granules.js
  packages/api/tests/performance/lib/test-write-granules.js
  packages/aws-client/package.json
  packages/common/package.json
  tasks/queue-workflow/tests/index.js
  tf-modules/internal/cumulus-test-cleanup/package.json
Labels: needs review

#3913 Move 'move_granule_collections_workflow' from example to /tf-modules/…
  example/cumulus-tf/move_granule_collections_workflow.tf
  tf-modules/cumulus/main.tf
  tf-modules/cumulus/outputs.tf
  tf-modules/cumulus/variables.tf
  tf-modules/cumulus/workflows.tf
  tf-modules/workflows/main.tf
  tf-modules/workflows/move_granule_collections_workflow.asl.json
  tf-modules/workflows/variables.tf
Labels: work in progress, needs review
